### ISSUE TITLE
Cannot require fuse-box in node shell ?

### ISSUE THREAD

**Issue by scarletsky** [fuse-box/fuse-box#1088] opened 2018-02-01 02:31 UTC
Thanks for your great work !

I am new to fuse-box, and I want to test it on node shell. However I got the following error:

```
$ node
> require('fuse-box')
TypeError: Cannot read property 'filename' of undefined
    at Object.<anonymous> (/Users/x/testlibs/node_modules/fuse-box/Config.js:6:32)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/x/testlibs/node_modules/fuse-box/CacheBreaker.js:3:18)
    at Module._compile (module.js:635:30)
```

Why can't I require it in the node shell ?

**Comment by nchanged** [comment] 2018-02-01 08:33
hi!
Because it's not installed probably?

**Comment by scarletsky** [comment] 2018-02-01 10:00
@nchanged If it's not installed, it should throw the following error:

```
$ node
> require('fuse-box')
Error: Cannot find module 'fuse-box'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at repl:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:441:10)
```

**Comment by nchanged** [comment] 2018-02-01 10:08
@scarletsky how about importing a bundle
`require("fuse-box/es6")`

**Comment by scarletsky** [comment] 2018-02-01 10:11
@nchanged The same result.

```
> require('fuse-box/es6')
TypeError: Cannot read property 'filename' of undefined
    at _df3d.f.(anonymous function) (/Users/scarlex/Projects/testlibs/node_modules/fuse-box/es6/es6.js:168:32)
    at Object._df3d.r (/Users/scarlex/Projects/testlibs/node_modules/fuse-box/es6/es6.js:26:9)
    at _df3d.f.(anonymous function) (/Users/scarlex/Projects/testlibs/node_modules/fuse-box/es6/es6.js:131:24)
    at Object._df3d.r (/Users/scarlex/Projects/testlibs/node_modules/fuse-box/es6/es6.js:26:9)
    at _df3d.f.(anonymous function) (/Users/scarlex/Projects/testlibs/node_modules/fuse-box/es6/es6.js:32:30)
    at Object._df3d.r (/Users/scarlex/Projects/testlibs/node_modules/fuse-box/es6/es6.js:26:9)
    at Object.<anonymous> (/Users/scarlex/Projects/testlibs/node_modules/fuse-box/es6/es6.js:11418:24)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
> require('fuse-box')
TypeError: Cannot read property 'filename' of undefined
    at Object.<anonymous> (/Users/scarlex/Projects/testlibs/node_modules/fuse-box/Config.js:6:32)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/scarlex/Projects/testlibs/node_modules/fuse-box/CacheBreaker.js:3:18)
    at Module._compile (module.js:635:30)
```

What's more, it works when I run `node fuse.js`. It just can not run in node shell.

**Comment by nchanged** [comment] 2018-02-01 10:59
@scarletsky I will see it fixed! thanks for reporting

**Comment by aswin-s** [comment] 2018-02-06 10:15
Same here. Worked fine till 3.0.2. Looks like require variable got over ridden in Config.ts & CacheBreaker.ts. Calling require as a constructor works fine.

Comparing compiled versions
v3.0.2
```
const MAIN_FILE = require.main.filename;
```
v3.1.0
```
const MAIN_FILE = _a3f9.main.filename;
```

**Comment by nchanged** [comment] 2018-02-06 10:47
so it's broken in `3.1.0`?

**Comment by aswin-s** [comment] 2018-02-06 10:49
@nchanged Yes. It broke with latest update

**Comment by nchanged** [comment] 2018-02-06 10:50
@aswin-s thanks, i know where the problem is, will be fixed in the `next`

**Comment by nchanged** [comment] 2018-02-06 11:36
@aswin-s please, verify `3.1.1-next.1` and I will release the patch  (`3.1.1`) ASAP

**Comment by scarletsky** [comment] 2018-02-06 11:40
```
$ cat node_modules/fuse-box/package.json
{
  "name": "fuse-box",
  "version": "3.1.1-next.1",
  "description": "Fuse-Box a bundler that does it right",
...

$ node
> require('fuse-box')
TypeError: Cannot read property 'filename' of undefined
    at Object.<anonymous> (/Users/scarlex/Projects/testlibs/node_modules/fuse-box/Config.js:6:32)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/scarlex/Projects/testlibs/node_modules/fuse-box/CacheBreaker.js:3:18)
    at Module._compile (module.js:635:30)
>
```

**Comment by nchanged** [comment] 2018-02-06 11:41
@scarletsky that's a different story ;-)

**Comment by scarletsky** [comment] 2018-02-06 11:41
@nchanged Oh, I see. Sorry 😥

**Comment by nchanged** [comment] 2018-02-06 11:42
@scarletsky I will tend to that problem soon enough ;-)

**Comment by aswin-s** [comment] 2018-02-06 13:04
@nchanged Yes its working now! Thanks

**Comment by nchanged** [comment] 2018-02-06 14:57
@aswin-s `3.1.1`

**Comment by paxperscientiam** [comment] 2018-10-19 02:05
@nchanged looks like this is still a problem (or there was a regression). Using version 3.5.0

```javascript
> require("fuse-box")
TypeError: Cannot read property 'filename' of undefined
    at Object.<anonymous> (/Users/ramos/Documents/apache2/www/clients/me/paxperscientiam.com/source/resources/modules.noSync/node_modules/fuse-box/Config.js:6:32)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
> require("fuse-box/es6")
TypeError: Cannot read property 'filename' of undefined
    at Object._2c04.f.(anonymous function) (/Users/ramos/Documents/apache2/www/clients/me/paxperscientiam.com/source/resources/modules.noSync/node_modules/fuse-box/es6/es6.js:166:32)
    at Object._2c04.r (/Users/ramos/Documents/apache2/www/clients/me/paxperscientiam.com/source/resources/modules.noSync/node_modules/fuse-box/es6/es6.js:26:8)
    at Object._2c04.f.(anonymous function) (/Users/ramos/Documents/apache2/www/clients/me/paxperscientiam.com/source/resources/modules.noSync/node_modules/fuse-box/es6/es6.js:129:24)
    at Object._2c04.r (/Users/ramos/Documents/apache2/www/clients/me/paxperscientiam.com/source/resources/modules.noSync/node_modules/fuse-box/es6/es6.js:26:8)
    at Object._2c04.f.(anonymous function) (/Users/ramos/Documents/apache2/www/clients/me/paxperscientiam.com/source/resources/modules.noSync/node_modules/fuse-box/es6/es6.js:32:30)
    at Object._2c04.r (/Users/ramos/Documents/apache2/www/clients/me/paxperscientiam.com/source/resources/modules.noSync/node_modules/fuse-box/es6/es6.js:26:8)
>
```

**Comment by nchanged** [comment] 2018-10-19 05:40
@scarletsky it is trying to locate a file which it has been launched from. Anyway, why would one do that?

**Comment by scarletsky** [comment] 2018-10-24 13:42
For me, I will use node shell to test a node module.

**Comment by nchanged** [comment] 2019-08-27 13:19
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.

**Closed by nchanged** 2019-08-27 13:19 UTC
Labels: bug

**Comment by evan-boissonnot** [comment] 2021-11-30 11:20
Hi, 

I'm using : "fuse-box": "^4.0.1-next.8",
When I run node fuse, to my file fuse.js, got the prob : 

node_modules\fuse-box\env.js:20
    SCRIPT_FILE: require.main.filename,
    
    here my fuse.js file : 
    import { fusebox } from 'fuse-box';

const fuse = fusebox({
    entry: 'src/main.ts',
    target: 'browser',
    devServer: true,
    webIndex: {
        template: 'src/index.html',
      },
    webIndex: true,
  });
  
  fuse.runDev();
