### ISSUE TITLE
Custom shim names not working

### ISSUE THREAD

**Issue by selfagency** [fuse-box/fuse-box#1405] opened 2018-10-10 19:32 UTC
Per the documentation [here](https://fuse-box.org/docs/development/configuration):

>  you can replace `jquery` with `foo` and use `import "foo"` to get a jquery instance

However, when I attempt to use the following, I get the error:
` uncaught exception: Package not found waypoints-infinite`.

From `fuse.js`:
```
fuse
  .bundle('nylon')
  .shim({
    jquery: {
      source: 'node_modules/jquery/dist/jquery.js',
      exports: '$'
    },
    waypoints: {
      source: 'node_modules/waypoints/src/waypoint.js',
      exports: 'Waypoint'
    },
    'waypoints-infinite': {
      source: 'node_modules/waypoints/lib/shortcuts/infinite.js'
    },
    'waypoints-sticky': {
      source: 'node_modules/waypoints/lib/shortcuts/sticky.js'
    }
  })
  .instructions(' > scripts/nylon.js')
  .hmr()
  .sourceMaps(true)
  .watch()
```

From my code:

```
import 'waypoints-infinite'
import 'waypoints-sticky'
```

I also tried it this way and got the same error:

```
const fuse = FuseBox.init({
  homeDir: 'src',
  target: 'browser@es5',
  output: 'public/scripts/$name.js',
  allowSyntheticDefaultImports: true,
  useTypescriptCompiler: true,
  sourceMaps: { inline: false, sourceRoot: '/public/scripts' },
  plugins: [JSONPlugin()],
  shim: {
    jquery: {
      source: 'node_modules/jquery/dist/jquery.js',
      exports: '$'
    },
    waypoints: {
      source: 'node_modules/waypoints/src/waypoint.js',
      exports: 'Waypoint'
    },
    'waypoints-infinite': {
      source: 'node_modules/waypoints/lib/shortcuts/infinite.js'
    },
    'waypoints-sticky': {
      source: 'node_modules/waypoints/lib/shortcuts/sticky.js'
    }
  }
})
```

**Comment by nchanged** [comment] 2018-10-10 20:15
@selfagency your shim `waypoints-infinite` doesn't have the exports key. If there is none a shim is executed right away on page load, as if you included a script in the head.  So there is no sense in importing it per se. Hope that explains it.

I will close this now, the issue is obvious. Feel free ask more questions here.

**Closed by nchanged** 2018-10-10 20:15 UTC

**Comment by selfagency** [comment] 2018-10-10 20:21
The issue with `waypoints-infinite` and `waypoints-sticky` is that they don't export their own methods, they add methods to the Waypoints object. [See here](https://github.com/imakewebthings/waypoints/blob/master/lib/shortcuts/infinite.js) for example. How would I import this as such?

**Comment by selfagency** [comment] 2018-10-10 20:31
OK but if it'll just work without an export, why am I getting an uncaught exception that stops script execution telling me that the package can't be found? Does that mean I should just remove those import calls from the script and they'll load nonetheless?

**Comment by selfagency** [comment] 2018-10-10 20:58
So I did the above, removing the import statements for shimmed scripts from my code. The `Package not found` errors stopped. But now, I'm getting this:

```
16:54:10.766 TypeError: "Waypoint.Sticky is not a constructor"
	navBar https://nylon.test:4444/nylon.js:13323:24
	execute https://nylon.test:4444/nylon.js:10581:5
	<anonymous> https://nylon.test:4444/nylon.js:10632:21
	step https://nylon.test:4444/nylon.js:31475:22
	verb https://nylon.test:4444/nylon.js:31456:57
	__awaiter https://nylon.test:4444/nylon.js:31449:75
	__awaiter https://nylon.test:4444/nylon.js:31445:16
	<anonymous> https://nylon.test:4444/nylon.js:10629:57
	wrapped https://nylon.test:4444/nylon.js:25534:16
	context https://nylon.test:4444/nylon.js:25468:12
	<anonymous> https://nylon.test:4444/nylon.js:10629:9
	step https://nylon.test:4444/nylon.js:31475:22
	verb https://nylon.test:4444/nylon.js:31456:57
	__awaiter https://nylon.test:4444/nylon.js:31449:75
	__awaiter https://nylon.test:4444/nylon.js:31445:16
	<anonymous> https://nylon.test:4444/nylon.js:10612:45
	completed https://nylon.test:4444/nylon.js:16152:9
```

When I check the Waypoints object in the console, neither Infinite nor Sticky have been added as methods.

**Comment by nchanged** [comment] 2018-10-11 04:36
Can u reproduce this issue in the repository? I will take a look!

**Comment by selfagency** [comment] 2018-10-11 15:08
@nchanged here you go https://bitbucket.org/selfagency/fusebox-issue/

**Comment by nchanged** [comment] 2018-10-11 16:41
```
shim: {
    jquery: {
      source: 'node_modules/jquery/dist/jquery.js',
      exports: '$'
    },
    waypoints: {
      source: 'node_modules/waypoints/src/waypoint.js',
      exports: 'Waypoint'
    },
    'waypoints-infinite': {
      source: 'node_modules/waypoints/lib/shortcuts/infinite.js',
       exports: 'WaypointInifinite'
    },
    'waypointssticky': {
      source: 'node_modules/waypoints/lib/shortcuts/sticky.js',
      exports: 'WaypointSticky'
    }
  }
```
well, as it turns out exports is required.
But there is another issue with `intermediate value`. FuseBox didn't modify this code at all

**Comment by nchanged** [comment] 2018-10-11 16:43
That's Waypoint's issue. 

```js
window.Waypoint = Waypoint
}()) // <--- semicolon is essential
```

I would recommend just copying this file and modifying it manually. Just to compare, jQuery has a semicolon at the end of the script.

**Comment by selfagency** [comment] 2018-10-11 16:44
hmm, i don't use semicolons in my own js usually. will that be an issue? or is this just an issue for vendor libraries?

**Comment by nchanged** [comment] 2018-10-11 16:46
Yes, that's the issue of that vendor library. If you don't use semicolon in this case and keep writing the code - javascript won't like - Syntax Error.

The following code will result in error.
```js
(function(){
}())
alert(1)
```

**Comment by selfagency** [comment] 2018-10-12 05:54
Ok, so I got all that working in development. Thanks for your help with that. However, now that I'm trying to make a production bundle, I'm getting:

```
ReferenceError: $ is not defined[Learn More] nylon.js:1:113308
  Un.f[80] https://dev.nylon.com/public/scripts/nylon.js:1:113308
  r.r https://dev.nylon.com/public/scripts/nylon.js:1:192
  Un.f[0] https://dev.nylon.com/public/scripts/nylon.js:1:573
  r.r https://dev.nylon.com/public/scripts/nylon.js:1:192
  <anonymous> https://dev.nylon.com/public/scripts/nylon.js:1:271108
  <anonymous> https://dev.nylon.com/public/scripts/nylon.js:1:460
```

Here's my config:

```
const { FuseBox, JSONPlugin, QuantumPlugin } = require('fuse-box')

const fuse = FuseBox.init({
  homeDir: 'src',
  target: 'browser@es5',
  output: 'public/scripts/$name.js',
  allowSyntheticDefaultImports: true,
  useTypescriptCompiler: true,
  sourceMaps: { inline: false, sourceRoot: '/public/scripts' },
  plugins: [
    QuantumPlugin({
      target: 'browser',
      bakeApiIntoBundle: true,
      treeshake: false,
      uglify: true
    }),
    JSONPlugin()
  ]
})

fuse
  .bundle('nylon')
  .shim({
    jquery: {
      source: 'node_modules/jquery/dist/jquery.js',
      exports: '$'
    },
    'jquery-prefetch': {
      source: 'node_modules/jquery-prefetch/jquery.prefetch.js'
    },
    'animate-css': {
      source: 'node_modules/@claviska/jquery-animate-css/jquery.animateCSS.js',
      exports: '$.fn.animateCSS'
    },
    waypoints: {
      source: 'node_modules/waypoints/lib/noframework.waypoints.js',
      exports: 'Waypoints'
    },
    'waypoints-infinite': {
      source: 'node_modules/waypoints/lib/shortcuts/infinite.js',
      exports: 'WaypointsInfinite'
    },
    'waypoints-sticky': {
      source: 'node_modules/waypoints/lib/shortcuts/sticky.js',
      exports: 'WaypointsSticky'
    }
  })
  .instructions(' > scripts/nylon.js')
  .sourceMaps({
    project: true,
    vendor: false,
    inline: true
  })

fuse.run()
```

Shouldn't my shims be getting packaged in the bundle? When I look at the output JS, it doesn't seem that they are.

**Comment by nchanged** [comment] 2018-10-12 06:27
@selfagency make sure to clear the cache! It should be there

**Comment by selfagency** [comment] 2018-10-12 06:29
I did...

**Comment by selfagency** [comment] 2018-10-12 06:32
Disabled the cache and it worked.
