### ISSUE TITLE
incremental build

### ISSUE THREAD

**Issue by zeniroy** [fuse-box/fuse-box#751] opened 2017-08-24 07:50 UTC
I am surprised at build speed of fuse-box. So i tried to migrate webpack to fuse-box, and almost done.
But i found there is no function about incremental build that is so important hot-module-replacement speed. Webpack is slower on startup build than fuse-box, but when file changed, webpack updates faster than fuse-box in my project. 

Is there any option for incremental build that i missed? or something i can try for hot-module-replacement speed faster?

**Comment by nchanged** [comment] 2017-08-24 07:53
hi @zeniroy 
1) How much time does it take to rebuild your project (it's logged)?
2) How many files do you currently have in your project (approx)?
3) Are you referring to the runtime update?

**Comment by zeniroy** [comment] 2017-08-24 10:25
1. about 7s
2. bundle result : 129 files, 1.3MB. react web project.
3. Yes, i'm using hmr.

**Comment by nchanged** [comment] 2017-08-24 10:35
Is cache enabled?

**Comment by zeniroy** [comment] 2017-08-24 10:49
of course.

**Comment by nchanged** [comment] 2017-08-24 11:07
Ok, 7s is way too long, something is off there, please run it with `--debug` option, and see which file takes the longest time to compile, besides the point, you could try using `customModules` http://fuse-box.org/page/configuration#custom-modules-folder to split you code into logical parts, where the entire package will be cached, with this approach you will decrease your build time from 7s to 0.5 seconds.

**Comment by nchanged** [comment] 2017-08-24 11:08
Secondly, are you using Sass?

**Comment by zeniroy** [comment] 2017-08-24 11:52
1.
So, your suggestion is splitting bundle into more files for less re-compile time?

2.
yes, i am using sass. 

3.
When one file changed on fuse-box, it seems that all the files are re-compiled.(all files are shown on the compiled list). But webpack compiles only modified file and related files. Why fuse-box do that?

**Comment by nchanged** [comment] 2017-08-24 12:01
1) You could try
2) Voila! you should get a significant boost with `2.2.3-beta.10`
3) that's not true, i suspect Sass file get re-compiled each time, but beta.10 fixes it

**Comment by zeniroy** [comment] 2017-08-24 13:17
i tried 2.2.3-beta.10. but same.
And I checked where is bottleneck, i found big js files that i imported takes time.
makeAnalysis Function in File.ts is called everytime on every js files when rebuild.
Is it normal situation?

**Comment by nchanged** [comment] 2017-08-24 13:36
Is it a javascript file or a ts file? 

I guess no..

**Comment by nchanged** [comment] 2017-08-24 14:06
Could you reproduce it? Cuz i've put a 500kb file to test, and `makeAnalysis` didn't happen resulting in 50ms reload.

**Comment by zeniroy** [comment] 2017-08-25 04:19
Ok i made simple example.

``` javascript
// fuse.js
const { FuseBox } = require('fuse-box');

let fuse = new FuseBox({
        log: true,
        debug: true,
        homeDir: 'src',
        output: 'build/$name.js'
});

fuse.bundle('test').instructions(`> index.tsx`).watch().hmr();
fuse.dev();
fuse.run();

// src/index.tsx
import "./jquery-ui-1.10.3.min.js";
```

And I add console.log on File.js
``` javascript
180         console.log("call analyze!", this.info.fuseBoxPath);
181         let start = new Date();
182         this.analysis.analyze(traversalOptions);
183         console.log("end analyze!", new Date() - start);
```
and the result is

```{r, engine='bash', count_lines}
-- cache cleared ---
13:08:44: Typescript : Captured  index.jsx
13:08:45: TypeScript : Transpile index.jsx
→Typescript config file was not found. Improvising
call analyze! index.jsx
end analyze! 3
call analyze! jquery-ui-1.10.3.min.js
end analyze! 186
call analyze! index.js
end analyze! 1
call analyze! index.js
end analyze! 3
call analyze! index.js
end analyze! 5

--------------------------
Bundle "test"

    index.jsx
    jquery-ui-1.10.3.min.js
└──  (2 files,  223.1 kB) default
└── fusebox-hot-reload 2.3 kB (1 files)
└── fusebox-websocket 2.9 kB (1 files)
└── events 9.8 kB (1 files)                                                                              /415]
size: 238.1 kB in 1s 23ms

---------------------------------------------------
Development server running http://localhost:4444
---------------------------------------------------

13:08:46: HMR is enabled




13:09:00: Typescript : Captured  index.jsx
13:09:00: TypeScript : Transpile index.jsx
call analyze! index.jsx
end analyze! 0
13:09:00: Source changed for index.jsx
call analyze! jquery-ui-1.10.3.min.js
end analyze! 153

--------------------------
Bundle "test"

    index.jsx
    jquery-ui-1.10.3.min.js
└──  (2 files,  223.1 kB) default
└── fusebox-hot-reload@0.0.0 2.3 kB (0 files)
└── fusebox-websocket@0.0.0 2.9 kB (0 files)
└── events@0.0.0 9.8 kB (0 files)
size: 238.1 kB in 391ms
```

As you can see, when i changed index.tsx, fuse-box analyze "jquery-ui-1.10.3.min.js" file, and it takes some time. I think it needs some cache for speed.

**Comment by nchanged** [comment] 2017-08-25 07:06
That's really odd! I can't reproduce it. Could you make a sample repository, please?

**Comment by zeniroy** [comment] 2017-08-28 06:22
Ok, i made it.

https://github.com/zeniroy/fuse-box-analyze-problem

instructions
1. npm install
2. node fuse
3. and change src/index.tsx

**Comment by nchanged** [comment] 2017-08-28 07:05
And you don't have eny plugins right?

**Comment by nchanged** [comment] 2017-08-28 07:23
`fuse-box@2.2.3-beta.11` should be fixed here

**Closed** 2017-08-28 07:22 UTC
Labels: discussion

**Comment by zeniroy** [comment] 2017-08-28 07:45
oh that's works! thanks!
