### ISSUE TITLE
Electron failed to install correctly

### ISSUE THREAD

**Issue by sentialx** [fuse-box/fuse-box#1570] opened 2019-07-29 14:25 UTC
Hi, I'm trying to bundle all my dependencies (excluding native and electron) using `QuantumPlugin` with `target` set to `electron` and also with `-electron` instruction, but it seems to be bundling `electron` anyway and it keeps me throwing:
```
Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
```

I'm using fuse-box 3.7.1

Edit: It seems to be issue with bundling modules using `electron` as a dependency.

**Comment by nchanged** [comment] 2019-07-30 08:16
@sentialx you can add `ignoreModules : ["electron"]` with v3, but I would encourage you to try `v4`

**Comment by sentialx** [comment] 2019-07-30 10:03
@nchanged Now I get 
```
Error: No native build was found for platform=win32 arch=x64 runtime=electron abi=73 uv=1 libc=glibc
```

Are there `QuantumPlugin`, `CopyPlugin`, `EnvPlugin` in v4? Is there a way to create multiple entries in one fuse-box instance so that there is only one `devServer`?

**Comment by sentialx** [comment] 2019-07-30 10:30
With `v4` I get following errors:
```
PS C:\Users\Senti\Desktop\Projekty\wexond> npm run dev

> wexond@2.2.4 dev C:\Users\Senti\Desktop\Projekty\wexond
> cross-env NODE_ENV='dev' ts-node fuse.ts

    assemble package sax:1.2.4ParseError [SyntaxError]: [26:35]: Illegal async arrow function parameter list
    at report (C:\Users\Senti\Desktop\Projekty\wexond\node_modules\meriyah\dist\meriyah.umd.js:354:13)
    at parseAsyncExpression (C:\Users\Senti\Desktop\Projekty\wexond\node_modules\meriyah\dist\meriyah.umd.js:5089:19)
    at parsePrimaryExpressionExtended (C:\Users\Senti\Desktop\Projekty\wexond\node_modules\meriyah\dist\meriyah.umd.js:3485:22)
    at parseExpression (C:\Users\Senti\Desktop\Projekty\wexond\node_modules\meriyah\dist\meriyah.umd.js:3127:18)
    at parseVariableDeclaration (C:\Users\Senti\Desktop\Projekty\wexond\node_modules\meriyah\dist\meriyah.umd.js:2690:18)
    at parseVariableDeclarationList (C:\Users\Senti\Desktop\Projekty\wexond\node_modules\meriyah\dist\meriyah.umd.js:2674:21)
    at parseLexicalDeclaration (C:\Users\Senti\Desktop\Projekty\wexond\node_modules\meriyah\dist\meriyah.umd.js:2654:28)
    at parseStatementListItem (C:\Users\Senti\Desktop\Projekty\wexond\node_modules\meriyah\dist\meriyah.umd.js:2174:22)
    at parseFunctionBody (C:\Users\Senti\Desktop\Projekty\wexond\node_modules\meriyah\dist\meriyah.umd.js:3314:21)
    at parseArrowFunctionExpression (C:\Users\Senti\Desktop\Projekty\wexond\node_modules\meriyah\dist\meriyah.umd.js:4921:18) {
  index: 755,
  line: 26,
  column: 35,
  description: '[26:35]: Illegal async arrow function parameter list'
}
ParseError [SyntaxError]: [715:34]: Illegal async arrow function parameter list
    at report (C:\Users\Senti\Desktop\Projekty\wexond\node_modules\meriyah\dist\meriyah.umd.js:354:13)
    at parseAsyncExpression (C:\Users\Senti\Desktop\Projekty\wexond\node_modules\meriyah\dist\meriyah.umd.js:5089:19)
    at parsePrimaryExpressionExtended (C:\Users\Senti\Desktop\Projekty\wexond\node_modules\meriyah\dist\meriyah.umd.js:3485:22)
    at parseExpression (C:\Users\Senti\Desktop\Projekty\wexond\node_modules\meriyah\dist\meriyah.umd.js:3127:18)
    at parseVariableDeclaration (C:\Users\Senti\Desktop\Projekty\wexond\node_modules\meriyah\dist\meriyah.umd.js:2690:18)
    at parseVariableDeclarationList (C:\Users\Senti\Desktop\Projekty\wexond\node_modules\meriyah\dist\meriyah.umd.js:2674:21)
    at parseLexicalDeclaration (C:\Users\Senti\Desktop\Projekty\wexond\node_modules\meriyah\dist\meriyah.umd.js:2654:28)
    at parseStatementListItem (C:\Users\Senti\Desktop\Projekty\wexond\node_modules\meriyah\dist\meriyah.umd.js:2174:22)
    at parseFunctionBody (C:\Users\Senti\Desktop\Projekty\wexond\node_modules\meriyah\dist\meriyah.umd.js:3314:21)
    at parseMethodDefinition (C:\Users\Senti\Desktop\Projekty\wexond\node_modules\meriyah\dist\meriyah.umd.js:4127:20) {
  index: 20526,
  line: 715,
  column: 34,
  description: '[715:34]: Illegal async arrow function parameter list'
}
```

**Comment by nchanged** [comment] 2019-07-30 11:06
@sentialx that's a syntax error. Could you paste some code snippet?

**Comment by sentialx** [comment] 2019-07-30 11:07
@nchanged Code snippet of what?

**Comment by sentialx** [comment] 2019-07-30 11:11
Here's my fuse.ts config https://github.com/wexond/wexond/blob/fuse/fuse.ts

**Comment by nchanged** [comment] 2019-07-30 11:35
Could you give me the steps on how to reproduce the error?

**Comment by sentialx** [comment] 2019-07-30 11:37
If you didn't install windows-build-tools before, run this command as admin:
```
npm i -g windows-build-tools
```
```
git clone https://github.com/wexond/wexond
git checkout fuse
npm i
npm run dev
```

**Comment by nchanged** [comment] 2019-07-30 12:48
@sentialx thanks! I think there a bug in the AST parser. I will keep you posted!

**Comment by jeremy-coleman** [comment] 2019-07-31 19:44
I have had this issue a few times, try removing the web index plugin and just use require directly inside your entry html file

**Comment by nchanged** [comment] 2019-08-01 10:37
@sentialx 
Try this config with `4.0.0-alpha.66`

Note that autoStartEntry will launch the process, but I think I did something wrong as that should be executed in the browser too?  Anyway, put there you electron launcher.

Let me know if that helps, I would like to get it running to share as a complex setup for electron.

Here is a [something](https://github.com/fuse-box/fuse-box/blob/v4/docs/resource_links.md) that will help you to understand how your resources are copied. (automatically)
```
import { fusebox } from 'fuse-box';
import { spawn } from 'child_process';
import { IPublicConfig } from 'fuse-box/config/IPublicConfig';

const production = process.env.NODE_ENV === 'dev' ? false : true;

const getConfig = (target: string) => {
  return {
    homeDir: 'src/',
    devServer: false,
    target,
    output: 'build/$name.js',
    cache: { root: '.cache' },
    dependencies: { ignoreAllExternal: true },
    alias: {
      '~': '~/',
    },

    // logging: {
    //   level: 'verbose',
    // },
  } as IPublicConfig;
};

const getRendererConfig = (target: string) => {
  const cfg = Object.assign({}, getConfig(target), {
    sourceMaps: !production,
  });

  return cfg;
};

const main = () => {
  const cfg = getConfig('electron');

  cfg.entry = 'main/index.ts';
  cfg.autoStartEntry = true;

  const fuse = fusebox(cfg);

  if (!production) {
    fuse.runDev();
  } else {
    fuse.runProd();
  }
};

const renderer = () => {
  const cfg = getRendererConfig('electron');

  cfg.webIndex = {
    template: 'static/pages/app.html',
    target: `app.html`,
  };
  cfg.entry = ['renderer/views/app/index.tsx'];

  const fuse = fusebox(cfg);

  if (!production) {
    fuse.runDev();
  } else {
    fuse.runProd();
  }
};

renderer();
main();

```

**Comment by sentialx** [comment] 2019-08-01 11:52
@nchanged Now, the `main` process doesn't build and `npm run dev` gives me following error:
```
export class View extends BrowserView {
                          ^
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (C:\src\main\view.ts:8:27)
    at $import (C:\Users\Senti\Desktop\Projekty\wexond\build\03f463b4f_dev.js.js:427:11)
    at locals.require (C:\Users\Senti\Desktop\Projekty\wexond\build\03f463b4f_dev.js.js:410:18)
    at Object.<anonymous> (C:\src\main\view-manager.ts:3:1)
    at $import (C:\Users\Senti\Desktop\Projekty\wexond\build\03f463b4f_dev.js.js:427:11)
    at locals.require (C:\Users\Senti\Desktop\Projekty\wexond\build\03f463b4f_dev.js.js:410:18)
    at Object.<anonymous> (C:\src\main\windows\app.ts:5:1)
    at $import (C:\Users\Senti\Desktop\Projekty\wexond\build\03f463b4f_dev.js.js:427:11)
    at locals.require (C:\Users\Senti\Desktop\Projekty\wexond\build\03f463b4f_dev.js.js:410:18)
    at Object.<anonymous> (C:\src\main\windows\index.ts:1:1)
```

The `BrowserView` class is imported from `electron`.
```
import { BrowserView } from 'electron';
```

**Comment by nchanged** [comment] 2019-08-01 12:04
@sentialx that's because it's being executed on the server side. Which Is wrong (Read my comment above) 

`cfg.autoStartEntry = true;`

I guess you need to have one bundle right? Cuz Fusebox produces at least 4 by default.  Can you feed it something else by `main.js` 

I will try to make it work this week.

**Comment by sentialx** [comment] 2019-08-01 16:19
@nchanged These bundles have random file names, is there a way to turn that off? Also, I'm not really sure which bundle is for the main process:
![image](https://user-images.githubusercontent.com/11065386/62310035-ead6ac00-b488-11e9-9b24-aa8deab93110.png)

**Comment by sentialx** [comment] 2019-08-01 16:30
Also, it would be great to have a config like this:
```typescript
cfg.entry = {
  app: {
    webIndex: {...},
    path: '...',
  }
}
```

**Comment by nchanged** [comment] 2019-08-01 17:06
@sentialx I will give a manifest.json + an object, where you will get the entry. Hopefully this week.

**Comment by nchanged** [comment] 2019-08-06 08:18
@sentialx the new docs can be found [here](https://github.com/fuse-box/fuse-box/blob/v4/docs/electron.md)
and a working [example](https://github.com/fuse-box/fuse-box-electron-seed)

Let me know if that helps.

**Comment by nchanged** [comment] 2019-08-07 19:08
@sentialx please gimme an update. Issues are piling up.

**Comment by sentialx** [comment] 2019-08-07 20:19
@nchanged It still doesn't work

```
C:\Users\Senti\Desktop\Projekty\wexond\src\main\view.ts:8
export class View extends BrowserView {
                          ^
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (C:\Users\Senti\Desktop\Projekty\wexond\src\main\view.ts:8:27)
    at $import (C:\Users\Senti\Desktop\Projekty\wexond\build\03f463b4f_dev.js.js:427:11)
    at locals.require (C:\Users\Senti\Desktop\Projekty\wexond\build\03f463b4f_dev.js.js:410:18)
    at Object.<anonymous> (C:\Users\Senti\Desktop\Projekty\wexond\src\main\view-manager.ts:3:1)
    at $import (C:\Users\Senti\Desktop\Projekty\wexond\build\03f463b4f_dev.js.js:427:11)
    at locals.require (C:\Users\Senti\Desktop\Projekty\wexond\build\03f463b4f_dev.js.js:410:18)
    at Object.<anonymous> (C:\Users\Senti\Desktop\Projekty\wexond\src\main\windows\app.ts:5:1)
    at $import (C:\Users\Senti\Desktop\Projekty\wexond\build\03f463b4f_dev.js.js:427:11)
    at locals.require (C:\Users\Senti\Desktop\Projekty\wexond\build\03f463b4f_dev.js.js:410:18)
    at Object.<anonymous> (C:\Users\Senti\Desktop\Projekty\wexond\src\main\windows\index.ts:1:1)
```

My config:

```typescript
const getConfig = (target: string) => {
  return {
    homeDir: 'src/',
    devServer: false,
    target,
    output: 'build/$name.js',
    cache: { root: '.cache' },
    dependencies: { ignoreAllExternal: true },
    alias: {
      '~': '~/',
    },
    watch: true,

    // logging: {
    //   level: 'verbose',
    // },
  } as any;
};

const main = () => {
  const cfg = getConfig('server');

  cfg.entry = 'main/index.ts';

  const fuse = fusebox(cfg);

  if (!production) {
    fuse.runDev();
  } else {
    fuse.runProd();
  }
};
```

**Comment by nchanged** [comment] 2019-08-07 20:58
@sentialx you haven't read the documentation nor tried the example have you?  This is an incorrect setup.

**Comment by sentialx** [comment] 2019-08-07 21:17
@nchanged I have read the docs, but I didn't notice I had `server` target instead of `electron`. Now I get this (node-window-manager is a native module):

```
Error: Cannot find module '../../build/Debug/addon.node'
Require stack:
- C:\Users\Senti\Desktop\Projekty\wexond\node_modules\node-window-manager\dist\classes\window.js
- C:\Users\Senti\Desktop\Projekty\wexond\node_modules\node-window-manager\dist\index.js
- C:\Users\Senti\Desktop\Projekty\wexond\build\6b4091b_app.js.js
- C:\Users\Senti\Desktop\Projekty\wexond\node_modules\electron\dist\resources\default_app.asar\main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (C:\Users\Senti\Desktop\Projekty\wexond\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:41:16)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Users\Senti\Desktop\Projekty\wexond\node_modules\node-window-manager\dist\classes\window.js:8:13)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
```

Config:
```typescript
const getConfig = (target: string) => {
  return {
    homeDir: 'src/',
    target,
    output: 'build/$name.js',
    cache: { root: '.cache' },
    dependencies: { ignoreAllExternal: true },
    alias: {
      '~': '~/',
    },
  } as any;
};

const main = () => {
  const cfg = getConfig('electron');

  cfg.homeDir = 'src/main';
  cfg.entry = 'index.ts';
  cfg.useSingleBundle = true;

  const fuse = fusebox(cfg);

  fuse.runDev(handler => {
    handler.onComplete(output => {
      output.electron.handleMainProcess();
    });
  })
};
```

**Comment by nchanged** [comment] 2019-08-08 06:05
@sentialx please try the example. It looks like some dependency is missing. This error is caused by electron, not FuseBox

**Comment by kurdin** [comment] 2019-08-25 01:38
@nchanged with `4.0.0-alpha.80` electron wont start anymore, `output.electron` in `undefined` on `handler.onComplete` it works if I rollback to `4.0.0-alpha.78`

Also `hash : false` wont work in configuration, I need to output 3rd bundle script for injecting js into webview, I have to use `useSingleBundle: true` and static bundle name something like `dist/injectapp.js` but I could not do it without `hash : false`

**Comment by nchanged** [comment] 2019-08-25 04:59
I will take a look, I think I know what might be broken. Install tslib. if it won't work could u reproduce and open an issue ?

**Comment by kurdin** [comment] 2019-08-25 12:28
`npm i tslib` did not help but in `fuse-box-electron-seed` with `FuseBox 4.0.0-alpha.80` if I run `npm run dist` it works just fine, so look like `'productionModule' of undefined` error has to do with my code or configuration. 

I still see with `FuseBox 4.0.0-alpha.80` 
```
TypeError: Cannot read property 'handleMainProcess' of undefined
    at /... /examples/fuse-box-electron-seed/fuse.ts:23:23
```
do you want me to open an issue about that ?

**Comment by nchanged** [comment] 2019-08-25 19:22
I will investigate and get back to you soon :)

**Comment by kurdin** [comment] 2019-08-25 21:07
@nchanged I post it in here https://github.com/fuse-box/fuse-box/issues/1585#issuecomment-524629048 looks like related issues.

**Comment by nchanged** [comment] 2019-08-27 12:32
Closing this issue, since electron build has been verified and works as expected. Re-open elsewise

**Closed by nchanged** 2019-08-27 12:32 UTC
