### ISSUE TITLE
error in VUE common.prod.js

### ISSUE THREAD

**Issue by nchanged** [fuse-box/fuse-box#1503] opened 2019-02-21 13:22 UTC
`dist/vue.runtime.common.prod.js` is originally uglified. When parsed and printed back it has syntax errors. Either a bug in typescript on escodegen.

The error is reproduced here:

https://github.com/diwiny/fusebox-vue-371-error

**Comment by robertkruis** [comment] 2019-04-25 08:04
@nchanged This error is indeed caused by the typescript compiler. This can however be resolved by enabling _useJsNext_ for the Vue library. This will result in using the _module_ property defined in the package.json of Vue, which points to _dist/vue.runtime.esm.js_. This is the same as how you would create an alias for Vue in webpack.

Adding the following to the FuseBox instance allows Vue to be required and prevents the syntax errors.
```
FuseBox.init({
  ...
  useJsNext: ['vue']
  ...
});
```

**Closed** 2019-08-27 13:24 UTC
