### ISSUE TITLE
Source maps are not syncing with code on latest Chrome and Firefox on macOS

### ISSUE THREAD

**Issue by aboyer1013** [fuse-box/fuse-box#1005] opened 2018-01-05 22:07 UTC
The last couple days, my source maps suddenly stopped working correctly in Fusebox. Namely, the debugger was off by several lines from where my breakpoint was. This happened in Chrome and Firefox. In short, I had to turn off source maps in order to debug. I'm still wondering what the cause is. Probably a bug with Babel? Anyway, I tried splitting out my bundles into smaller sizes but that didn't change anything. Now, I ended up using the Typescript compiler useTypescriptCompiler: true. Starting things up is a lot faster and it fixed my source map issue. I wanted to give Typescript a shot anyway so this was the catalyst. Just posting my struggle here in case anyone had ideas. Below is my fuse.js config. To fix it, I just flipped the compiler flag and removed the BabelPlugin().

Below is a link to a repo with the issue distilled to its essense:
https://github.com/aboyer1013/fuse-box-sourcemap-issue

**Comment by geowarin** [comment] 2018-01-06 12:07
With fuse-box 3, source maps are broken for me too.
I only use typescript.

Fuse config:

<details>

```ts
import {
  CSSPlugin, CSSResourcePlugin, EnvPlugin, FuseBox, JSONPlugin, PostCSS, QuantumPlugin, Sparky,
  SVGPlugin
} from "fuse-box";

const paths = require('./paths');
const postCssPlugins = require('./postcssPlugins');

let isProduction = false;
let fuse;

Sparky.task("config", () => {

  const outputDir = isProduction ? paths.prodDist : paths.devDist;

  fuse = new FuseBox({
    homeDir: `${paths.jsRoot}`,
    output: `${outputDir}/$name.js`,
    target: "browser",
    plugins: [
      isProduction && EnvPlugin({NODE_ENV: "production"}),
      SVGPlugin(),
      JSONPlugin(),
      [
        PostCSS(postCssPlugins, {from: `${paths.root}/src/main/ts/styles/main.css`}),
        CSSResourcePlugin({inline: true}),
        CSSPlugin(isProduction ? {group: 'main.css', outFile: `${outputDir}/main.css`} : {})
      ],
      isProduction && QuantumPlugin({
        uglify: true,
        api: (core) => {
          core.solveComputed("default/core/RouterStore.js", {
            mapping: "pages/**",
            fn: (statement, core) => {
              return statement.setExpression(`self.currentComponentPath`)
            }
          });
        }
      })
    ] as any
  });


  const vendors = fuse.bundle("vendor")
    .cache(!isProduction)
    .instructions(" ~ core/client.ts ~ pages/**/*.tsx");

  const pages = fuse.bundle("pages")
    .cache(!isProduction)
    .sourceMaps(!isProduction)
    .instructions(" !> [core/client.ts] + [pages/**/*.tsx]");

  if (!isProduction) {
    // vendors.hmr().watch();
    pages.hmr().watch();
    fuse.dev();
  }
});

Sparky.task("set-prod", () => {
  isProduction = true;
});

Sparky.task("dist", ["set-prod", "config"], () => {
  return fuse.run();
});

Sparky.task("default", ["config"], () => {
  return fuse.run();
});
```

</details>

My console log should be in `myPage.jsx` :

<img width="918" alt="image" src="https://user-images.githubusercontent.com/1045636/34639536-fcc8e6b8-f2e1-11e7-851b-165c58285049.png">

The default.js package does not exist:

<img width="918" alt="image" src="https://user-images.githubusercontent.com/1045636/34639574-64fb67f6-f2e2-11e7-9b87-4346a03b19ad.png">


<img width="242" alt="image" src="https://user-images.githubusercontent.com/1045636/34639541-0d4c51a0-f2e2-11e7-9175-3236746f4c4b.png">

**Comment by nchanged** [comment] 2018-01-06 12:34
Can u reproduce it please? Sourcemaps were fixed before the release, cache cleared?

**Comment by nchanged** [comment] 2018-01-08 09:50
It might be related to the target. Try setting `browser@es6`

**Comment by jperezdavinchi** [comment] 2018-01-08 15:40
Same here, cache cleared.
I tried with target browser@es6 and browser@es5, in compilerOptions module commonjs and target es6 and the sourcemaps are empty

![image](https://user-images.githubusercontent.com/28526655/34678110-6bb34ef4-f492-11e7-92b7-ef6a72793932.png)
and the js.map doesn't have code references
![image](https://user-images.githubusercontent.com/28526655/34678165-9302a7b6-f492-11e7-8347-3157a17882d5.png)

this is the js.map from previous fuse-box version
![image](https://user-images.githubusercontent.com/28526655/34678203-ad7c67bc-f492-11e7-9093-ddfe42d90e94.png)

**Comment by nchanged** [comment] 2018-01-08 15:53
@jperezdavinchi version of fusebox? and your config please

**Comment by jperezdavinchi** [comment] 2018-01-09 08:51
fuse-box 3.0.2
fuse:
```typescript
fuse = FuseBox.init({
        homeDir: `src/`,
        output: `dist/$name.js`,
        target: "browser",
        cache:false,
        hash:isProduction,
        plugins: [
            JSONPlugin(),
            [
                SassPlugin(
                    {
                        outputStyle: 'expanded',
                        importer:true
                    }
                ),
                CSSPlugin()
            ],
            CSSPlugin(),
            WebIndexPlugin(
                {
                    title: '',
                    template: 'src/index.html',
                    path:"./"
                }
            ),
            ConsolidatePlugin({
                engine:"pug"
            }),
            EnvPlugin({ NODE_ENV: isProduction ? "production" : "dev"}),
            ReplacePlugin({ "process.env.NODE_ENV": JSON.stringify(isProduction ? "production" : "dev") }),
            isProduction && UglifyESPlugin()
        ],
    });
```
tsconfig:
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "sourceMap": true,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "typeRoots": [
            "../node_modules/@types"
        ],
        "importHelpers": true,
        "noEmitHelpers": true,
        "lib":[
            "es2015",
            "dom",
            "es5"
        ]
    },
    "exclude": [
        "node_modules",
        "jspm_packages"
    ]
}
```

**Comment by nchanged** [comment] 2018-01-09 09:56
@jperezdavinchi I can't seem to reproduce it. Do you think you can make a test repo?

**Comment by jperezdavinchi** [comment] 2018-01-09 10:58
@nchanged sorry, my bad, the project uses angular 5.x and it fails with es2015 or es6 target at runtime.
I tried to configure fuse-box alias to point @angular/xxx to @angular/xxx/esm2015 but I failed, so I returned to es5.
The error happens with es5
![image](https://user-images.githubusercontent.com/28526655/34717703-3bfe94d2-f534-11e7-9fa5-8e6d11259a1f.png)
```typescript
fuse = FuseBox.init({
        homeDir: `src/`,
        output: `dist/$name.js`,
        target: "browser",
        cache:false,
        hash:isProduction,
        plugins: [
            JSONPlugin(),
            [
                SassPlugin(
                    {
                        outputStyle: 'expanded',
                        importer:true
                    }
                ),
                CSSPlugin()
            ],
            CSSPlugin(),
            WebIndexPlugin(
                {
                    title: '',
                    template: 'src/index.html',
                    path:"./"
                }
            ),
            ConsolidatePlugin({
                engine:"pug"
            }),
            EnvPlugin({ NODE_ENV: isProduction ? "production" : "dev"}),
            ReplacePlugin({ "process.env.NODE_ENV": JSON.stringify(isProduction ? "production" : "dev") }),
            isProduction && UglifyESPlugin()
        ],
    });
```
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "sourceMap": true,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "typeRoots": [
            "../node_modules/@types"
        ],
        "importHelpers": true,
        "noEmitHelpers": true,
        "lib":[
            "es2015",
            "dom",
            "es5"
        ]
    },
    "exclude": [
        "node_modules",
        "jspm_packages"
    ]
}
```

**Comment by nchanged** [comment] 2018-01-09 11:12
How about `target@es6`

**Comment by jperezdavinchi** [comment] 2018-01-09 11:21
Angular fails because expects es5.
They provide an esm2015 folder but I can't configure the fuse-box to import @angular/xxx/esm2015 when @angular/xxx is imported.
```typescript
 vendor = fuse.bundle('vendor')
        .alias("@angular/core","@angular/core/esm2015/core")
```
![image](https://user-images.githubusercontent.com/28526655/34718623-aa11ec8c-f537-11e7-82a3-fe948cbbe937.png)

**Comment by nchanged** [comment] 2018-01-09 11:49
@jperezdavinchi the problem is that FuseBox re-generates a file if it doesn't match user's target. And that breaks the sourcemaps

**Comment by jperezdavinchi** [comment] 2018-01-09 12:09
But until 3.0 it works fine with the same config.
Typescript emits to es5, vendor is es5 and fusebox target is browser. Is there something wrong with the config?

**Comment by nchanged** [comment] 2018-01-09 12:10
@jperezdavinchi can you set `browse@es5` to your target? because the default one is es6

**Comment by nchanged** [comment] 2018-01-09 12:29
For example, https://github.com/fuse-box/angular2-example here sourceMaps work perfectly

**Comment by jperezdavinchi** [comment] 2018-01-09 12:35
I copied the tsconfig.json and changed the target to browser@es5 and happens the same. 
Maybe some dependency could be the problem?

**Comment by nchanged** [comment] 2018-01-09 12:43
I honestly don't know, I am migrating now one heavy project, I will get back to you once I verify

**Comment by jperezdavinchi** [comment] 2018-01-09 13:05
Thank you for your help. In the meantime, I installed 2.5.0-beta.1 again and it works well.

**Comment by nchanged** [comment] 2018-01-09 15:25
@jperezdavinchi btw, where is your `sourceMaps : true` in `FuseBox.init`  ?

**Comment by jperezdavinchi** [comment] 2018-01-09 15:40
I copied the settings in https://github.com/fuse-box/angular2-example/blob/master/src/tsconfig.json, the js.map file was generated also

**Comment by nchanged** [comment] 2018-01-09 16:58
Can you set it in FuseBox.init please and only there, clear caches and dist

**Comment by nchanged** [comment] 2018-01-09 22:18
yeah, and it works, i've checked on my heavy project, and the sourcemaps are OK there. Can you narrow it down? Is it all broken?

**Comment by jperezdavinchi** [comment] 2018-01-10 08:57
@nchanged it works, moving the sourcemaps to the init!. 
Also works putting the sourcemaps in all the bundles, but fails if other bundles doesn't have the sorucemaps specified
This fails:
````typescript
//separate vendor
    vendor = fuse.bundle('vendor')
        .shim({
            jquery: {
                source: "node_modules/jquery/dist/jquery.js",
                exports: "$"
            }
        })
        .instructions(' ~ main.ts');
    app = fuse.bundle('main')
        .sourceMaps(!isProduction)//sourcemaps only in app bundle
        .instructions(' !> [main.ts]');
```
This works:
```typescript
//separate vendor
    vendor = fuse.bundle('vendor')
        .shim({
            jquery: {
                source: "node_modules/jquery/dist/jquery.js",
                exports: "$"
            }
        })
        .sourceMaps(!isProduction)//sourcemaps in vendor bundle
        .instructions(' ~ main.ts');
    app = fuse.bundle('main')
        .sourceMaps(!isProduction)//sourcemaps in appbundle
        .instructions(' !> [main.ts]');
```

**Comment by nchanged** [comment] 2018-01-10 08:59
ok man, I see. Gotta update the doc ;-)

**Comment by nchanged** [comment] 2019-02-21 11:18
It has been fixed in `fuse-box@next`

**Closed by nchanged** 2019-02-21 11:18 UTC
Labels: discussion
