### ISSUE TITLE
Support browser directive of package.json

### ISSUE THREAD

**Issue by alloy** [fuse-box/fuse-box#258] opened 2017-02-21 10:12 UTC
This is a continuation of https://github.com/fuse-box/fuse-box/issues/111#issuecomment-281009761

Details about how it should be interpreted can be found here: https://github.com/defunctzombie/package-browser-field-spec

An example of a package that uses this pattern is the popular [asap](https://github.com/kriskowal/asap/blob/b8ea518818fdd88c0f8b6b8b6b3002a01c0962cc/package.json#L16-L21).

**Comment by nchanged** [comment] 2017-03-05 20:58
@alloy please try http://fuse-box.org/#alias
I hope it help you with your project.

**Comment by alloy** [comment] 2017-03-05 22:12
Alas, no the `alias` directive will not work as a replacement for the `browser` directive, because an alias affects code in _any_ dependency whereas the `browser` directive only affects files in the package that specifies it.

E.g. using an alias like the following breaks something completely unrelated in a different package:

```json
  alias: {
    "./raw": "./browser-raw",
  }
```

**Comment by nchanged** [comment] 2017-03-05 22:15
Right, so we are interested in this:

```
"browser": {
    "module-a": "./shims/module-a.js",
    "./server/only.js": "./shims/client-only.js"
}
```

**Comment by nchanged** [comment] 2017-03-05 22:18
There will be a preview version hopefully next week for you to test ;-)

**Comment by nchanged** [comment] 2017-03-06 08:41
https://github.com/fuse-box/fuse-box/issues/354

**Comment by geowarin** [comment] 2017-05-16 16:24
Piggybacking on this issue.
I'm using [reactstrap](https://github.com/reactstrap/reactstrap) which defines several fields in its [package.json](https://github.com/reactstrap/reactstrap/blob/master/package.json#L5-L7).

Those are: `main`, `jsnext:main` and `module`.
The main field refers to the minified package and this is causing some issues for me (warning that I might be using the minified version of react).

Shouldn't fuse-box try to use `module` as a preferred source and fallback to `main` when not available?

Can I use shims as a workaround?

**Comment by geowarin** [comment] 2017-05-16 16:25
More info [here](https://github.com/rollup/rollup/wiki/pkg.module)

**Comment by devmondo** [comment] 2017-05-16 19:25
@geowarin good idea! we are studying it, stay tuned and we are extremely sorry for the delay :)

**Comment by geowarin** [comment] 2017-05-16 21:36
@devmondo Usually, when you say that, it means the problem is about to be solved. :smile: 

Anyways, no worries, it's just a warning message for now. 
I'll try to see if shims solve my problem tomorrow.

Keep it up, guys. :+1:

**Comment by geowarin** [comment] 2017-05-16 21:42
Now that I think of it, I might deserve its own issue.
Preferring `module` to `main` when available should also improve uglify/rollup performance, don't you think?

**Comment by nchanged** [comment] 2017-05-16 21:51
@geowarin I think fuse already taking into consideration `jsnext:main` over here
https://github.com/fuse-box/fuse-box/blob/master/src/core/PathMaster.ts#L331

But it will be extended to `target("browser")` and handled accordingly

**Comment by nchanged** [comment] 2017-05-17 19:55
@alloy @geowarin let's verify `fuse-box@2.1.0-beta.3` and close it already...

Don't forget to set `target("browser")` [here](http://fuse-box.org/page/configuration#target)

**Closed** 2017-05-22 21:23 UTC
Labels: enhancement, Feature
