### ISSUE TITLE
styled-component issue

### ISSUE THREAD

**Issue by matt-erhart** [fuse-box/fuse-box#863] opened 2017-10-13 23:33 UTC
```js
import * as React from "react";
import { Flex as FlexBase } from "rebass";
import styled from "styled-components";
import {Details} from './Icons'

export const ButtonWithIconsContainer = styled(FlexBase)`
  cursor: pointer;
  border-top: 1px solid white;
  border-bottom: 1px solid white;
  
  &:hover {
    border-top: 1px solid lightblue;
    border-bottom: 1px solid lightblue;
  }
  
  ${Details} {
    visibility: hidden;
  }
  
  &:hover ${Details} {
    visibility: visible;    
  }
`;
```
The ```${Details} ``` component selector in styled-components doesn't work in fuse but does work in webpack.

**Comment by nchanged** [comment] 2017-10-14 08:16
@matt-erhart and what's in `./Icons`

**Comment by Shepless** [comment] 2017-10-16 19:37
@matt-erhart could this something to do with default exports?

**Comment by matt-erhart** [comment] 2017-10-16 20:27
Just exporting const
```ts
export const DetailsBase: React.StatelessComponent<any> = props => {
  return (
    <Tooltip 
      mouseLeaveDelay={0}
      placement="top"
      overlay={ <Text m={0} p={0}>hey</Text>  }
      arrowContent={<TooltipHtml m={0} p={0} className="rc-tooltip-arrow-inner"></TooltipHtml>}
    >
      <Icon size={20} icon={ic_info_outline} className={props.className} />
    </Tooltip>
  );
};
export const Details = styled(DetailsBase)``; // just to use Details as a selector
```

**Comment by nchanged** [comment] 2017-10-16 20:56
And what kind of error you got? Could you create a repository where the issue is reproduced?

**Comment by nchanged** [comment] 2019-08-27 13:14
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.

**Closed by nchanged** 2019-08-27 13:14 UTC
Labels: discussion
