### ISSUE TITLE
Watch and rebuild linked packages in yarn workspaces monorepo

### ISSUE THREAD

**Issue by andrewcourtice** [fuse-box/fuse-box#1429] opened 2018-11-05 05:16 UTC
Hey guys

Firstly I'd like to say fusebox is epic! It is a breath of fresh air coming from webpack and babel. Well done to all contributors for all of your hard work in making this such a great build tool with a well thought out api.

I just have a quick question in regards to using fusebox with yarn workspaces. Consider the following file structure:

```
-- applications
    -- main
        -- src
            -- index.ts
        -- fuse.js
        -- tsconfig.json
        -- package.json

-- packages
    -- components
        -- src
            -- accordion.vue
            -- dropdown.vue
            ...
            -- index.ts
        -- package.json
    -- styles
        -- src
            -- site.scss
```

Currently with my webpack setup if I modify a file in any of the linked packages (say **./packages/components/src/dropdown.vue**) that are referenced by the app, webpack will automatically trigger a rebuild and hmr the app. It's also worth noting that our `webpack.config.js` file is located at **./applications/main/webpack.config.js** not at the project root. The problem I am facing is that fusebox doesn't rebuild in the same scenario so I have to stop the process and rebuild the app each time a change is made in any of the packages.

I am aware of issue #1277 which suggests moving `fuse.js` to the root or manually aliasing the package paths however I would prefer to use this as a last resort. I have also tried setting the `modulesFolder` property in the fuse config to the path of the packages **../../packages** (relative to **./applications/main/src** as the `homeDir`) however this had no effect.

My fusebox config is as follows:

``` javascript
const {
    FuseBox,
    CSSPlugin,
    SassPlugin,
    VueComponentPlugin,
    WebIndexPlugin
} = require('fuse-box');

const fuse = FuseBox.init({
    homeDir: 'src',
    target: 'browser@es2015',
    output: 'dist/$name.js',
    useTypescriptCompiler: true,
    allowSyntheticDefaultImports: true,
    plugins: [
        CSSPlugin(),
        [
            SassPlugin(),
            CSSPlugin()
        ],
        VueComponentPlugin({
            style: [
                SassPlugin(),
                CSSPlugin()
            ]
        }),
        WebIndexPlugin()
    ],
});

fuse.dev();

fuse
    .bundle('app')
    .instructions(' > index.ts')
    .hmr()
    .watch();

fuse.run();
```

Is there any way to configure fusebox to behave similar to webpack in the given scenario and rebuild/hmr upon changing a file in a linked package?

**Comment by nchanged** [comment] 2018-11-05 08:08
@andrewcourtice Hi and thanks for such kind words!
modulesFolder is one of the oldest features and it requires some love. Due to the amount of requests for this workspace setup (You aren't even the first nor the second to ask for this feature), I will try to implement and squeeze it into 3.7 release. 

There is one thing that might be helpful in `fuse-box@next`. You can keep fuse.js in your homeDirectory and reference `homeDir` higher up in the hierarchy. Your `Dist` folder will be ignored and the watcher won't trigger re-load.

**Comment by andrewcourtice** [comment] 2018-11-05 23:42
@nchanged You sir, are a legend! I'm looking forward to the 3.7 release. In the meantime I'll give `fuse-box@next` a go. Thanks again for your help 👍

**Comment by nchanged** [comment] 2018-12-01 20:49
Closing this for now. I believe the `@next` version solves the problem

**Closed by nchanged** 2018-12-01 20:49 UTC

**Comment by nchanged** [comment] 2019-01-30 06:45
@bkniffler this infinite loop is solved in the `@next` version. Please upgrade

**Comment by bkniffler** [comment] 2019-01-30 12:09
im on 3.7.0-next.17 actually :(

**Comment by nchanged** [comment] 2019-01-30 12:15
@bkniffler since your fuse.js is somewhere deep down the homeDir, you need to ignore some of the directories like described [here](https://fuse-box.org/docs/development/watching#chokidar-options)

There is a failsafe in FuseBox, but it doesn't apply on folders that change after the build has been completed

**Comment by bkniffler** [comment] 2019-01-30 12:56
Ah, I didn't see there was even a `bundle.watch(pathCheck)` function. I'm using that now and my CPU is very thankful of it :) 

I'd like to say how awesome fuse-box is. I've had nothing but perfect results (except for this little one, that is now fixed), even with my super complicated yarn workspace setup, where my webpack config was super hacky. Even with electronjs main/renderer it works so nicely!

**Comment by bkniffler** [comment] 2019-01-30 12:58
Here is my watch function for the record:
```
    rendererBundle.watch(
      p =>
        p.indexOf('packages/ui-') !== -1 ||
        p.indexOf(resolve(__dirname, 'src')) === 0
    );
```

**Comment by nchanged** [comment] 2019-01-30 13:20
That only means that you have some other directories that are updated. For
example fuse.js file itself

**Comment by bkniffler** [comment] 2019-01-30 13:22
Ah, since you answered by email, you probably didn't see the previous message. The issue is solved, thanks :)

**Comment by nchanged** [comment] 2019-01-30 13:33
@bkniffler I am glad it all worked out well for you ;-)
