### ISSUE TITLE
HMR doesn't handle package version change

### ISSUE THREAD

**Issue by whitecolor** [fuse-box/fuse-box#573] opened 2017-05-25 15:59 UTC
Workflow:
1) Start HMR.
2) Load page.
3) Update package in `node_modules` (content and **package.json version have changed**)
4) Nothing happens (old code is in use)
5) Remove .fusebox (with cache) folder, trigger reload
6) Nothing happens (old code is in use)

So have to restart fusebox process - new code in use.

**Comment by nchanged** [comment] 2017-05-25 16:07
Yes that's expected behavior, fuse caches modules in memory that's why it's darn fast. you don't really update modules all the time do you? But we could have a workaround for that. Nothing is impossible :)

**Comment by whitecolor** [comment] 2017-05-25 16:46
Nothing is impossible, right, so why not: watch `package.json` for loaded modules, and if version changed then reassemble the bundle.

While development it is obviously usual situation when one update dependency version. And in my workflow, I use local dependencies often with [yalc](https://github.com/whitecolor/yalc) which may change even more often, but they support different package.json `verson` value for any updated version of package content.

**Comment by nchanged** [comment] 2017-05-25 17:06
You could do it with [Sparky](http://fuse-box.org/page/sparky) and re-trigger your bundle manually. Like that:
```
const app = fuse.bundle("app").instructions()
Sparky.watch("package.json").file("*" => app.exec())
```

**Comment by nchanged** [comment] 2017-05-25 17:09
Just to make it clear, HMR doesn't reload modules, it reloads only your local files, however, we should introduce an API that will force a page to get reloaded

**Comment by whitecolor** [comment] 2017-05-25 17:17
> Just to make it clear, HMR doesn't reload node_modules, it reloads only your local files,

What is the actual different between my "local files" and code in node_modules? It is all the code that application is composed of, and the code in `node_modules` may change, the same way as my local code does. Packages code usually excluded from watching because of speed, as they supposed to change rarely. But why not handle this case out of the box, esp when we have single file `package.json` in the package that tells that package supposedly change. It will not introduce any slowing down but will be a very convenient addition. I think this need to be considered.

**Comment by nchanged** [comment] 2017-05-25 18:26
Absolutely! We can plan it, 2.1.0, however, is quite full already, and we are working on finalising it. 
But I agree, developing submodules should be easier.

**Comment by Shepless** [comment] 2017-11-05 11:15
@nchanged something for v3 roadmap?

**Comment by nchanged** [comment] 2017-11-05 16:50
I think Sparky can do that quite easily no need in watching everything by default.

**Comment by patgoley** [comment] 2019-04-10 23:44
@nchanged For clarification, if I stop and restart the HMR server, FuseBox should pick up any changes to `node_modules`, correct?

I'm seeing an issue where even restarting the server, clearing `build` and `.fusebox` cache directories, a new npm version is not getting picked up. I have no idea where it's still finding the old code to bundle because it is nowhere in my project anymore. Even a production build picks up the old code.

Building with FuseBox 3.7.1 and using yarn 1.15.2 to install dependencies.

If it's not something obvious I'm missing, I'll make a new issue. Thanks!!

**Comment by nchanged** [comment] 2019-08-27 13:10
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.

**Closed by nchanged** 2019-08-27 13:10 UTC
Labels: enhancement
