### ISSUE TITLE
`index.jsx` isn't implicitly loaded when using `../..` (or above entry file, but still in homeDir) during runtime

### ISSUE THREAD

**Issue by dzek69** [fuse-box/fuse-box#1596] opened 2019-08-28 10:32 UTC
I have a library project and I'm using fuse-box as a dev server for real-life testing and developing my library. My homeDir is set to `src` and my code used for testing the lib is in `src/example`.

When from example I am importing my library code from `src` (directory being the ancestor of `example`, but still in homeDir) I cannot use `../..` as import path, because this doesn't uses `index.jsx` but just imports "empty" import: `{__esModule: true, default: {…}}`

Importing with `../../` doesn't change anything

Importing with `../../index.jsx` fixes the issue

When I try to import *.js file with "../.." it works fine.

Repo to try this out/reproduce:
https://github.com/dzek69/react-perfect

- in `src/example/app/Sub.jsx` replace `"../../index.jsx"` with `"../.."`
- try creating `index.js` inside `src` - it will be imported, so just .jsx extension is a problem
- try creating `index.jsx` in `src/example` and import it with `".."` from `Sub.jsx` - it works as well, I expect it's because i'm importing from above entry file (or it's the amount of `../` that causes the issue - i did not test it)

**Comment by nchanged** [comment] 2019-08-29 07:53
@dzek69 I am not able to reproduce it. Here is working [example](https://github.com/fuse-box/fuse-box/blob/master/playground/jsx_in_js/src/one/two/three/three.js) in the playground

```
ts-node -T playground/jsx_in_js/fuse.ts
```

Resolves `../../` and `../..` More over that part has a 100% test coverage. If you manage to reproduce this issue please re-open the ticket and provide a sample.

**Comment by nchanged** [comment] 2019-08-29 07:55
@dzek69 UPD:

tried your example with `4.0.0-next.92`  -> works flawlessly

**Comment by dzek69** [comment] 2019-08-29 09:41
Your playground example isn't accurate without some changes.
You should be able to reporoduce on my example with `next.92` too, but you need to do some tweaks as described (as I didn't want to push broken code there).

To help you out i prepared a ready-to-reproduce example:
https://github.com/dzek69/fuse-bug/tree/1596

Just run `node fuse`, then open the dev server page in browser and check the console.

**Comment by nchanged** [comment] 2019-08-29 09:48
@dzek69 so that's a runtime error then?

**Comment by dzek69** [comment] 2019-08-29 10:07
Yes, sorry I didn't mention that

**Comment by nchanged** [comment] 2019-08-29 13:24
@dzek69 `4.0.0-next.93` please try that. I am not closing this issue until you confirm

**Closed** 2019-08-29 14:07 UTC
Labels: 4.0.0, bug
