### ISSUE TITLE
v4 - aliases are not resolved

### ISSUE THREAD

**Issue by lgibson02** [fuse-box/fuse-box#1653] opened 2019-09-30 21:02 UTC
Hi, I've only recently started using fuse after switching from webpack. Webpack had something where you could alias certain paths.
```javascript
module.exports = {
  resolve: {
    alias: {
      example: path.resolve(__dirname, "../src/"),
    }
  }
};
```

I've found an equivalent on the documentation for Fusebox 3:
```javascript
FuseBox.init({
  alias: {
    faraway: "~/somewhere/far/away/",
  }
});
```

However in version 4 this doesn't seem to work properly for me. On compilation it complains that it "Cannot resolve '~' / Import statement:".

My fuse.js:
```javascript
const { fusebox } = require("fuse-box");

const fuse = fusebox({
    homeDir: "../src",
    entry: "Boot.js",
    target: "browser@es5",
    output: "../server/public/$name.js",
    modules: ["phaser"],
    alias: {
        demo: "~"
    }
});

fuse.runDev();
```

And I import with something like this:
```javascript
import * as Test from "demo/a/b/Test";
```

Changing "demo" from "~" to "../src" will not work either. The error message just changes to "Cannot resolve 'demo' / Import statement".

**Comment by nchanged** [comment] 2019-09-30 21:28
hi @lgibson02 
Please upgrade to v4



Here is a live [sandbox](https://codesandbox.io/s/github/fuse-box/sandbox/tree/master/monorepo) for you to help deal with the paths. v4 supports typescript paths as well as aliases. The example above will help you understand how to setup your project. [Here](https://github.com/fuse-box/fuse-box/tree/master/docs) is the new documentation.  Feel free to join [slack](http://slack.fuse-box.org) we will be happy to help!

https://github.com/fuse-box/sandbox/tree/master/monorepo

**Comment by lgibson02** [comment] 2019-10-01 12:33
Hello, I've had a look at the project. I'm using javascript so typescript paths are no use to me, right? Shouldn't what I did above work?

**Comment by nchanged** [comment] 2019-10-01 13:17
@lgibson02 should work regardless. tsconfig.json works for javascript too

**Comment by nchanged** [comment] 2019-10-16 08:27
closing this issue, re-open if still relevant

**Comment by lgibson02** [comment] 2019-10-29 17:44
Hi sorry for not responding, I got caught up with other things. I'm unclear to why I must make a whole new tsconfig.json file just to do this, surely it would be easier from a user's perspective to just let us use the alias property. It seems this is what was done in v3 and I don't see why you should break that functionality.

**Comment by lgibson02** [comment] 2019-10-31 09:56
@nchanged Also I don't think I'm allowed to reopen this issue. Not seeing an option to anyway.

**Comment by lgibson02** [comment] 2019-11-16 15:46
Setting the path in tsconfig.json has no effect. 
`Cannot resolve "demo" / Import statement: "demo/ImportTest" in Boot.js`

Here's what I have:
./fuse.js
```javascript
const { fusebox } = require("fuse-box");

fusebox({
    target: "browser",
    homeDir: "../src",
    entry: "Boot.js",
    tsConfig: "./tsconfig.json",
}).runDev();
```
./tsconfig.json
```javascript
{
    "compilerOptions": {
        "target": "es2018",
        "module": "commonjs",
        "lib": ["es2017", "dom"],
        "moduleResolution": "node",
        "importHelpers": true,
        "skipLibCheck": true,
        "baseUrl": "",
        "paths": {
            "demo": ["../src/"]
        }
    },
    "exclude": ["node_modules"]
}
```
../src/Boot.js
```javascript
import ImportTest from "demo/ImportTest"; // tried this first
import * as ImportTest from "demo/ImportTest"; // tried this second
import * as ImportTest from "demo/ImportTest.js"; // tried this third
```
On an off topic note, is it really crucial that you must make people use a tsconfig.json? It doesn't seem to be needed in v3 so it seems like a bit of a back step in terms of simplicity.

**Comment by nchanged** [comment] 2019-11-16 16:39
@lgibson02 clear the cache or set it to false when configuring it, it has been covered with tests and I guarantee it is working as expected. The new version which hasn't been merged yet will allow you to configure it from the main object, and tsconfig will be no longer required

**Comment by lgibson02** [comment] 2019-11-16 16:43
I've set the cache to false in fuse.js but it had no effect. How do I go about clearing cache?

**Comment by nchanged** [comment] 2019-11-16 19:29
@lgibson02 make sure that your homeDir is set at ./src level otherwise FuseBox won't be able to resolve it. Long story short set it to the root of the project

**Comment by lgibson02** [comment] 2019-11-16 22:05
homeDir is set correctly, if I change it to anything else I get error `FATAL: Your entry point was not found`. Using `../src` like before is suitable in my case because my file structure is....

:open_file_folder: builder
&nbsp;&nbsp;&nbsp;&nbsp;:page_facing_up: fuse.js
&nbsp;&nbsp;&nbsp;&nbsp;:page_facing_up: tsconfig.json
:open_file_folder: src
&nbsp;&nbsp;&nbsp;&nbsp;:page_facing_up: Boot.js

**Comment by nchanged** [comment] 2019-11-16 23:02
So your homeDir should be ../ and the entry point relative to that directory, you need to change both

**Comment by lgibson02** [comment] 2019-11-17 12:21
I'm not really understanding you. homeDir should be a directory relative to fuse.js right? So ../src would be correct in that case... As I said before, if I change homeDir to anything else other than ../src it has problems finding the entry point. I don't believe homeDir has any relevance to this issue.

**Comment by nchanged** [comment] 2019-11-17 13:16
Then tweak the entry point, I don't understand why it's so hard ) homeDir should be relative to the root in your case along with your entry point

**Comment by lgibson02** [comment] 2019-11-17 13:30
The entry point is not the problem. It is able to find Boot.js just fine. Otherwise how would it ever be able to display this error message? 
 `Cannot resolve "demo" / Import statement: "demo/ImportTest" in Boot.js`

**Comment by nchanged** [comment] 2019-11-17 16:39
@lgibson02 I am telling you once again. It can't reach it, because your homeDir is incorrect. 
https://github.com/fuse-box/sandbox/blob/3bac740adc3eed968a2aa101b652a63edc2fb6cc/monorepo/sample/main/fuse.ts#L6-L7

Here is almost the same scenario, and tsconfig paths work as expected.

**Comment by nchanged** [comment] 2019-11-17 16:40
@lgibson02 actully, your configuration is incorrect

Has to be like this:
```
"paths": {
            "demo/*": ["../src/*"]
        }
```

**Comment by nchanged** [comment] 2019-11-17 16:43
https://www.typescriptlang.org/docs/handbook/module-resolution.html


<img width="945" alt="Screenshot 2019-11-17 17 42 06" src="https://user-images.githubusercontent.com/1629088/69010614-b5839a80-0961-11ea-93ee-c40ae64a3c7b.png">

**Comment by lgibson02** [comment] 2019-11-17 17:46
I already tried doing it like that, no difference. I've zipped up what I've got here...
[test.zip](https://github.com/fuse-box/fuse-box/files/3855890/test.zip)

I just cd into builder do `npm install` and then `node fuse.js`.

**Comment by kwhitley** [comment] 2020-01-09 05:41
I can confirm aliases work in v4 via the above method.  Obviously this example is a bit contrived (accomplished removing a `./`in front of the path), but it failed until I correctly configured the path in `tsconfig.json` per @nchanged suggestion.

// tsconfig.json
![image](https://user-images.githubusercontent.com/865416/72040906-a4734d80-326f-11ea-8bd7-7c3779db9213.png)

// src structure
![image](https://user-images.githubusercontent.com/865416/72041009-f3b97e00-326f-11ea-8392-bd4f758e8003.png)

// src/client/index.tsx (using alias to components)
![image](https://user-images.githubusercontent.com/865416/72041023-00d66d00-3270-11ea-99ba-0ed8ad7fed55.png)

**Comment by nchanged** [comment] 2020-01-09 06:38
Brilliant , closing this now

**Closed by nchanged** 2020-01-09 06:38 UTC
