### ISSUE TITLE
Development only modules are not removed in production

### ISSUE THREAD

**Issue by unlight** [fuse-box/fuse-box#332] opened 2017-03-02 18:34 UTC
```
if (process.env.NODE_ENV === 'development') {
    require('some-debug-mode-only-module');
}
```
When running in prod mode `NODE_ENV = 'production'`
1. code of `some-debug-mode-only-module` still exists in the bundle
2. this condition `if (process.env.NODE_ENV === 'development') {` will not be removed by uglifyjs

**Comment by unlight** [comment] 2017-03-02 18:37
If i replaced condition by preprocess
```
// @if devMode
require('some-debug-mode-only-module');
// @endif
```
this require will be removed, but code will left in the bundle.

**Comment by xdave** [comment] 2017-03-02 20:45
Can confirm, happening to me too

**Comment by nchanged** [comment] 2017-03-02 21:05
The upcoming release will feature AST exposure in the plugin API. So we could cook a plugin that removes unnecessary code, including `isServer` checks.

**Comment by aretecode** [comment] 2017-03-21 16:05
@nchanged @xdave @unlight http://fuse-box.org/#replaceplugin works?

**Comment by unlight** [comment] 2017-03-21 17:27
@aretecode
Not for me.
Removing unused code from bundle is more complex task than just simple string replace.
I already described result [here](https://github.com/fuse-box/fuse-box/issues/332#issuecomment-283739976 )

> will be removed, but code will left in the bundle.

**Comment by unlight** [comment] 2017-03-27 09:30
Workaround (only for typescript)
```ts
    const plugins: any[] = [
        {
            onTypescriptTransform: (file: File) => {
                if (_.endsWith(file.info.absPath, 'main.ts')) {
                    file.contents = preprocess(file.contents, config, { type: 'ts' });
                }
            }
        },
...
```
where preprocess is [npm preprocess](http://ghub.io/preprocess)

**Comment by xdave** [comment] 2017-05-15 20:20
Using the ReplacePlugin is broken for me.

When I add:

```js
    plugins: [
        ReplacePlugin({
            'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || '')
        })
    ]
```
to my config, it throws an error when bundling:

`(node:20118) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): TypeError: Cannot read property 'replace' of undefined`

**Comment by geowarin** [comment] 2017-05-15 21:30
The [env plugin](http://fuse-box.org:3333/plugins/env-plugin) works for me `EnvPlugin({ NODE_ENV: "production" })`.

**Comment by devmondo** [comment] 2017-05-15 23:29
@xdave  is it still an issue ? @geowarin says it works for him

**Comment by xdave** [comment] 2017-05-17 03:59
Env plugin works fine.  It injects the variables into the environment through the global `process` object.  That's not the issue here.  The issue is, we want the if branches that check for it's value to be optimized.   ie. dead code removal when it checks if you're comparing `'production' === 'production'`.

**Comment by aretecode** [comment] 2017-05-17 10:01
@xdave I'm confident replace plugin & envplugin does work for this, I made a minimal example testing it

**Comment by devmondo** [comment] 2017-05-17 10:36
@xdave yes i remember @aretecode  discussing this and it even works with minification too, to achieve what you want

**Comment by xdave** [comment] 2017-05-17 17:44
I upgraded from an old 2.0 beta, removed the EnvPlugin, and changed the order of plugins so that ReplacePlugin appears last, and it seems to work.

**Comment by devmondo** [comment] 2017-05-17 17:45
@xdave, awesome, we shall close this now, feel free to open it otherwise :)

**Comment by xdave** [comment] 2017-05-20 07:23
I am feeling free to open this.  After my initial tests, I was satisfied because a simple piece of code like this was removed with ReplacePlugin & UglifyJSPlugin:

```js
if (process.env.NODE_ENV !== 'production') {
    onlyInDevelopment();
}
```

However, if I use `require()` anywhere in one of these blocks, the packages that I'm importing using `require` are _still_ included in the bundle.  For example:

```js
let devMiddleware = null;

if (process.env.NODE_ENV !== 'production') {
    devMiddleware = require('some-pkg');
}
```
`some-pkg` is _always_ included.

If I alias `require` to something else, it works in prod, but breaks in dev.  For example:

```js
let devMiddleware = null;

if (process.env.NODE_ENV !== 'production') {
    const r = require;
    devMiddleware = r('some-pkg');
}
```

`some-pkg` is _never_ included.

**Comment by xdave** [comment] 2017-05-20 07:29
OK, it works if I use `FuseBox.import()` instead of require.  While this is nice, it would be nicer if my code didn't depend on the build system API.

**Comment by xdave** [comment] 2017-05-20 07:33
I suppose I have to explicitly add the package(s) in dev to the bundle in the `instructions()`:

```js
    .instructions(`
        > index.tsx
        ${prod ? '' : '+some-pkg'}
    `);
```

**Comment by devmondo** [comment] 2017-05-20 10:05
@xdave, when you use `FuseBox.import` you are doing lazy loading, so your file won't be bundled unless you explicitly say soo like you did here
```
.instructions(`
        > index.tsx
        ${prod ? '' : '+some-pkg'}
    `);
```

another way to do it is using code splitting, did you check the example here? https://github.com/fuse-box/fuse-box-examples/blob/master/examples/code-splitting/fuse.js or react one https://github.com/fuse-box/fuse-box-examples/blob/master/examples/react-code-splitting/fuse.js

does that help ?

**Comment by aretecode** [comment] 2017-05-21 05:10
@xdave ah, now I see this as an issue indeed. The code is dead-dropped, but the require statements statements still parse and cause issues. Seems to be a fundamental part of the requiring and related to https://github.com/fuse-box/fuse-box/issues/545 since that also requires files that are not used in the bundle (though they _should_ be, opposite of this case, same core issue).

**Comment by nchanged** [comment] 2017-05-21 05:33
This will be solved in 2.1+

**Comment by devmondo** [comment] 2017-06-20 21:31
It is solved now with the latest version.

we will close this for now but let us know otherwise :)

**Comment by xdave** [comment] 2017-06-21 02:02
Is it?  Quantum hasn't removed stuff I `require` inside of a `process.env.NODE_ENV !== 'production` block.

**Comment by devmondo** [comment] 2017-06-21 02:21
@nchanged i thought we solved it?

**Comment by nchanged** [comment] 2017-06-21 05:52
@xdave Quantum replaces it with string "production" and uglify js actually removes it. IsServer is being replaced to true/false

**Comment by xdave** [comment] 2017-06-22 01:40
@nchanged  test repo:  https://github.com/xdave/fuse-box-production-trim

Essentially, after quantum + uglify, the modules are _still in the bundle_

**Comment by nchanged** [comment] 2017-06-22 12:23
@xdave I think it's related to the fact that Quantum replaces `process.env.NODE_ENV` to production. Always. We could find a workaround.

**Comment by nchanged** [comment] 2017-06-22 12:32
@xdave 
```
natives : {
        process : !prod
   }
```

try that one =)

**Comment by xdave** [comment] 2017-06-22 21:57
@nchanged tried that & with beta 17, still not removing the modules.  I've updated the test repo.

**Comment by nchanged** [comment] 2017-06-22 22:06
@xdave which modules are you expecting to be removed?

**Comment by xdave** [comment] 2017-06-22 22:15
It's clearly marked in the code in `src/store.js`
- `redux-logger`
- `redux-immutable-state-invariant`
- `redux-devtools-extension`

They're being required inside of

```ts
    if (process.env.NODE_ENV !== 'production') {
        // DEVELOPMENT

        // The following modules SHOULD be removed in production, as they are not used.
        const { createLogger } = require('redux-logger');
        const immutable = require('redux-immutable-state-invariant').default;
        const { composeWithDevTools } = require('redux-devtools-extension');

        middleware = [
            immutable(),
            ...middleware,
            createLogger({ level: 'info', collapsed: true })
        ];
        composeEnhancers = composeWithDevTools({});
    }
```

**Comment by nchanged** [comment] 2017-06-28 14:25
@xdave TreeShaking removes dead modules in  `fuse-box@2.2.0-beta.24`
http://fuse-box.org/page/quantum#treeshake

Don't forget to enable it. It's `false` by default, as it's a bleeding edge thingy.

**Comment by xdave** [comment] 2017-06-29 03:33
That's pretty good.  The bundle for my test project went down by 50%, and it still works.

**Comment by devmondo** [comment] 2017-06-29 04:10
Awesome :)
We will close this for now but let us know otherwise :)

**Closed by devmondo** 2017-06-29 04:10 UTC
Labels: bug, enhancement
