### ISSUE TITLE
Package not found process

### ISSUE THREAD

**Issue by jcmoore0** [fuse-box/fuse-box#585] opened 2017-06-01 22:50 UTC
Fuse team:
I am trying to use Fuse-Box on an Angular2 project for the browser.
When importing rxjs, fuse injects a require("process").
I am not sure how to solve this.

__scope___.file("util/Immediate.js", function(exports, require, module, __filename, __dirname){
/* fuse:injection: */ var process = require("process");

Best regards,
John

**Comment by nchanged** [comment] 2017-06-02 06:20
Is it happening on an HMR event? Tried clearing the cache?

**Comment by nchanged** [comment] 2017-07-25 11:53
Can we close this one?

**Comment by timothyallan** [comment] 2017-07-31 21:47
I get this too on a plain .tsx page... `app.js:22023 Uncaught Package not found process`

```
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import TestComponent from './TestComponent';

ReactDOM.render(<TestComponent />, document.getElementById('app'));
```


The wacky thing is as soon as I add a path command, the error goes away.
```
import * as path from 'path';
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import TestComponent from './TestComponent';

const test = path.join('a', 'b', 'c');

ReactDOM.render(<TestComponent />, document.getElementById('app'));

```
The error goes away. Haven't tested it with other libraries yet to see what magic is going on.

fuse-box v2.2.1 with HMR

**Comment by nchanged** [comment] 2017-08-04 19:55
Can you make a repo to reproduce the bug please?

**Comment by nchanged** [comment] 2017-08-26 19:18
Closing due to inactivity

**Closed by nchanged** 2017-08-26 19:18 UTC
Labels: discussion

**Comment by magnushiie** [comment] 2017-10-10 16:05
I had the same issue, nuking cache (.fusebox) resolved it. I guess the cache goes corrupt sometimes?

**Comment by nchanged** [comment] 2017-10-10 16:06
it happens very rarely, hard to trace

**Comment by rw251** [comment] 2018-10-05 08:56
I realise this is a closed issue and don't want it to be reopened - but just in case it is useful for you to know I just had this issue with v3.5.0 so it does still happen. As suggested by @magnushiie deleting the .fusebox directory fixed the issue.
