### ISSUE TITLE
Quantum target universal and nodejs

### ISSUE THREAD

**Issue by maximkott** [fuse-box/fuse-box#1123] opened 2018-02-22 09:31 UTC
Hi @nchanged 

While building a package with `QuantumPlugin` for target `universal`, I've noticed that the produced bundle cannot be properly consumed from nodejs - when I try to `require` a bundle, produced by Quantum, all I get is an empty object `console.dir(require('./bundle.js')) // yields an empty object like:
 {}`. I am not sure whether this is intended behaviour or not. I'm simply trying to build a `umd` like package that I can use in browser, through `window.NAME` as well as require it trough nodejs. 

I do use the `globals` fuse-box configuration option and I've tried all the possible targets: 
- target `server` work on nodejs 
- target `browser` works in browser 
- target `universal` is not `requirable` from nodejs

Is there a way I can build a platform agnostic bundle, like `umd`? 

(I've seen the other issues on fuse-box regarding umd, but they don't seem to answer my question)

Thanks!

**Comment by nchanged** [comment] 2018-02-22 10:38
Could you reproduce the problem in a repository?

**Comment by maximkott** [comment] 2018-02-22 11:17
Yep, will do

**Comment by eddyw** [comment] 2018-05-14 07:29
@nchanged the original question of the author of this topic:
> Is there a way I can build a platform agnostic bundle, like umd?

Without Quantum it's possible to run the previous code in browser and in NodeJS (as a CommonJS module with the exports and so on), however, with Quantum the code is executed in an isolated function expression, no exports.

My solution was hacky since I didn't want to spend much time on it, I set target to `universal@es5` in FuseBox config but `target: "npm"` in Quantum, then just mock `module.exports` in browser.

**Comment by nchanged** [comment] 2018-05-14 07:42
@eddyw 
`globals: { default: '*' },` should actually do it. Could you install `@next` version and try again? There might be an actual bug or lack of implementation for the `universal` target.  But all is fixable.

**Comment by eddyw** [comment] 2018-05-14 08:29
@nchanged I tried with `@next`, it didn't work. Same results.

**Comment by KonstantinSimeonov** [comment] 2019-03-27 13:43
@nchanged What's the status of this?

**Comment by nchanged** [comment] 2019-03-27 13:59
Have you tried with the latest version? I am in the middle of a big refactor now

**Comment by KonstantinSimeonov** [comment] 2019-03-27 14:02
Yes, latest and greatest. Would you like a minimal replicating sample?

**Comment by nchanged** [comment] 2019-03-27 17:01
Sure, I will make sure to give it a proper test with `v4`

**Comment by KonstantinSimeonov** [comment] 2019-03-28 09:06
@nchanged Here's a repo to reproduce the issue with: https://github.com/KonstantinSimeonov/wavy-carrot

## Setup:

Node version: replicated with both `10.15.1` and `8.12.0`.

```typescript
// index.ts
export const add = (x: number, y: number): number => x + y;
```
- Steps to reproduce the issue:
```sh
npm i
node fuse.js
node -p "require('./dist/es6.js')"
```

This outputs an empty javascript object, but should output an object with a single export, something like `{ add: (x, y) => x + y }`.

**Comment by KonstantinSimeonov** [comment] 2019-03-28 11:14
If you don't have the time to do it, I can look into it and possible open a PR

**Comment by nchanged** [comment] 2019-03-28 12:17
@KonstantinKai as I mentioned, `v4` will be a brand new product, with 7x-10x faster than `v4`. If you want to help push it faster, you are welcome ;-)

**Comment by nchanged** [comment] 2019-08-27 13:19
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.

**Closed by nchanged** 2019-08-27 13:19 UTC
