### ISSUE TITLE
React-Router: Unexpected token 'export'

### ISSUE THREAD

**Issue by tomitrescak** [fuse-box/fuse-box#1679] opened 2019-11-06 04:56 UTC
Hi, for some reason, fuse-box keeps bundling the 'esm' code from react router. This is what is bundled:

```js
FuseBox.pkg("react-router-dom", {}, function(___scope___){
___scope___.file("esm/react-router-dom.js", function(exports, require, module){
const __req1__ = require("react-router");
export {} from "react-router"; // <------ ERROR
```

This is my fuse config

```js
const { fusebox } = require('fuse-box');
const fuse = fusebox({
  target: 'browser',
  entry: 'src/index.tsx',
  devServer: true,
  webIndex: {
    template: 'src/index.html'
  }
});

fuse.runDev();
```
This is my tsconfig

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "commonjs",
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react",
    "baseUrl": "src",
    "plugins": [
      {
        "name": "typescript-styled-plugin",
        "lint": {
          "validProperties": ["label"]
        }
      }
    ]
  },
  "include": ["src"]
}
```

Any idea how can I make it work ?

**Comment by tomitrescak** [comment] 2019-11-06 05:17
Looks like a bundling bug:

When I removed this line: `export * from 'react-router';` in the react-router-dom.js file all bundled well

**Comment by tomitrescak** [comment] 2019-11-06 05:20
Easy to reproduce for you, just use 'react-router-dom' in a react app.

**Comment by nchanged** [comment] 2019-11-06 07:04
@tomitrescak hey, which version of FuseBox?

**Comment by tomitrescak** [comment] 2019-11-06 11:37
Using latest, fresh install.

**Comment by nchanged** [comment] 2019-11-06 20:16
There are the contents I am seeing in the latest version `5.1.2`

```ts
import { Router, __RouterContext, matchPath } from 'react-router';
export * from 'react-router';
import _inheritsLoose from '@babel/runtime/helpers/esm/inheritsLoose';
import React from 'react';
import { createBrowserHistory, createHashHistory, createLocation } from 'history';
import PropTypes from 'prop-types';
import warning from 'tiny-warning';
import _extends from '@babel/runtime/helpers/esm/extends';
import _objectWithoutPropertiesLoose from '@babel/runtime/helpers/esm/objectWithoutPropertiesLoose';
import invariant from 'tiny-invariant';
```

Which is transpiled correctly

**Comment by nchanged** [comment] 2019-11-06 21:33
Ok, so the issue is that meriyah has changed the AST:
https://github.com/meriyah/meriyah/commit/01db03c08816ffdb092ebd890130bfd189f5e3eb

He is the commit, I am investigating what went wrong here. @KFlash could you help out here and tell us why there is no more `ExportAllDeclaration`

**Comment by nchanged** [comment] 2019-11-06 21:41
@tomitrescak `fuse-box@4.0.0-next.150`

**Comment by tomitrescak** [comment] 2019-11-06 22:35
Thanks I’ll check it ASAP. I actually had the repro for you I was about to send. Am glad you guys are this fast ;)

**Comment by KFlash** [comment] 2019-11-07 02:09
@nchanged Someone with a fever commited to Meriyah. It's all fixed in latest version

**Closed** 2019-11-07 06:37 UTC
