### ISSUE TITLE
Not all referenced sourcemaps aren't available 

### ISSUE THREAD

**Issue by auchenberg** [fuse-box/fuse-box#673] opened 2017-07-16 23:23 UTC
We have a reported issue on `vscode-chrome-debug` that [Fuse-box's HMR doesn't work with our debugger](https://github.com/Microsoft/vscode-chrome-debug/issues/459), and a quick debugging  session shows that not all referenced sourcemaps generated by fuse-box exists.

**Steps to reproduce:**
1. Get https://github.com/andrew-w-ross/fuse-debug
2. Start via F5
3. Put a breakpoint here, https://github.com/andrew-w-ross/fuse-debug/blob/master/src/components/Adder.tsx#L19
4. Change the value being added and wait for HMR to kick in.

**Actual result**

The pushed delta-bundle for `"components/Adder.jsx"` contains a sourceMappingURL for `Adder.jsx` which points to `Adder.js.map`
```js
exports.Adder = Adder;
//# sourceMappingURL=Adder.js.map
});
```
Making a HTTP GET to `http://localhost:4444/Adder.js.map` returns `404`

**Expected result**
Making a HTTP GET to `http://localhost:4444/Adder.js.map` return `200` and contains the relevant sourcemap for  `Adder.jsx`

**Comment by andrew-w-ross** [comment] 2017-07-17 08:47
@auchenberg Hey thanks so much for going to all this trouble on what was supposed to be just a question.   
Ok so to clarify from the question before in this case if I modified fuse-box to update with 

```javascript
exports.Adder = Adder;
//# sourceMappingURL=app.js.map
});
```

Would `vscode-chrome-debug` follow the sourceMappingUrl and apply the new one?

**Comment by nchanged** [comment] 2017-07-17 10:03
@auchenberg http://fuse-box.org/page/configuration#hosting-source-files can you try this option with the latest beta

**Comment by andrew-w-ross** [comment] 2017-07-17 12:14
@nchanged Here is an updated example using the [beta](https://github.com/andrew-w-ross/fuse-debug/tree/beta)

This doesn't work at all after the update. Looks like the beginning slash in the map file sources property is breaking it.

If I change the `app.js.map` file from 
```json
"sources":["/src/index.tsx","/src/components/Main.tsx","/src/components/Adder.tsx"]
```
to 
```json
"sources":["src/index.tsx","src/components/Main.tsx","src/components/Adder.tsx"]
```
It starts to works again.

**Comment by nchanged** [comment] 2017-07-17 12:18
@andrew-w-ross oh right, the problem is that without `/` it will fail to server sources in browser.

**Comment by auchenberg** [comment] 2017-07-17 19:37
@andrew-w-ross Given fuse-box produces a correct and updated sourcemap in `app.js.map` then it will work. Our debugger will simply follow the referenced sourcemap and use that.

**Comment by nchanged** [comment] 2017-07-17 19:45
@auchenberg @andrew-w-ross 
```
FuseBox.init({
    sourceMaps: { sourceRoot : "src" }
})
```

Should fix it

**Comment by auchenberg** [comment] 2017-07-17 20:02
@andrew-w-ross That would fix the path-issue, but not that HMR is pushing references to non-existing sourcemaps, right?

**Comment by nchanged** [comment] 2017-07-17 20:13
@auchenberg yep, that one to be investigated.

**Comment by andrew-w-ross** [comment] 2017-07-17 20:43
@auchenberg Thanks for clarification on how the source maps update.

@nchanged  You're right the `{ sourceRoot : "src" }` fixes the forward slash being appended at the beginning of the sources in the map file. The HMR update still breaks the source maps with this update.
```javascript
//# sourceMappingURL=Adder.js.map
```
as there is no `Adder.js.map`.

I've updated my [example repo](https://github.com/andrew-w-ross/fuse-debug/tree/beta).

**Comment by auchenberg** [comment] 2017-08-14 22:10
Just pulled the `beta` branch and I'm still seeing the issue of 404'ed source map

```
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"33","url":"","startLine":0,"startColumn":0,"endLine":28,"endColumn":2,"executionContextId":1,"hash":"CA1491A0AC55A2341417A210E9A61D4A3FA4A126","executionContextAuxData":{"isDefault":true,"frameId":"15131.1"},"isLiveEdit":false,"sourceMapURL":"app.js.map","hasSourceURL":false,"isModule":false,"length":821,"stackTrace":{"callFrames":[{"functionName":"","scriptId":"30","url":"http://localhost:4444/app.js","lineNumber":22171,"columnNumber":4339}]}}}
SourceMaps.getMapForGeneratedPath: Finding SourceMap for VM33 by URI: app.js.map and webRoot: /Users/auchenberg/development/fuse-debug
SourceMaps.loadSourceMapContents: Reading local sourcemap file from app.js.map
SourceMaps.loadSourceMapContents: Could not read sourcemap file - ENOENT: no such file or directory, open 'app.js.map'
SourceMaps.loadSourceMapContents: Reading local sourcemap file from VM33.map
To client: {"seq":0,"type":"event","event":"script","body":{"reason":"new","script":{"id":2,"source":{"name":"VM33","path":"VM33","sourceReference":1002}}}}
To client: {"seq":0,"type":"event","event":"scriptLoaded","body":{"path":"<eval>/VM33"}}
```

**Comment by auchenberg** [comment] 2017-08-14 22:12
Same for the `fix-hmr-sourcemaps` branch

```
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"33","url":"","startLine":0,"startColumn":0,"endLine":28,"endColumn":2,"executionContextId":1,"hash":"CA1491A07E7D1FF81417A210E9A61D4A3FA4A126","executionContextAuxData":{"isDefault":true,"frameId":"15531.1"},"isLiveEdit":false,"sourceMapURL":"app.js.map","hasSourceURL":false,"isModule":false,"length":821,"stackTrace":{"callFrames":[{"functionName":"","scriptId":"30","url":"http://localhost:4444/app.js","lineNumber":22518,"columnNumber":26}]}}}
SourceMaps.getMapForGeneratedPath: Finding SourceMap for VM33 by URI: app.js.map and webRoot: /Users/auchenberg/development/fuse-debug
SourceMaps.loadSourceMapContents: Reading local sourcemap file from app.js.map
SourceMaps.loadSourceMapContents: Could not read sourcemap file - ENOENT: no such file or directory, open 'app.js.map'
```

**Comment by nchanged** [comment] 2017-08-15 04:52
HMR will break sourcemaps that's inevitable, why can't you host them?

**Comment by auchenberg** [comment] 2017-08-15 05:04
Host them? We rely on valid referenced source maps in order to map the open
files in the editor to the loaded files.

Webpacks HMR strategi works perfect with our debuggers.

**Comment by Shepless** [comment] 2017-11-05 11:09
@auchenberg Im doing some house keeping on older tasks - is this still an issue for you?

**Comment by auchenberg** [comment] 2017-11-05 17:28
@Shepless Fusebose's HMR still isn't working with VS Code.

**Comment by Shepless** [comment] 2017-11-05 17:35
Thanks for getting back to me. Im not too savvy with this - is this something we need to address in FuseBox, or is it something that needs to be updated in VSCode? Or both 😄 ?

**Comment by andrew-w-ross** [comment] 2017-11-06 08:09
@Shepless [here is a summary on the issue](https://github.com/fuse-box/fuse-box/issues/659#issuecomment-326499961) so far. 

And [here is how to recreate it](https://github.com/fuse-box/fuse-box/issues/659#issuecomment-326517162). Just give me a shout if you need more info/help.

**Comment by partnerinflight** [comment] 2018-02-16 21:21
Any update on this? Trying to debug Electron's renderer process in VSCode using a repo cloned from https://skellock.github.io/typescript-with-electron-react-kit/#/

So far no dice.

**Comment by nchanged** [comment] 2018-02-17 08:53
Hasn't this been resolved? 
https://fuse-box.org/page/debugging-with-vscode

**Comment by andrew-w-ross** [comment] 2018-02-18 06:48
@nchanged No, it works initially but it doesn't work on hmr. It's because be vscode [relies on  the url from the scriptParsed event.](https://chromedevtools.github.io/devtools-protocol/tot/Debugger/#event-scriptParsed) It's not set because fuse-box uses the function constructor on update so there is no url.

Two things need to change to get it to work 

1.  On hmr the sourcemap url has to point to the bundle sourcemap output, I think this is fixed
2. Hmr will have to drop using function constructor and instead use a script tag injection

**Comment by nchanged** [comment] 2018-02-18 08:39
@andrew-w-ross but does it mean that we need to send the actual source map of that file? Or will it be enough to send the same source map? 
We can send a script tag update, but it will still wrapped in `FuseBox.dynamic`

**Comment by andrew-w-ross** [comment] 2018-02-18 19:22
The updated sourcemap has to be written to disk before the script update goes through but that's it.

**Comment by nchanged** [comment] 2019-08-27 13:12
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.

**Closed by nchanged** 2019-08-27 13:12 UTC
Labels: discussion
