### ISSUE TITLE
Watch with glob not working?

### ISSUE THREAD

**Issue by jmathew** [fuse-box/fuse-box#881] opened 2017-10-19 02:27 UTC
# Overview
I'm trying to pass a glob to `watch` to a subdirectory in my home dir as described in the documentation. I make changes to the files in sub directory and it doesn't trigger a rebuild. 

## When it doesnt work
I've tried multiple globs that all failed:
```
.watch("src/**")
.watch("src/**/*")
```

## When it works
Without a glob it does work, however there is an infinite loop of rebuilding. I think thats because the generated output folder is in the same folder as described in another issue.

It also will work with a specific file name to watch such as 'index.html'.

Globs like `**` or `.` seem to work as well. 

# Versions
**OS**
macOS 10.12.6 (16G29)

**Fusebox Version**
2.3.4-beta.7 (but also tested with the latest stable)

# Research
I made a project to hopefully demonstrate the issue.

Here is a gist version: 
https://gist.github.com/jmathew/1d88228e1dba7e9625acc4a188e06977

And a drive link:
https://drive.google.com/file/d/0B1tPVng1LVFCT1RlVndGY2xJSVU/view?usp=sharing

**Comment by devmondo** [comment] 2017-10-19 10:28
@jmathew did you try `.watch("src**")` ?

**Comment by jmathew** [comment] 2017-10-21 16:41
Hey thanks! That seems to work. What's the difference between that and the version with the slash?

**Comment by nchanged** [comment] 2017-10-21 16:44
@jmathew I think we have a problem with windows paths, that's what you are running it on, right?

**Comment by jmathew** [comment] 2017-10-21 17:03
I'm running it on macOS.

**Comment by misantronic** [comment] 2017-11-18 00:17
I've got the same problem as described above. The watcher without any args runs in an infinite loop whenever changes appear. Unfortunately, the watcher doesn't work with any args whatsoever.
My config:

```
const {
    Sparky,
    FuseBox,
    WebIndexPlugin,
    CSSPlugin,
    SassPlugin,
    CSSResourcePlugin,
    HTMLPlugin,
    JSONPlugin,
    ImageBase64Plugin,
    RawPlugin,
    ReplacePlugin
} = require('fuse-box');
const cpx = require('cpx');

const DIST = './dist';
const BASE = './scripts/main';

Sparky.task('build', () => {
    const fuse = FuseBox.init({
        homeDir: '.',
        output: `${DIST}/$name.js`,
        target: 'browser',
        cache: true,
        sourceMaps: true,
        hash: false,
        plugins: [
            WebIndexPlugin({
                target: 'index.html',
                template: './scripts/template/index.ejs',
                path: '/'
            }),
            [SassPlugin({ sourceMap: false }), CSSPlugin()],
            [
                CSSResourcePlugin({
                    dist: `${DIST}/static`,
                    resolve: file => `/static/${file}`
                }),
                CSSPlugin()
            ],
            CSSPlugin(),
            JSONPlugin(),
            ImageBase64Plugin({ useDefault: true }),
            HTMLPlugin(),
            RawPlugin(['.woff']),
            ReplacePlugin({
                IS_DEV: process.env.NODE_ENV === 'dev',
                GITHASH: JSON.stringify(process.env.GITHASH || '')
            })
        ]
    });

    fuse
        .bundle('app')
        .instructions(`> ${BASE}/index.tsx`)
        .watch(`${BASE}**`);

    return fuse.run();
});

Sparky.task('copy-assets', () => {
    cpx.copySync(
        './node_modules/jquery/dist/jquery.min.js',
        './dist/scripts/vendor'
    );
    cpx.copySync(
        './scripts/main/vendor/kendo/*.js',
        './dist/scripts/vendor/kendo'
    );
    cpx.copySync(
        './scripts/main/vendor/kendo/cultures/*.js',
        './dist/scripts/vendor/kendo/cultures'
    );
    cpx.copySync(
        './assets/fonts/ml-icons/*.woff',
        './dist/assets/fonts/ml-icons'
    );
});

Sparky.task('default', ['copy-assets', 'build'], () => {});
```

**Comment by Adamfsk** [comment] 2018-07-13 15:22
@devmondo @nchanged I was looking into this a little bit earlier, and spotted some inconsistency between sparky and fuse-box which might be useful for solving these issues.

In SparkFlow.ts (Sparky.watch returns SparkFlow.watch), chokidar is used directly, so both full globs and all chokidar options can be used easily.
In Bundle.ts, a proprietary and woefully incomplete in comparison to chokidar String2Regexp method is used to parse the paths for watching. Chokidar is actually used later, but properties have to be passed in by adding a parameter to the fuse.run() method, e.g. fuse.run({ chokidar: { ignored: ["assets"] } });

To fix this inconsistency (and also the rebuilding bugs), a few changes need to be made;

1. In Bundle.ts, remove any pre-parsing of the watchRule property.
2. In Bundle.ts, add an additional optional parameter to the watch method, to also pass in the chokidar options, in an identical fashion to how it's done in SparkFlow.ts. Store this as a secondary public property, e.g. "watchOpts"
3. In BundleProducer.ts, there appears to be an issue as when fuse.run() is called, it is calling the watch method and _always_ creates a watcher for the entire home directory, regardless of if the user wants this or not. This is one of the causes of duplicate builds, and should probably be deleted, as it's both unnecessary and incorrect; fuse.run() is called when making production builds, so why is a watcher created when we do this?
4. In BundleProducer.ts, modify the bundles.forEach loop to create chokidar watchers using the original file globs and options the user passed in via the bundle parameters modified in changes 1/2.

I can provide a pull request later on if you approve of these changes.

**Comment by nchanged** [comment] 2018-07-13 16:06
I think it's a good change! I was thinking of going for FuseBox 4.0 and introduce some breaking changes 

So feel free to break things and make it rather consistent. If you do this please don't forget to update the documentation along with the list of breaking changes to share later

**Comment by Adamfsk** [comment] 2018-07-13 17:29
@nchanged I've made the changes locally, but it's uncovered another issue. I'll see what I can do over the next few days to fix this once and for all,

**Comment by gastonkirsman** [comment] 2018-10-11 14:59
Problem still exists. At least I can't watch multiple directories.
I'd love to be able to specify different watch directory from the homeDir.

This is my current fuse.js file

`const { FuseBox } = require("fuse-box");

const fuse = FuseBox.init({
    homeDir: __dirname,
    output: "dist/$name.js",
  });
  
   
  fuse
    .bundle("app")
    .watch("src**")
    .instructions('> ./src/Games/Game1/Game1/main.ts')
   
  fuse.run();`

Modifying a file inside current directory (__dirname) will make an infinite loop of bundles.
Modifying a file in an deeper directory will not trigger the watch

Node 8.12.0
fuse-box 3.5.0

**Comment by nchanged** [comment] 2018-10-11 17:02
@gastonkirsman this [feature](https://github.com/fuse-box/fuse-box/commit/0c91f2085657b543933aa209882713bd7ea492d7) in `@next` will help you ignoring dist directories

**Comment by gastonkirsman** [comment] 2018-10-15 08:59
And the watch itself did you manage to make it work if you modify a file in a deeper directory (deeper than homeDir)?

**Comment by gastonkirsman** [comment] 2018-10-19 09:20
As a temporary solution you might use [node watch](https://www.npmjs.com/package/node-watch)

**Comment by nchanged** [comment] 2019-08-27 13:15
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.

**Closed by nchanged** 2019-08-27 13:15 UTC
Labels: discussion
