### ISSUE TITLE
Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by mbilling** [fuse-box/fuse-box#444] opened 2017-03-29 23:56 UTC
Observed with fuse-box 1.3.129
.fusebox dir has been removed
(My code bundles fine with Webpack, and runs without errors)

Running my fuse bundle code below produces 2 bundles which are loaded into a browser like.
```
<script src="/dist/modules.js" type="text/javascript"></script>
<script src="/dist/bundle.js" type="text/javascript"></script>
```

Fuse bundler code:
```
const FuseBox = require("fuse-box");

let fuse = FuseBox.FuseBox.init({
   homeDir: "./src",
   outFile: "../public/dist/bundle.js",
   plugins: [
      FuseBox.JSONPlugin(),
      FuseBox.TypeScriptHelpers(),
      [
         FuseBox.LESSPlugin(),
         FuseBox.CSSPlugin()
      ]
   ],
   sourcemaps : true
})

const DEPS = `
   +react
   +react-dom
   +parse
   +react-bootstrap
   +js-cookie
   +moment
   +react-waypoint
   +query-string
   +lz-string
   +request
   +credit-card-type
   +downloadjs
   +https
   +jquery-color
   +location
   +lodash
   +merge
   +navigator
   +node-gyp
   +react-clipboard
   +react-copy-to-clipboard
   +react-select
   +stripe
   +universal-analytics
   +url-search-params
   +xtend
` // Why doesn't fuse-box scan the dependencies of package.json for this info (optionally)?

fuse.bundle(
   {
         "../public/dist/bundle.js": ">index.tsx",
         "../public/dist/modules.js": DEPS
   });
```

While singlestepping it fails on the statement

`import request = require('request');`

with
```
Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at Function.create (<anonymous>)
    at Object.inherits (util@0.0.0:584)
    at Number.<anonymous> (stringstream@0.0.5:24)
    at c (xtend@4.0.1:26)
    at w.require (xtend@4.0.1:26)
    at Number.<anonymous> (request@2.81.0:290)
    at c (xtend@4.0.1:26)
    at w.require (xtend@4.0.1:26)
    at Number.<anonymous> (request@2.81.0:147)
    at c (xtend@4.0.1:26)
inherits @ util@0.0.0:584
(anonymous) @ stringstream@0.0.5:24
c @ xtend@4.0.1:26
w.require @ xtend@4.0.1:26
(anonymous) @ request@2.81.0:290
c @ xtend@4.0.1:26
w.require @ xtend@4.0.1:26
(anonymous) @ request@2.81.0:147
c @ xtend@4.0.1:26
w.require @ xtend@4.0.1:26
(anonymous) @ GoogleAnalytics.Management.ts:4
c @ xtend@4.0.1:26
w.require @ xtend@4.0.1:26
(anonymous) @ User.tsx:5
c @ xtend@4.0.1:26
w.require @ xtend@4.0.1:26
(anonymous) @ Overview.tsx:7
c @ xtend@4.0.1:26
w.require @ xtend@4.0.1:26
(anonymous) @ App.tsx:4
c @ xtend@4.0.1:26
w.require @ xtend@4.0.1:26
(anonymous) @ index.tsx:7
c @ xtend@4.0.1:26
r.import @ xtend@4.0.1:26
(anonymous) @ License.ts:69
(anonymous) @ License.ts:69

```

**Comment by nchanged** [comment] 2017-03-30 08:13
Hi @mbilling 
Sure, you can extract your dependencies automatically. Please check this repo -> that's a bleeding edge version https://github.com/fuse-box/preview-1.4.1/tree/master/examples/react-code-splitting

Regarding `request` I will check it soon

**Comment by mbilling** [comment] 2017-03-30 11:00
I tried the bleeding edge stuff and modified the example you suggested to my needs.
Wow! (apart from it not working for me yet :), it will be fantastic, and save me tons of time.
I love the html output template stuff, too.
Good job.

1. hmr loading part
The 2 hmr() calls are getting in the way of each other.
```
    const deps = fuse.bundle("deps").instructions(`~ **/**.{ts,tsx} +tslib`)
    if (!production) { deps.hmr(); }

    const app = fuse.bundle("app").instructions(`> [index.tsx] +react`)
    if (!production) { app.hmr().watch() }

```
Both takes port 4444, so I get following error message
`Uncaught Package not found fusebox-hot-reload`


2. Still not auto resolving and bundling dependencies. Am I doing it wrong, misunderstanding something?
I do not get my dependencies into either of the bundles.
`Uncaught Package not found react`



Here is my modified version.

```
const { Sparky, FuseBox, UglifyJSPlugin, TypeScriptHelpers, CSSPlugin, EnvPlugin } = require("fuse-box");

let producer;
let production = false;


let outPath = '../public/dist';

Sparky.task("build", ["prepare"], () => {
    const fuse = FuseBox.init({
        homeDir: "src",
        output: outPath + "/$name.js",
        hash: production,
        cache: !production,
        plugins: [
            EnvPlugin({ NODE_ENV: production ? "production" : "development" }),
            CSSPlugin(), production && UglifyJSPlugin()
        ]
    });

    !production && fuse.dev();

    // extract dependencies automatically
    const deps = fuse.bundle("deps").instructions(`~ **/**.{ts,tsx} +tslib`)
    if (!production) { deps.hmr(); }

    const app = fuse.bundle("app").instructions(`> [index.tsx] +react`)
    if (!production) { app.hmr().watch() }

    return fuse.run().then((fuseProducer) => {
        producer = fuseProducer;
    });
});

// main task
Sparky.task("default", ["clean", "build", "make-html"], () => {});

// wipe it all
Sparky.task("clean", () => Sparky.src(outPath + "/dist/*").clean(outPath + "/dist/"));

// copy and replace HTML
Sparky.task("make-html", () => {
    return Sparky.src("src/index.htm")
        .file("*", file => {
            let fname;
            const deps = producer.bundles.get("deps");
            const app = producer.bundles.get("app");
            // get generated bundle names
            file.template({
                deps: deps.context.output.lastGeneratedFileName,
                app: app.context.output.lastGeneratedFileName,
            });
        })
        .dest(outPath + "/../$name")
});

Sparky.task("set-production-env", () => production = true);
Sparky.task("dist", ["clean", "set-production-env", "build", "make-html"], () => {})
```

**Comment by nchanged** [comment] 2017-03-30 11:08
Ok,
It seem that HMR related code isn't bundled. Did you check the example? is it working for you?

* That symbol `~` grabs all dependencies. Make sure you have correct arithmetics.
* Move that `+react` to vendor.
*  Change your vendor (deps) to `.instructions(`~ index.tsx`)
* Import tslib in your index.tsx `import("tslib")`
* Clear the cache

Let me know if that helps. And check the example on github.

**Comment by nchanged** [comment] 2017-03-30 11:23
P.S make sure of your files order `deps.js` and then `app.js`

**Comment by mbilling** [comment] 2017-03-30 14:05
I striped down my code only to load a react component with react, react-dom, react-bootstrap. This worked fine. HMR worked, splitting, html template and the works.
A soon is I added more components it broke the build phase, HMR died etc.
When I have time for it I will break it further down to see exactly what component breaks what.
I use v 1.4.1beta18 and I don't get en error on request. Maybe its random or you have changed something
I'll get back

**Comment by nchanged** [comment] 2017-03-30 14:28
Cool, if you add an external dep you need to restart your vendor, or watch it, but I find it faster restarting.
If you add a new file, HMR should reload the page

**Comment by aretecode** [comment] 2017-03-31 12:15
that is why there is this rule http://eslint.org/docs/rules/no-prototype-builtins

**Comment by nchanged** [comment] 2017-04-30 16:29
@mbilling please check if you have any issues with `fuse-box@2.0.0-beta.8`
Documentation is here: http://fuse-box.org:3333/

We are finalising the release, I am closing the issue for now, please feel free to re-open elsewise

**Closed by nchanged** 2017-04-30 16:29 UTC
Labels: discussion

**Comment by rosensama** [comment] 2017-06-19 18:10
FWIW, when I find that neither of my bundles has my vendor dependencies causing console errors like `Uncaught Package not found react`, it's because the BabePluginClass capture failed.   There was no strong error message for this.   In the most recent instance, a module was loading the mime module which in turn was including a JSON file.  I need to add the JSON plugin to my config.   It would complete the vendor capture with nothing found, I assume because it crapped out even though the message reads more like a warning than a fatal.  

Example error:

```
10:20:26: BabelPluginClass : Captured mime.js
{ message: 'File contents for /home/rosensama/src/the_project/node_modules/mime/types.json were not loaded. Missing a plugin?' }
└──  (0 files,  53 Bytes) default
Size: 53 Bytes in 3s 218ms
```

I'm now troubleshooting a similar error to this issue with fuse-box@2.1.0.   Again it's referencing in util@0.0.0:584.  I'm guessing I just don't grok the error yet.   But if @mbilling has any advice, i'd appreciate it.  

```
Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at Function.create (<anonymous>)
    at Object.inherits (util@0.0.0:584)
    at Number.<anonymous> (superagent@3.5.2:1113)
    at c (moment@2.18.1:4470)
    at w.require (moment@2.18.1:4470)
    at Number.<anonymous> (superagent@3.5.2:12)
    at c (moment@2.18.1:4470)
    at w.require (moment@2.18.1:4470)
    at Number.<anonymous> (auth0-js@8.7.0:497)
    at c (moment@2.18.1:4470)
    at w.require (moment@2.18.1:4470)
    at Number.<anonymous> (auth0-js@8.7.0:21)
    at c (moment@2.18.1:4470)
    at w.require (moment@2.18.1:4470)
    at Number.<anonymous> (auth0-js@8.7.0:4)
    at c (moment@2.18.1:4470)
    at w.require (moment@2.18.1:4470)
    at Number.<anonymous> (auth0-lock@10.17.0:1566)
    at c (moment@2.18.1:4470)
    at w.require (moment@2.18.1:4470)
    at Number.<anonymous> (auth0-lock@10.17.0:931)
    at c (moment@2.18.1:4470)
    at w.require (moment@2.18.1:4470)
    at Number.<anonymous> (auth0-lock@10.17.0:147)
    at c (moment@2.18.1:4470)
    at w.require (moment@2.18.1:4470)
    at Number.<anonymous> (auth0-lock@10.17.0:8)
    at c (moment@2.18.1:4470)
    at w.require (moment@2.18.1:4470)
    at Number.<anonymous> (AuthService.js:3)
    at c (moment@2.18.1:4470)
    at w.require (moment@2.18.1:4470)
    at Number.<anonymous> (Page.jsx:2)
    at c (moment@2.18.1:4470)
    at w.require (moment@2.18.1:4470)
    at Number.<anonymous> (index.jsx:7)
    at c (moment@2.18.1:4470)
    at Function.r.import (moment@2.18.1:4470)
    at NotFound.jsx:3
    at NotFound.jsx:3
inherits @ util@0.0.0:584
(anonymous) @ superagent@3.5.2:1113
c @ moment@2.18.1:4470
w.require @ moment@2.18.1:4470
(anonymous) @ superagent@3.5.2:12
c @ moment@2.18.1:4470
w.require @ moment@2.18.1:4470
(anonymous) @ auth0-js@8.7.0:497
c @ moment@2.18.1:4470
w.require @ moment@2.18.1:4470
(anonymous) @ auth0-js@8.7.0:21
c @ moment@2.18.1:4470
w.require @ moment@2.18.1:4470
(anonymous) @ auth0-js@8.7.0:4
c @ moment@2.18.1:4470
w.require @ moment@2.18.1:4470
(anonymous) @ auth0-lock@10.17.0:1566
c @ moment@2.18.1:4470
w.require @ moment@2.18.1:4470
(anonymous) @ auth0-lock@10.17.0:931
c @ moment@2.18.1:4470
w.require @ moment@2.18.1:4470
(anonymous) @ auth0-lock@10.17.0:147
c @ moment@2.18.1:4470
w.require @ moment@2.18.1:4470
(anonymous) @ auth0-lock@10.17.0:8
c @ moment@2.18.1:4470
w.require @ moment@2.18.1:4470
(anonymous) @ AuthService.js:3
c @ moment@2.18.1:4470
w.require @ moment@2.18.1:4470
(anonymous) @ Page.jsx:2
c @ moment@2.18.1:4470
w.require @ moment@2.18.1:4470
(anonymous) @ index.jsx:7
c @ moment@2.18.1:4470
r.import @ moment@2.18.1:4470
(anonymous) @ NotFound.jsx:3
(anonymous) @ NotFound.jsx:3
```

**Comment by nchanged** [comment] 2017-06-19 18:26
@rosensama please add JSONPlugin and use `2.2.0-beta.12`

**Comment by rosensama** [comment] 2017-06-19 19:06
@nchanged since I added JSONPlugin, my vendor bundle is improved and contains many packages.   I get the same `TypeError` regarding prototype with `2.2.0-beta.12` as I did with `2.1.0`.   Debug logging doesn't reveal any interesting messages.

**Comment by nchanged** [comment] 2017-06-19 19:19
Could you reproduce it in a separate repository please?

**Comment by rosensama** [comment] 2017-06-19 20:11
@nchanged I'll try.

**Comment by nchanged** [comment] 2017-06-19 20:23
@rosensama and in a new issue, please. Much appreciated.
