### ISSUE TITLE
Typescript's esModuleInterop not supported in fuse-box 3.1.3 

### ISSUE THREAD

**Issue by kevlugli** [fuse-box/fuse-box#1167] opened 2018-03-20 21:44 UTC
Hi,
I'm facing an issue in  the current version (3.1.3), that doesn't happen on version 2.4.0. 
I'm using semantic-ui-react. I couldn't get it working with commonjs, so ended enabling jsNext. That version uses some defaults imports in lodash so I also had to enable polyfillNonStandardDefaultUsage in my config. Also I have esModuleInterop enabled my tsconfig.json.
I updated fuse-box to the last version and it stopped working. After debugging it a little, it seems to me that the problem happens when using a mixed import like `import React, {Component} from 'react'`, the function __importDefault that TS adds to the compilation in combination with fuse makes that what gets imported is just an object like `{default: React}`, so Component import is lost.
For now I'm staying with 2.4.0 but I'd like to use the last version.
Thanks

**Comment by nchanged** [comment] 2018-03-21 08:41
Hi, I don't think you can mix `esModuleInterop` and `polyfillNonStandardDefaultUsage` together just choose one.

**Comment by kevlugli** [comment] 2018-03-22 03:53
That's the only way it works. But only with 2.4.0. When I update to 3.1.3 it brokes. No matter if I use `allowSyntheticDefaultImports`, `polyfillNonStandardDefaultUsage` or the two of them. I tried disabling `esModuleInterop`  and enabling `allowSyntheticDefaultImports` in tsconfig.ts but it produces the same error. 
Maybe it's related to a change hapenning in TS 2.7.0, but I need to use it. 
Anyways it works with fuse-box 2.4.0 but no with 3.1.3, so I think it has to be with the change introduced with the option `allowSyntheticDefaultImports` in fuse.

**Comment by nchanged** [comment] 2018-03-22 09:06
@kevlugli if you modified `tsconfig.json` only, you would need to clear the cache.
Could you reproduce the issue in a repository if nothing works?

**Comment by kevlugli** [comment] 2018-03-22 22:22
@nchanged I tried changing `esModuleInterop` with `allowSyntheticDefaultImports` in `tsconfig.json` , and after clearing the cache it works with latest fuse-box version.  Thanks!
 Anyway, with fuse-box 2.4.0 I could use `esModuleInterop` and it worked, so I suppose that's an issue.
I created a [repo](https://github.com/kevlugli/fuse-box-test) . In master you have a non working setup with fuse-box 3.1.3 and  `esModuleInterop` in `tsconfig.json`. In branch working-2.4.0 there is a working setup with fuse-box 2.4.0 and  `esModuleInterop` in `tsconfig.json`. At last you have branch  working-3.1.3, a working setup with fuse-box 3.1.3 with  `esModuleInterop` disabled and `allowSyntheticDefaultImports` enabled.

**Comment by kevlugli** [comment] 2018-03-22 22:24
Changed the title to reflect accordingly.

**Comment by nchanged** [comment] 2018-03-23 08:02
So, `allowSyntheticDefaultImports` should be omitted when used with `esModuleInterop` ?

**Comment by kevlugli** [comment] 2018-03-23 19:46
Mm no. The problem is that fuse-box 3.1.3 generates wrong build when `esModuleInterop` is enabled in `tsconfig.json`, no matter which options you use on fuse. And that didn't happen with fuse-box 2.4.0.

**Comment by kevlugli** [comment] 2018-03-23 22:04
It's here.. https://github.com/kevlugli/fuse-box-test . In a previous comment I described the branchs. Master has the issue

**Comment by nchanged** [comment] 2018-04-14 17:34
Hi @kevlugli 
Sorry it took so long,  I checked the issue, and it turns out that it's not fuse's fault
line `16782`

```
var react_1 = __importDefault($fsx.r(493));
```
Imported with `importDefault` (typescript), However, on line `16795` it is used without `default` and returns `undefined`

```
    return Icon;
}(react_1.Component); // undefined
```
Which isn't handled either by `semantic ui` or typescript doesn't intercept it properly. FuseBox's `allowSyntheticDefaultImports` works as expected.

**Comment by nchanged** [comment] 2019-08-27 13:20
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.

**Closed by nchanged** 2019-08-27 13:20 UTC
Labels: discussion
