### ISSUE TITLE
Add bundle name to File object to identify the group. (CSS)

### ISSUE THREAD

**Issue by johnpittman** [fuse-box/fuse-box#1308] opened 2018-07-01 04:05 UTC
I have been looking at the CSSPlugin as well of your core source on how I can identify which .js bundle a .css import was in so I can generate CSS bundles by bundle/chunk name so lazy loading can happen easy by referencing same name for both .css and .js files. I know that this would require grouping them either after the bundles are created or optimally create the collection during bundle creation to skip redundant file parsing.

I import a .css file per a component in my app structure:

Ex.
```javascript
import * as React from 'react';

import './style.css';

export default class SomeComponent extends React.Component { ...
```

So building apps this way easily allows for .css grouping.

Having this information available is very important to get to loading optimal resource when code splitting as well as file caching. When code splitting, the CSS chunk should be grouped in the same manner as your JavaScript chunks are currently grouped. Currently, when code splitting, the main .js chunk are added to the bundles collection while leaving out the chunk files to be lazily loaded. Maybe turn the .css file chunking on via the Quantum options?

Ex.
```javascript
<div>
  import('./SomeComponent')
</div>
```

will generate a 2345346.js and 2345346.css in my build

This will also lead to optimal server side rendered index.html responses because you will be able to flush the accessed chunk file names from either your lazy load code split API or a custom component like universal-react-component to enable loading screens etc.

Ex.
```javascript
<div>
 <UniversalComponent 
    Component={import('./SomeComponent')} 
    LoadingComponent={LoadComponent}
</UniversalComponent>
</div>
```

So I need to be able to generate .css files that are imported by each bundle/chunk with the same name and hash-name.

**Comment by nchanged** [comment] 2018-07-01 19:22
That's actually doable. But with Quantum, currently it's extracting the CSS and piping it to the file system. Moreover we have a branch which requires just testing which does the grouping based on user  conditions.

Check out Quantum css options first, we can implement the feature you are talking about😃

**Comment by chickendinosaur** [comment] 2018-07-02 19:19
I have been thinking how I am going to be able to get access to the code split file mapping after the build happens. 

For instance:
```javascript
import('../../component');
```
will result in generate a random hash-chunkname.

In order for me to be to be able to know which files have been access on render I would queue up the files from within a component to access them for tag injected once the renderToString() has been completed. 

Maybe a specific manifest for code-splitting that maps the import path to the generated hash-chunkfile names?

We are on our way to ultimate streamlined dynamic resources! 

On a side note, I pushed out WebIndexPugin that should alleviate having to keep adjusting to ever going changes to resource options as well as custom functionality. Repo; [https://github.com/chickendinosaur/fuse-box-web-index-plugin](https://github.com/chickendinosaur/fuse-box-web-index-plugin)

**Comment by chickendinosaur** [comment] 2018-07-10 08:58
There is not a whole lot to Quantum CSS options in the docs. I see cssCollection in the code but not a whole lot on where to put stuff. Quantum does not currently contain what I need and I couldn't get css bundling to work via dynamic import bundles due to now knowing where to do it. I feel like I'm just hacking shit that should not be done.

**Comment by nchanged** [comment] 2018-08-12 13:01
@chickendinosaur I am actually very close to have it ready

<img width="227" alt="screenshot 2018-08-12 15 00 55" src="https://user-images.githubusercontent.com/1629088/44002284-950aad62-9e40-11e8-9e66-8e02fb31e5d9.png">

So basically once `7cb0b743.js` is loaded it will load `7cb0b743.css` too. Do you think you can help me test it?

**Comment by johnpittman** [comment] 2018-08-12 18:43
Awesome! Definitely can help.

**Comment by johnpittman** [comment] 2018-08-12 22:02
@nchanged. Real quick though on "So basically once 7cb0b743.js is loaded it will load 7cb0b743.css too."

My thoughts on the load process are this:

1) Read from a chunk.manifest.js or some other way to check if a chunk even has a .css chunk to load.
2) Load .css and .js in a non-block/non-dependent manner.

Here is my draft of how it should work. (I know you have utils to handle loading of resources)
```javascript
/**
 * 1) Downloads all resources at the same time for non-block loading.
 * 2) Ensures CSS is loaded in the DOM before JavaScript.
 * 
 * @param chunkName {string} filename of the JavaScript chunk file.
 */
async function loadFeature(chunkName) {
  const promises = [];

  // Load CSS
  if (manifest[chunkName].hasCSS === true) {
    promises.push(fetch('7cb0b743.css'));
  }

  // Load JavaScript.
  promises.push(fetch('7cb0b743.js'));

  let resources;

  try {
    resources = await Promise.all(promises);

    let jsResource = resources[0];

    // Ensure CSS is loaded before JavaScript.
    if (promises.length > 1) {
      // Reset loaded JavaScript resource reference.
      jsResource = resources[1];

      // Add CSS to DOM.
      const link = document.createElement('link');
      link.rel = 'stylesheet';
      link.href = window.URL.createObjectURL(resources[0].blob());

      document.head.appendChild(link);
    }

    // Add JavaScript to DOM.
    const script = document.createElement('script');
    script.type = 'application/javascript';
    script.async = true;
    script.src = window.URL.createObjectURL(jsResource.blob());

    document.head.appendChild(script);
  } catch (err) {
    throw new Error(err);
  }
}
```

**Comment by nchanged** [comment] 2018-08-13 06:58
@johnpittman would you mind submitting a PR? I will point to the place where this should be put?!
The problem is that this js module loading needs a special treatment. I don't think we can sync both js and css, unless we refactor the part that loads resources in Quantum

**Comment by nchanged** [comment] 2018-08-13 08:40
Let's give it a try!!
`fuse-box@3.5.0-next.5`

**Comment by johnpittman** [comment] 2018-08-13 21:42
You are the man. Anything needed to enable it? I'll play with it later tonight.

**Comment by nchanged** [comment] 2018-08-14 09:03
`QuantumPlugin({css : true})`
It's appended to the head. So there is no way to tell if it's loaded. Or is there?

Nonetheless, here is the part where we could tweak around

https://github.com/fuse-box/fuse-box/blob/master/modules/fuse-box-responsive-api/index.js#L300-L302

**Comment by johnpittman** [comment] 2018-08-15 05:15
- loadRemoteScript does not work when hashes are enabled since you're only passing in the .name.
(Error: Refused to apply style from 'http://localhost:4444/6c17d02d.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.)

- I am going to alter so things to parallel download.

**Comment by nchanged** [comment] 2018-08-15 06:04
Thanks I completely forgot about hashing

**Comment by johnpittman** [comment] 2018-08-15 06:18
So this works except if you look at the network tab, the last .css file tries to load again and errors out but I have no idea why. I think it's the style.css that's i the main CSS file but comes in as a chunk name maybe? I am no longer seeing my main CSS loaded. I think the name of the main .css file should match the main .js file for continuity even though it's no big deal.

### loadRemoteScript:
```javascript
	/* @if loadRemoteScript  */
	function loadRemoteScript(basePath, jsFilename, cssFilename) {
		// console.error(url);
		
		/* @if server */
		return Promise.resolve();
		/* @end */

		/* @if browser || universal */
		return Promise.resolve().then(function() {
			/* @if universal */
			if (!isBrowser) {
				return;
			}
			/* @end */

			var d = document;
			var head = d.getElementsByTagName("head")[0];
			/* @if cssLoader */
			if (cssFilename) {
				const linkEl = d.createElement("link");
				linkEl.rel = "stylesheet";
				linkEl.type = "text/css";
				linkEl.href = basePath + cssFilename;
				head.appendChild(linkEl);
			}
			/* @end */

			if (jsFilename) {
				const scriptEl = d.createElement("script");
				scriptEl.type = "text/javascript";
				scriptEl.src = basePath + jsFilename;
				scriptEl.async = true;
				head.appendChild(scriptEl);
			}
		});
		/* @end */
	}
	/* @end */
```

### Using loadRemoteScript
```javascript
	var $cache = {};
	$fsx.l = function(id) {
		return new Promise(function(resolve, reject) {
			if ($cache[id]) {
				return resolve($cache[id]);
			}
			/* @if codeSplitting */
			if (bMapping.i && bMapping.i[id]) {
				var data = bMapping.i[id];
				/* @if universal */
				var path = isBrowser ? bMapping.c.b : bMapping.c.s;
				/* @end */
				/* @if server */
				var path = bMapping.c.s;
				/* @end */

				/* @if browser */
				var path = bMapping.c.b;
				/* @end */

				if (data[2] && data[2].css === true) {
					return loadRemoteScript(path, data[0], data[2].name);
				} 

				req(path + data[0], function(err, result) {
					// console.error(path + data[0]);
					/* @if browser */
					if (!err) {
						new Function(result)();
					}
					/* @end */

					/* @if universal */
					if (!err && isBrowser) {
						new Function(result)();
					}
					/* @end */

					$cache[id] = $fsx.r(data[1]);
					/* @if allowSyntheticDefaultImports */
					syntheticDefaultExportPolyfill($cache[id]);
					/* @end */
					!err ? resolve($cache[id]) : reject(err);
				});
			} else {
				/* @end */

				/* @if loadRemoteScript */
				var isCSS;

				/* @if cssLoader */
				isCSS = /\.css$/.test(id);
				/* @end */
				// id.charCodeAt(4) === 58 || id.charCodeAt(5) === 58)
				if (isCSS) {
					return loadRemoteScript(path, null, id);
				}
				/* @end */
				req(id, function(err, result, ctype) {
					if (!err) {
						/* @if browser */
						var res = ($cache[id] = evaluateModule(id, result, ctype));
						/* @if allowSyntheticDefaultImports */
						syntheticDefaultExportPolyfill(res);
						/* @end */
						resolve(res);
						/* @end */

						/* @if server */
						/* @if allowSyntheticDefaultImports */
						syntheticDefaultExportPolyfill(result);
						/* @end */
						resolve(result);
						/* @end */

						/* @if universal */
						if (isBrowser) {
							var res = ($cache[id] = evaluateModule(id, result, ctype));
							/* @if allowSyntheticDefaultImports */
							syntheticDefaultExportPolyfill(res);
							/* @end */
							resolve(res);
						} else {
							/* @if allowSyntheticDefaultImports */
							syntheticDefaultExportPolyfill(result);
							/* @end */
							resolve(result);
						}
						/* @end */
					} else {
						reject(err);
					}
				});
				/* @if codeSplitting */
			}
			/* @end */
		});
	};
```

**Comment by johnpittman** [comment] 2018-08-15 07:39
This is how it should work to download .css and .js in parallel while loading in order. Now the main.css is not loading and the last .css file name tries to loaded twice which errors. I am lost.

```javascript
	/* @if loadRemoteScript  */
  function loadRemoteScript(basePath, cssFilename) {
    /* @if server */
    return Promise.resolve();
    /* @end */

    /* @if browser || universal */
    return new Promise(function(resolve) {
      /* @if universal */
      if (!isBrowser) {
        return;
      }
      /* @end */

      var d = document;
      /* @if cssLoader */
      if (cssFilename) {
        const linkEl = d.createElement('link');
        linkEl.rel = 'stylesheet';
        linkEl.type = 'text/css';
        linkEl.onload = resolve;
        linkEl.href = basePath + cssFilename;
        var head = d.getElementsByTagName('head')[0];
        head.appendChild(linkEl);
      }
      /* @end */
    });
    /* @end */
  }
	/* @end */
	
	var $cache = {};
	$fsx.l = function(id) {
		return new Promise(function(resolve, reject) {
			if ($cache[id]) {
				return resolve($cache[id]);
			}
			/* @if codeSplitting */
			if (bMapping.i && bMapping.i[id]) {
				var data = bMapping.i[id];
				/* @if universal */
				var path = isBrowser ? bMapping.c.b : bMapping.c.s;
				/* @end */
				/* @if server */
				var path = bMapping.c.s;
				/* @end */

				/* @if browser */
				var path = bMapping.c.b;
				/* @end */

				if (data[2] && data[2].css === true) {
					loadRemoteScript(path, data[2].name);
				}

				req(path + data[0], function(err, result) {
					/* @if browser */
					if (!err) {
						new Function(result)();
					}
					/* @end */

					/* @if universal */
					if (!err && isBrowser) {
						new Function(result)();
					}
					/* @end */

					$cache[id] = $fsx.r(data[1]);
					/* @if allowSyntheticDefaultImports */
					syntheticDefaultExportPolyfill($cache[id]);
					/* @end */
					!err ? resolve($cache[id]) : reject(err);
				});
			} else {
				/* @end */

				/* @if loadRemoteScript */
				var isCSS;

				/* @if cssLoader */
				isCSS = /\.css$/.test(id);
				/* @end */
				// id.charCodeAt(4) === 58 || id.charCodeAt(5) === 58)
				if (isCSS) {
					loadRemoteScript(path, id + '.css');
				}
				/* @end */
				req(id, function(err, result, ctype) {
					if (!err) {
						/* @if browser */
						var res = ($cache[id] = evaluateModule(id, result, ctype));
						/* @if allowSyntheticDefaultImports */
						syntheticDefaultExportPolyfill(res);
						/* @end */
						resolve(res);
						/* @end */

						/* @if server */
						/* @if allowSyntheticDefaultImports */
						syntheticDefaultExportPolyfill(result);
						/* @end */
						resolve(result);
						/* @end */

						/* @if universal */
						if (isBrowser) {
							var res = ($cache[id] = evaluateModule(id, result, ctype));
							/* @if allowSyntheticDefaultImports */
							syntheticDefaultExportPolyfill(res);
							/* @end */
							resolve(res);
						} else {
							/* @if allowSyntheticDefaultImports */
							syntheticDefaultExportPolyfill(result);
							/* @end */
							resolve(result);
						}
						/* @end */
					} else {
						reject(err);
					}
				});
				/* @if codeSplitting */
			}
			/* @end */
		});
	};
```

**Comment by nchanged** [comment] 2018-08-15 08:29
Not sure what you are trying to do here. You shouldn't append `.css` extension. It will be in the config already.

**Comment by johnpittman** [comment] 2018-08-15 16:55
Let's fix this bug first then I can explain with pictures what I did.

List of files is dist folder:
![image](https://user-images.githubusercontent.com/6298219/44161015-bef8c580-a081-11e8-9e05-fdf62265e400.png)

What is being requested on page load which also show:
![image](https://user-images.githubusercontent.com/6298219/44160976-a7214180-a081-11e8-8280-22326674df7b.png)

Problem that I will fix with the chain loading that is happening:
![image](https://user-images.githubusercontent.com/6298219/44161134-0bdc9c00-a082-11e8-95b9-6bfce0d810d9.png)

**Comment by johnpittman** [comment] 2018-08-16 05:57
# Sandbox

[https://github.com/johnpittman/fuse-box-sandbox](https://github.com/johnpittman/fuse-box-sandbox)

- Changes are in the sandbox repo under src/fuse-box (copy of the npm download)
- [https://github.com/johnpittman/fuse-box-sandbox/blob/master/src/fuse-box/modules/fuse-box-responsive-api/index.js](https://github.com/johnpittman/fuse-box-sandbox/blob/master/src/fuse-box/modules/fuse-box-responsive-api/index.js)

# Screens

- Image are from local machine testing.
- Key here is to assure CSS is loaded before JavaScript to render the page properly.

## Before fix:
![image](https://user-images.githubusercontent.com/6298219/44189353-9821aa00-a0e8-11e8-87e7-ebc3ffb8a361.png)

![image](https://user-images.githubusercontent.com/6298219/44190693-8d1d4880-a0ed-11e8-8cd9-7eff1d60b82e.png)

## After fix:
![image](https://user-images.githubusercontent.com/6298219/44190444-7c200780-a0ec-11e8-807c-0eb63d4d1736.png)

![image](https://user-images.githubusercontent.com/6298219/44190647-49c2da00-a0ed-11e8-8da3-3263a22dd7d3.png)


# Code

```javascript
	/* @if loadRemoteScript  */
	function loadRemoteScript(url, isCSS) {
		/* @if server */
		return Promise.resolve();
		/* @end */

		/* @if browser || universal */
		return new Promise(function(resolve, reject) {
			/* @if universal */
			if (!isBrowser) {
				return resolve();
			}
			/* @end */

			var d = document;
			var head = d.getElementsByTagName("head")[0];
			var target;
			/* @if cssLoader */
			if (isCSS) {
				target = d.createElement("link");
				target.rel = "stylesheet";
				target.type = "text/css";
				target.onload = resolve;
				target.onerror = reject;
				target.href = url;
			} else {
				/* @end */

				target = d.createElement("script");
				target.type = "text/javascript";
				target.onload = resolve;
				target.onerror = reject;
				target.async = true;
				target.src = url;

				/* @if cssLoader */
			}
			/* @end */
			head.insertBefore(target, head.firstChild);
		});
		/* @end */
	}
	/* @end */

	var $cache = {};
	$fsx.l = function(id) {
		return new Promise(function(resolve, reject) {
			if ($cache[id]) {
				return resolve($cache[id]);
			}
			/* @if codeSplitting */
			if (bMapping.i && bMapping.i[id]) {
				var data = bMapping.i[id];
				if(typeof data === "number"){
					return resolve($fsx.r(data))
        }
				/* @if universal */
				var path = isBrowser ? bMapping.c.b : bMapping.c.s;
				/* @end */
				/* @if server */
				var path = bMapping.c.s;
				/* @end */

				/* @if browser */
				var path = bMapping.c.b;
				/* @end */

				if (data[2] && data[2].css === true) {
					Promise.all([loadRemoteScript(path + data[2].name, true), new Promise((resolve, reject) => {
						req(path + data[0], function(err, result) {
							/* @if browser */
							if (!err) {
								new Function(result)();
							}
							/* @end */
		
							/* @if universal */
							if (!err && isBrowser) {
								new Function(result)();
							}
							/* @end */
		
							$cache[id] = $fsx.r(data[1]);
							/* @if allowSyntheticDefaultImports */
							syntheticDefaultExportPolyfill($cache[id]);
							/* @end */
							!err ? resolve($cache[id]) : reject(err);
					})
				})]).then((values) => {
						console.log('loaded');
						resolve(values[1]);
					});
				} else {
					req(path + data[0], function(err, result) {
						/* @if browser */
						if (!err) {
							new Function(result)();
						}
						/* @end */

						/* @if universal */
						if (!err && isBrowser) {
							new Function(result)();
						}
						/* @end */

						$cache[id] = $fsx.r(data[1]);
						/* @if allowSyntheticDefaultImports */
						syntheticDefaultExportPolyfill($cache[id]);
						/* @end */
						!err ? resolve($cache[id]) : reject(err);
					});
				}
			} else {
				/* @end */

				/* @if loadRemoteScript */
				var isCSS;

				/* @if cssLoader */
				isCSS = /\.css$/.test(id);
				/* @end */
				// id.charCodeAt(4) === 58 || id.charCodeAt(5) === 58)
				if (isCSS) {
					return loadRemoteScript(id, isCSS);
				}
				/* @end */
				req(id, function(err, result, ctype) {
					if (!err) {
						/* @if browser */
						var res = ($cache[id] = evaluateModule(id, result, ctype));
						/* @if allowSyntheticDefaultImports */
						syntheticDefaultExportPolyfill(res);
						/* @end */
						resolve(res);
						/* @end */

						/* @if server */
						/* @if allowSyntheticDefaultImports */
						syntheticDefaultExportPolyfill(result);
						/* @end */
						resolve(result);
						/* @end */

						/* @if universal */
						if (isBrowser) {
							var res = ($cache[id] = evaluateModule(id, result, ctype));
							/* @if allowSyntheticDefaultImports */
							syntheticDefaultExportPolyfill(res);
							/* @end */
							resolve(res);
						} else {
							/* @if allowSyntheticDefaultImports */
							syntheticDefaultExportPolyfill(result);
							/* @end */
							resolve(result);
						}
						/* @end */
					} else {
						reject(err);
					}
				});
				/* @if codeSplitting */
			}
			/* @end */
		});
	};
```

**Comment by johnpittman** [comment] 2018-08-17 04:47
@nchanged 

I will do a PR, but first can you help me understand something?
Why is fuse-box trying to load the main script twice instead of just executing it after it loads the first time? This was like this before I edited anything.

## Initial resource loaded from index.html

![image](https://user-images.githubusercontent.com/6298219/44248106-48a5b180-a1ae-11e8-8f34-0620fac8cd6c.png)

app.js requested again but since it's from cache it's super faster, then app.js is executed which requests the chunks.

## app.js requested again

![image](https://user-images.githubusercontent.com/6298219/44248174-a508d100-a1ae-11e8-88f8-3ebf6756ebf0.png)

**Comment by nchanged** [comment] 2018-08-17 07:09
Can it be sourcemaps or something? The only reference is in `index.html` can you confirm that?

**Comment by johnpittman** [comment] 2018-08-17 08:36
I made this sandbox for testing if you want to run it: [https://github.com/johnpittman/fuse-box-sandbox](https://github.com/johnpittman/fuse-box-sandbox)
```
$ npm i
$ npm i -g http-server
$ npm run build:prod
$ cd dist/prod
$ http-server
```

Both app.js requests return the same content:
```javascript
(function($fsx){
// default/client.jsx
$fsx.f[25] = function(module,exports){
Object.defineProperty(exports, '__esModule', { value: true });
const React = $fsx.r(22);
const ReactDOM = $fsx.r(19);
const root_1 = $fsx.r(26);
ReactDOM.render(React.createElement(root_1.default, null), document.getElementById('root'));
}
// default/components/root/index.jsx
$fsx.f[26] = function(module,exports){
Object.defineProperty(exports, '__esModule', { value: true });
const React = $fsx.r(22);
$fsx.r(27);
$fsx.l('6c17d02d').then(() => {
    console.log('chunk a loaded.', arguments);
});
$fsx.l('5c651a6f').then(() => {
    console.log('chunk c loaded.', arguments);
});
const Root = () => {
    return React.createElement('div', { className: 'app' }, React.createElement('span', null, 'Root'));
};
exports.default = Root;
}
$fsx.r(25)
})($fsx);
```

#### Steps checked
- Find all in files there is no app.js references.
- View page source show only one import of the file.
- It has to be with how you handle loading intially.

Do a "find in folder" on the fuse-box project.
First, you have multiple version of the same loadScript method in 3 spots. 

### module -> fuse-box-loader-api
```javascript
function $loadURL(url) {
    if ($isBrowser) {
        var d = document;
        var head = d.getElementsByTagName("head")[0];
        var target;
        if (/\.css$/.test(url)) {
            target = d.createElement("link");
            target.rel = "stylesheet";
            target.type = "text/css";
            target.href = url;
        }
        else {
            target = d.createElement("script");
            target.type = "text/javascript";
            target.src = url;
            target.async = true;
        }
        head.insertBefore(target, head.firstChild);
    }
}
```
### module -> fuse-box-responsive-api -> dev-imports.js
```javascript
function loadRemoteScript(url) {
		return Promise.resolve().then(function() {
			if (FuseBox.isBrowser) {
				let d = document;
				var head = d.getElementsByTagName("head")[0];
				var target;
				if (/\.css$/.test(url)) {
					target = d.createElement("link");
					target.rel = "stylesheet";
					target.type = "text/css";
					target.href = url;
				} else {
					target = d.createElement("script");
					target.type = "text/javascript";
					target.src = url;
					target.async = true;
				}
				head.insertBefore(target, head.firstChild);
			}
		});
	}
```
### module -> fuse-box-responsive-api -> index.js (our new CSS loading code)
```javascript
	function loadRemoteScript(url, isCSS) {
		/* @if server */
		return Promise.resolve();
		/* @end */

		/* @if browser || universal */
		return new Promise(function(resolve, reject) {
			/* @if universal */
			if (!isBrowser) {
				return resolve();
			}
			/* @end */

			var d = document;
			var head = d.getElementsByTagName("head")[0];
			var target;
			/* @if cssLoader */
			if (isCSS) {
				target = d.createElement("link");
				target.rel = "stylesheet";
				target.type = "text/css";
				target.onload = resolve;
				target.onerror = reject;
				target.href = url;
			} else {
				/* @end */
debugger;
				target = d.createElement("script");
				target.type = "text/javascript";
				target.onload = resolve;
				target.onerror = reject;
				// Should this be defer to keep the order of script execution? Script still download in parallel but load in order of other defers.
				// target.defer = true; 
				target.async = true; 
				target.src = url;

				/* @if cssLoader */
			}
			/* @end */
			head.insertBefore(target, head.firstChild);
		});
		/* @end */
	}
```

I am willing to be that this is the problem somewhere, but I have to sleep for another 15 hour day of coding tomorrow.

### module -> timers -> index.js 
```javascript
	function installReadyStateChangeImplementation() {
			var html = doc.documentElement;
			registerImmediate = function(handle) {
				// Create a <script> element; its readystatechange event will be fired asynchronously once it is inserted
				// into the document. Do so, thus queuing up the task. Remember to clean up once it's been called.
				var script = doc.createElement("script");
				script.onreadystatechange = function() {
					runIfPresent(handle);
					script.onreadystatechange = null;
					html.removeChild(script);
					script = null;
				};
				html.appendChild(script);
			};
		}
```

**Comment by johnpittman** [comment] 2018-08-17 08:45
Removing app.js from the ```index.html``` removes both resource calls so that means you guys bundle something in the main file(installReadyStateChangeImplementation seems like a good place to start) that executes to re-fetch and apply the app.js.

**Comment by nchanged** [comment] 2018-08-17 08:54
I just checked my requests... Got only 1 for app.js

**Comment by johnpittman** [comment] 2018-08-17 09:05
Wow man you are right. Incognito works perfect. Now to figure out wtf is causing that in standard chrome.

I referred to those other files because all the code is redundant. You're just missing an isCSS param or isBrowser param.

All good my brother! Stoked to have this working and so easy.

**Comment by nchanged** [comment] 2019-08-27 13:22
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.

**Closed by nchanged** 2019-08-27 13:22 UTC
