### ISSUE TITLE
Error when importing new (not cached) module `... does not provide a module`

### ISSUE THREAD

**Issue by whitecolor** [fuse-box/fuse-box#689] opened 2017-07-26 08:47 UTC
This issue happens when adding import of newly not yet imported module (that is not in cache yet). If it is in cache event on new run there is no error.

![fuse-issues-xstream-extra-import](https://user-images.githubusercontent.com/736697/28611860-b1e2fb90-7206-11e7-89d3-710bc5b0b7fe.gif)

Code and steps to reporoduce can be taken from here:
https://github.com/whitecolor/fusebox-issues/tree/master/xstream-extra-import

**Comment by nchanged** [comment] 2017-07-26 09:22
@whitecolor That's kind on invalid ES6 javascript. All your imports must be at the top of your module.

**Comment by nchanged** [comment] 2017-07-26 09:25
Please add all the packages to package.json. I can't run it. And instructions on how to launch it

**Comment by whitecolor** [comment] 2017-07-26 11:06
1) Well first it is not ES6, it is Typescript =) It should be compiled just fine to ES5, I just grouped lines that should be uncommented.

2) If you clone the repo from repo root you should change dir to `xstream-extra-import`, as it is a monorepo, that contains multiple projects. In the dir run `npm install` and `npm run watch`

**Comment by nchanged** [comment] 2017-07-26 11:29
yep @whitecolor that's invalid and defeats the purpose of using import syntax, I am not sure how typescript even compiled it. you can't do for example
```
function(){
 import "./bla"
}
```

**Comment by whitecolor** [comment] 2017-07-26 12:14
In your example you will get the syntax error: `An import declaration can only be used in a namespace or module.`

My code is valid in terms of ES/TS language syntax. Imports do not define any order they just should be placed in module's root scope, placing on top is just a matter of readability. 

Anyway, you can change it to "valid syntax", the error still will be here.

**Comment by nchanged** [comment] 2017-07-29 19:04
I see the bug yep, the cache has been always tricky. That's why I suggest you restart your fuse process when adding a new module

**Comment by whitecolor** [comment] 2017-07-29 19:51
> That's why I suggest you restart your fuse process when adding a new module

You are not serious, are you? This definitely should not be user's responsibility. Flow especially, standard flow (and adding/removing modules is a part of standard flow) should be absolutely flawless, transparent and seamless.

**Comment by nchanged** [comment] 2017-07-30 07:12
listen, it doesn't bug most of the people, and most of the time caching works. Let me remind you - this is an open source, and you are not paying money for it. Feel free to investigate the problem instead of ranting

**Comment by whitecolor** [comment] 2017-07-30 08:02
> it doesn't bug most of the people,

And I really wonder why? They don't add new modules/imports to projects? So maybe I'm doing something wrong?

Usually, there is a lot of things that don't bother most of the people, and that doesn't mean that those things should not be accomplished. You probably know what happens often when ~~average~~ most of devs try a project and it doesn't work *as expected* and gives an error - they don't go to github/gitter they just leave it alone and say: *well maybe some next day ~me~ this project will be luckier*.

> Feel free to investigate the problem instead of ranting

I'm not just ranting. I think this is quite a fundamental bug, so it definitely should not be there, and I believe it should be really not hard for authors to fix such things, esp considering that the project in the active stage of development and you know/remember all your codebase very well.

**Comment by devmondo** [comment] 2017-07-30 10:53
@whitecolor we are trying our best, and input, investigations, like yours helps us to make fuse better.
 
it is a valid bug, and we had bugs around caching before and we got down to them and fixed them. what @nchanged  is saying above does not mean we will not fix it, he is trying to say we are really doing our best and working on this on a daily basis. but when you said > You are not serious, are you? I am sure you agree that the tone was not helpful. 

please work with us to make fuse better for you and for others and we promise we will do our best :)

**Comment by whitecolor** [comment] 2017-07-30 12:31
Yeah sorry for the tone, sometimes my style may seem conflicting and intolerant, though I don't mean this way.

**Comment by devmondo** [comment] 2017-07-30 13:16
@whitecolor no problem, thanks for the cooperation and rest assured we will keep working hard to fix your issues :)

**Comment by Janaka-Steph** [comment] 2017-08-08 09:00
Hello,

I also have an issue with the same error message, but different context. Error is : `~/node_modules/reactstrap-tether/src/js/tether.js does not provide a module`.
I am using an alias to load reactstrap-tether because Fusebox can't load the built version on Quantum mode.
```
alias: {
      "reactstrap-tether": '~/node_modules/reactstrap-tether/src/js/tether.js'
}
```

**Comment by nchanged** [comment] 2017-08-08 09:14
Wrong alias
`~` if you homeDir. 
```
alias: {
      "reactstrap-tether": `reactstrap-tether/src/js/tether.js'
}
```
clear the cache

**Comment by Janaka-Steph** [comment] 2017-08-08 09:30
It doesn't work for me. `Uncaught SyntaxError: Unexpected token export` on line: `export default TetherBase;`
Btw, I don't import `reactstrap-tether` in my code, it is a dependency of a dependency.

**Comment by nchanged** [comment] 2017-08-08 09:32
you were supposed to import a transpiled module a from node_module, not the source

**Comment by whitecolor** [comment] 2017-08-08 11:00
> clear the cache

This recommendation sounds like fuse-box mantra =) Isn't cache is cleared automatically now on launch?

![image](https://user-images.githubusercontent.com/736697/29069011-87277bf0-7c52-11e7-9757-742504c57b7b.png)

**Comment by nchanged** [comment] 2017-08-08 11:07
@whitecolor only if `fuse.js` has changed

**Comment by whitecolor** [comment] 2017-08-08 11:16
Does it check file's text content? 
I would prefer to be cleared it each time, just not to create this extra hassle for users, and for authors not to repeat cache mantra ever again.

**Comment by Shepless** [comment] 2017-10-03 21:51
@whitecolor you can set `cache: false` as a temporary work around (not ideal I know). I have just started contributing so my knowledge isn't as in depth but I will certainly take a look to see if I can resolve this issue.

**Comment by Gustorn** [comment] 2019-01-28 21:23
I'm also running into this issue using the latest version of fuse-box. I made a minimal repro at [Gustorn/fuse-box-cache-issue](https://github.com/Gustorn/fuse-box-cache-issue). FuseBox has been a fantastic experience so far but this issue is becoming more annoying as packages start to modularize themselves this way. The issue is reproducible with:

* @material-ui/core
* @material-ui/icons
* date-fns

I did some preliminary debugging and it seems like that neither the file nor the memory cache gets updated in these cases which leads to the incorrect behavior: the ModuleCache thinks that the module is cached and so it happily resolves the package into the cached version but at runtime the new exports are not there. Unfortunately I'm not very well versed in the caching mechanism so that's all I could do in a short time.

It would be awesome if you could look into this: this is the last annoying thing that actually severely hinders a fast development workflow.

**Comment by nchanged** [comment] 2019-01-28 22:11
@Gustorn I will take a look at it, it bugs me too sometimes. I think the workaround would be to request a module via socket connection.

**Comment by nchanged** [comment] 2019-01-29 09:47
@Gustorn do you think you can help? I have a good progress, but I need to switch now
https://github.com/fuse-box/fuse-box/commit/a318900677456a09eb95eb85810ce4f377952b18

Basically, this peace needs to work

https://github.com/fuse-box/fuse-box/commit/a318900677456a09eb95eb85810ce4f377952b18#diff-b3b0577122b7966eac777eaf732a6685R301

It should collect the dependencies recursively.

**Comment by Gustorn** [comment] 2019-01-30 17:39
I'm swamped at work currently but I'll take a look this weekend if you don't get to it first. Thanks for the quick reply!

**Comment by nchanged** [comment] 2019-02-02 21:01
#1483

**Comment by nchanged** [comment] 2019-02-02 21:01
@Gustorn follow the linked issue ;-)

**Comment by nchanged** [comment] 2019-08-27 13:12
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.

**Closed by nchanged** 2019-08-27 13:12 UTC
Labels: bug
