### ISSUE TITLE
Proxy feature missing in development server

### ISSUE THREAD

**Issue by screendriver** [fuse-box/fuse-box#698] opened 2017-08-01 06:06 UTC
Currently I am missing the ability to proxy API requests from my app to my API services. For example at development time I serve my App from `localhost` but the microservices that I consume are not running at my machine locally (they are running in a production domain) and does **not** allow CORS requests.

In webpack I solved this with following configuration:

```js
devServer: {
  inline: true,
  historyApiFallback: true,
  proxy: {
    '/services/': {
      target: 'https://www.myapp.com',
      secure: false,
      changeOrigin: true,
    },
  },
},
```

With this configuration all fetch requests in my App to `/services/foo/bar` will be proxied to `https://www.myapp.com/services/foo/bar`. With fuse-box the request URL looks like this at the moment `http://localhost:4444/services/foo/bar`

**Comment by nchanged** [comment] 2017-08-01 06:39
Good feature to have. Will be in the next version

**Comment by screendriver** [comment] 2017-08-01 06:48
Great! Thank you very much 💃

**Comment by nchanged** [comment] 2017-08-01 07:33
`fuse-box@2.2.2-beta.7`

http://fuse-box.org/page/development#proxy

**Comment by whitecolor** [comment] 2017-08-01 07:33
I thought it was by design that this should be implemented by the user using custom server config. Then probably `historyApiFallback` feature could be too included.

**Closed** 2017-08-01 07:46 UTC

**Comment by screendriver** [comment] 2017-08-01 09:39
`historyApiFallback` would be nice to have as well 😉

**Comment by patrickmichalina** [comment] 2017-08-01 14:45
historyFallback is a hard requirement for SPA deep linking

**Comment by whitecolor** [comment] 2017-08-01 15:03
@patrickmichalina not that it is easy to set up it now with custom httpServer config, read the docs about it.

**Comment by patrickmichalina** [comment] 2017-08-11 19:51
@whitecolor can you explain? I cannot get it to work. I've tried proxying to no avail.

**Comment by whitecolor** [comment] 2017-08-12 03:56
http://fuse-box.org/page/development#express-application-access

**Comment by jpike88** [comment] 2018-05-02 01:27
this has regressed, no longer works.

**Comment by nchanged** [comment] 2018-05-02 05:34
What do you mean? I used it yesterday

**Comment by jpike88** [comment] 2018-05-02 06:44
Oh I'm an idiot. I've noticed a fair amount of documentation links dont work anymore, I assumed wrong...

**Comment by nchanged** [comment] 2018-05-02 06:55
@jpike88 the website was updated, yep
