### ISSUE TITLE
HMR on CSS Moduler loader won't keep class name.

### ISSUE THREAD

**Issue by kyasbal-1994** [fuse-box/fuse-box#857] opened 2017-10-10 16:11 UTC
I'm facing a problem with fuse box. I want to enable hmr with CSSModule. I'm using StylusPlugin ,CSS Module plugin, CSS module.
I confirmed that updated style is injected correctly.
But hash of class names that is generated for each are not same. Therefore, hmr is not working. How should I fix this?

This is my fusebox.ts.

```ts
import { CSSModules, CSSPlugin, FuseBox, StylusPlugin } from "fuse-box";
import { argv } from "yargs";

// Arrange yargs input
interface IBuildConfig {
    watchMode: boolean;
    hotModuleLoading: boolean;
    devServer: boolean;
    productionMode: boolean;
}
const config = {} as IBuildConfig;
config.watchMode = argv.watch || false;
config.hotModuleLoading = argv.hotModuleLoading || false;
config.devServer = argv.devServer || false;
config.productionMode = argv.productionMode || false;

// Configure build steps

const fuse = FuseBox.init({
    homeDir: "src",
    output: "public/dist/$name.js",
    tsConfig: "./tsconfig.client.json",
    cache: true,
    sourceMaps: true,
});

let instruction = fuse.bundle("app").target("browser").plugin(StylusPlugin(), CSSModules(), CSSPlugin({
    group: "bundle.css",
    outFile: "./public/dist/bundle.css",
    inject: (file: string) => `dist/${file}`,
})).instructions(">./client/index.tsx");
if (config.watchMode) {
    instruction = instruction.watch();
}
if (config.hotModuleLoading) {
    instruction = instruction.hmr({
    });
}
if (config.devServer) {
    fuse.dev({
        open: true,
        root: "public",
    });
}

fuse.run();
```

All of the project code are available on [here](https://github.com/kyasbal-1994/ts-environment-starter ). 

Thanks.

**Comment by nchanged** [comment] 2017-10-11 19:48
Should be working beautifully in `fuse-box@2.3.4-beta.7`
It turns out it never had caching nor CSSDependency analysis enabled. Please, verify

**Comment by kyasbal-1994** [comment] 2017-10-12 10:42
Unfortunately, It wont work for me. I updated fuse-box to use that version and removed `.fusebox` directory for in case.
However, that also change class name on HMR.

**Comment by nchanged** [comment] 2017-10-12 10:56
of course it will change it, isn't that what you want?

**Comment by nchanged** [comment] 2017-10-26 19:11
I am closing this issue for now, feel free to re-open once reproduced

**Closed by nchanged** 2017-10-26 19:11 UTC
Labels: bug
