### ISSUE TITLE
Bundling for incorrect target

### ISSUE THREAD

**Issue by cah-dunn** [fuse-box/fuse-box#1367] opened 2018-08-28 15:42 UTC
I have the FuseBox [`target`](https://fuse-box.org/page/configuration#target) set to `browser@es5`, however the `main` script is being bundled rather than the `browser` script in cases like [`cross-fetch/polyfill`](https://github.com/lquixada/cross-fetch/blob/master/polyfill/package.json).

As a debug step I tried targeting both `browser` and `server`, comparing the cached `cross-fetch` file in `.fusebox`. While both pull in the `node-polyfill` source, you can see that the file generated with `target: "browser"` references `dist/browser-ponyfill.js` at the end, but with `target: "server"` it references `dist/node-ponyfill.js`.

File generated with `target: "browser"`: https://gist.github.com/cah-dunn/7295ab14e0f529d9c03b7f11728ff269
File generated with `target: "server"`: https://gist.github.com/cah-dunn/cdcb220b1dd7a45a37b3f22000a1adc8

Everything works if I reference `cross-fetch/dist/browser-polyfill` explicitly.

**Comment by nchanged** [comment] 2018-08-28 15:50
So what's the actual problem? Target browser will take an actual effect when using Quantum , Dev builds are always universal

**Comment by cah-calebboyd** [comment] 2018-08-28 15:59
If that is the case then these docs are wrong https://fuse-box.org/page/configuration#target

**Comment by nchanged** [comment] 2018-08-28 16:06
As I mentioned, production builds look different 
Besides polyfills will be there unless there are conditions that Quantum understands

**Comment by cah-dunn** [comment] 2018-08-28 16:19
Ok, that's good to know. I was debugging with the dev build because the production build was broken. I'm still seeing the same problem in the production build with `target: "browser"` set on the QuantumPlugin config using `fuse-box@3.4.0`.

**Comment by nchanged** [comment] 2018-08-28 16:48
What do you mean by "broken"? Could you reproduce it in a repository?

**Comment by cah-dunn** [comment] 2018-08-28 17:55
Broken in the sense that since `node-fetch` was being bundled, the polyfill for `fetch` was not being loaded correctly. I'll get a repo put together.

**Comment by cah-dunn** [comment] 2018-08-28 18:40
@nchanged [`cross-fetch/polyfill`](https://github.com/lquixada/cross-fetch/blob/master/polyfill/package.json) is just a package.json with `main` pointing at the node polyfill and `browser` pointing at the browser polyfill. I would assume fuse-box should know which one to bundle by my specifying `target: 'browser'` in the config?

**Comment by nchanged** [comment] 2018-08-28 18:42
Riiight, I see. Yes It knows about it. But a repo would be nice, I would like to see how you actually use it.

**Comment by cah-dunn** [comment] 2018-08-28 19:30
No problem. Here's a minimal reproducible repo: https://github.com/cah-dunn/fuse-box-issue-1367

**Comment by eddyw** [comment] 2018-08-29 01:51
@cah-dunn but you're shimming the lib. That means you should provide/load the lib in a script tag on browser because you're omitting the `source` option.

**Comment by cah-dunn** [comment] 2018-08-29 14:35
@eddyw I removed the shimming config from that repo but, as @cah-calebboyd mentioned, the same issue persists.

**Comment by nchanged** [comment] 2018-10-26 06:38
Is this one still relevant?

**Comment by cah-dunn** [comment] 2018-10-26 13:56
I believe so - I updated the reproduction repo to 3.5.0 and `require('cross-fetch/polyfill')` still pulls in the node src with `target: 'browser'` set.

But it's not a blocking issue since you can just `require('cross-fetch/dist/browser-polyfill')`.

**Comment by nchanged** [comment] 2019-08-27 12:44
This has been all fixed in `v4`. Please upgrade to the [major version](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

**Closed by nchanged** 2019-08-27 12:44 UTC
