### ISSUE TITLE
Quantum Tree shaking issue

### ISSUE THREAD

**Issue by mdlawson** [fuse-box/fuse-box#1064] opened 2018-01-27 11:27 UTC
See example at https://github.com/mdlawson/fuse-box-cosmos-example/tree/3.1.0

When `treeshake: true` in fuse.ts, the produced bundle is broken:

```js
(function($fsx){
// default/index.jsx
$fsx.f[28] = function(module,exports){
Object.defineProperty(exports, '__esModule', { value: true });
const react_1 = $fsx.r(0);
const react_dom_1 = $fsx.r(23);
$fsx.r(29);
const App_1 = $fsx.r(30);
react_dom_1.render(react_1.default.createElement(App_1.default, null), document.getElementById('app'));
}
// default/css/main.css
$fsx.f[29] = function(module,exports){
Object.defineProperty(exports, '__esModule', { value: true });
module.exports.default = {};
}
// default/App.jsx
$fsx.f[30] = function(module,exports){
Object.defineProperty(exports, '__esModule', { value: true });
const react_1 = $fsx.r(0);
const Card_1 = $fsx.r(31);
class App extends react_1.Component {
    render() {
        return react_1.default.createElement('div', null, react_1.default.createElement(Card_1.default, null, 'Hello World'));
    }
}
exports.default = App;
}
// default/components/Card/index.js
$fsx.f[31] = function(module,exports){
Object.defineProperty(exports, '__esModule', { value: true });
const Card_1 = $fsx.r(32); // This require is undefined
var Card_css_1 = $fsx.r(33);
exports.styles = Card_css_1.default;
exports.default = Card_1.default;
}
// default/components/Card/Card.css
$fsx.f[33] = function(module,exports){
Object.defineProperty(exports, '__esModule', { value: true });
module.exports.default = { 'card': 'file__card___3Nw' };
}
$fsx.r(28)
})($fsx);
```

The entire `components/Card/Card.js` file has been stripped from the bundle, despite being required by `components/Card/index.js` which itself is used.

The logs also show it being removed:
```
  → tree shaking: Remove Props from default/components/Card/index.js
  → tree shaking: Remove Card from default/components/Card/Card.jsx
  → tree shaking: Mark for removal default/components/Card/Card.jsx
```

I thought the problem was something to do with [src/components/Card/Card.tsx](https://github.com/mdlawson/fuse-box-cosmos-example/blob/master/src/components/Card/Card.tsx) being exported twice (default and named), but only one export being used. However in my testing, no matter how that class is exported (default, named, both) that file ends up being dropped in tree shaking.

I can reproduce this on both the latest `3.1.0` beta and on `3.0.2`.

**Comment by nchanged** [comment] 2018-01-30 14:49
@mdlawson just tried the example. I was wondering what is off, I've moved your src with my own config and couldn't reproduce the issue

```
const { FuseBox, WebIndexPlugin, CSSPlugin, QuantumPlugin } = require("fuse-box");
const fuse = FuseBox.init({
    homeDir: "src",
    output: "dist/$name.js",
    target: "browser",
    allowSyntheticDefaultImports: true,
    sourceMaps: true,
    plugins: [
        CSSPlugin(),
        true && QuantumPlugin({
            treeshake: true,
            uglify: false
        }),
        WebIndexPlugin()
    ]
});
fuse.dev();

fuse.bundle("app")
    .watch()
    .hmr()
    .instructions(" > index.tsx");
fuse.run();
```

Quantum removes everything because you are using a wrong entry point (my wild guess)
Please confirm it, I would like to close it as soon as possible.

Here is my log

```
 → tree shaking: Mark for removal react/cjs/react.development.js
  → tree shaking: Mark for removal fbjs/lib/invariant.js
  → tree shaking: Mark for removal fbjs/lib/warning.js
  → tree shaking: Mark for removal fbjs/lib/hyphenateStyleName.js
  → tree shaking: Mark for removal fbjs/lib/hyphenate.js
  → tree shaking: Mark for removal fbjs/lib/camelizeStyleName.js
  → tree shaking: Mark for removal fbjs/lib/camelize.js
  → tree shaking: Mark for removal process/index.js
  → tree shaking: Mark for removal prop-types/checkPropTypes.js
  → tree shaking: Mark for removal prop-types/lib/ReactPropTypesSecret.js
  → tree shaking: Mark for removal react-dom/cjs/react-dom.development.js
```

FuseBox 3.1.0-next.20

**Comment by mdlawson** [comment] 2018-01-30 21:03
I can still reproduce this even with your config. I have stripped down my example heavily (https://github.com/mdlawson/fuse-box-cosmos-example/tree/treeshaking-issue) and identified what I presume is the cause:

Commenting this line
https://github.com/mdlawson/fuse-box-cosmos-example/blob/treeshaking-issue/src/Card/index.ts#L2
Allows the application to run in the browser and display "Hello World" correctly, with the log

```
  → tree shaking: Mark for removal react/cjs/react.development.js
  → tree shaking: Mark for removal fbjs/lib/invariant.js
  → tree shaking: Mark for removal fbjs/lib/warning.js
  → tree shaking: Mark for removal fbjs/lib/hyphenateStyleName.js
  → tree shaking: Mark for removal fbjs/lib/hyphenate.js
  → tree shaking: Mark for removal fbjs/lib/camelizeStyleName.js
  → tree shaking: Mark for removal fbjs/lib/camelize.js
  → tree shaking: Mark for removal process/index.js
  → tree shaking: Mark for removal prop-types/checkPropTypes.js
  → tree shaking: Mark for removal prop-types/lib/ReactPropTypesSecret.js
  → tree shaking: Mark for removal react-dom/cjs/react-dom.development.js
  → Render bundle app
```
With that line present, the app does not render and produces the error:

![image](https://user-images.githubusercontent.com/1243016/35591153-ec8247fe-0600-11e8-8a7d-f7ac44fc1766.png)

And the log:

```
 → tree shaking: Remove Props from default/Card/index.js
  → tree shaking: Mark for removal default/Card/Card.jsx
  → tree shaking: Mark for removal react/cjs/react.development.js
  → tree shaking: Mark for removal fbjs/lib/invariant.js
  → tree shaking: Mark for removal fbjs/lib/warning.js
  → tree shaking: Mark for removal fbjs/lib/hyphenateStyleName.js
  → tree shaking: Mark for removal fbjs/lib/hyphenate.js
  → tree shaking: Mark for removal fbjs/lib/camelizeStyleName.js
  → tree shaking: Mark for removal fbjs/lib/camelize.js
  → tree shaking: Mark for removal process/index.js
  → tree shaking: Mark for removal prop-types/checkPropTypes.js
  → tree shaking: Mark for removal prop-types/lib/ReactPropTypesSecret.js
  → tree shaking: Mark for removal react-dom/cjs/react-dom.development.js
  → Render bundle app
```

Let me know if you need any more details :)

**Comment by nchanged** [comment] 2018-01-31 17:41
@mdlawson thanks!
I am really confused here.

Setting `"target": "es7"` fixes it.... i will continue digging

**Closed** 2018-01-31 19:50 UTC
Labels: bug
