### ISSUE TITLE
If bundle name contains dot, no extension will be added in output file

### ISSUE THREAD

**Issue by JiDai** [fuse-box/fuse-box#525] opened 2017-05-13 19:42 UTC
Hi,

```
const fuse = FuseBox.init({
    homeDir: "src",
    output: "dist/$name.js",
});
fuse.bundle("my.app")
    .instructions(`>app.tsx`);

fuse.run()
```

Will generate a `dist/my.app` file instead of `dist/my.app.js`

**Comment by nchanged** [comment] 2017-05-13 21:53
That's not a bug, but expected behavior.  FuseBox thinks that you set an extension

**Comment by JiDai** [comment] 2017-05-14 08:29
Ok, I expected there will be an extension because I put `.js` in output setting

**Comment by devmondo** [comment] 2017-05-14 18:00
will close this for now, let us know otherwise :)

**Closed by devmondo** 2017-05-14 18:00 UTC
Labels: discussion
