### ISSUE TITLE
crypto.createHash is not a function

### ISSUE THREAD

**Issue by vutran1710** [fuse-box/fuse-box#1515] opened 2019-03-27 03:23 UTC
I stumbled on this error, cant figure out how to solve it.
Im trying to use a npm library called **@colony/purser-ledger**, it works well with other tools like `Create-react-app`, but not with my fusebox. When executing a specific function, it throws an error like below>
```js
Uncaught (in promise) Error: Could not export the wallet account, check the values you are sending to your Ledger Wallet: m/44'/889'/0'/0 crypto.createHash is not a function
    at _callee2$ (purser-ledger@1.2.4:893)
    at tryCatch (regenerator-runtime@0.13.2:48)
    at Generator.invoke [as _invoke] (regenerator-runtime@0.13.2:274)
    at Generator.prototype.(:3000/anonymous function) [as next] (https://localhost:3000/app.js:99312:21)
    at asyncGeneratorStep (runtime@7.4.2:21)
    at _next (runtime@7.4.2:43)
```

Here is my `fuse.ts` file
```js
import * as fs from 'fs'

import {
  FuseBox,
  CopyPlugin,
  EnvPlugin,
  JSONPlugin,
  SassPlugin,
  CSSPlugin,
  CSSResourcePlugin,
  WebIndexPlugin,
  QuantumPlugin,
} from 'fuse-box'

import {
  src,
  task,
} from 'fuse-box/sparky'

const isProduction = process.env.STG === 'production'
const assetExts = ['ico', 'jpg', 'png'].map(ex => `static/*.${ex}`)

const config = {
  homeDir: '.',
  output: 'dist/$name.js',
  target: 'browser@esnext',
  autoImport: {
    React: 'react',
  },
  plugins: [
    EnvPlugin(process.env),
    WebIndexPlugin({ template: 'index.html' }),
    CopyPlugin({ files: assetExts }),
    [
      SassPlugin({ importer: true }),
      CSSResourcePlugin({
        macros: {
          static: `${__dirname}/static/`
        },
        dist: 'dist/css-resources',
      }),
      CSSPlugin({
        inject: file => `${file}`,
        outFile: file => `dist/${file}`,
      }),
    ],
    JSONPlugin(),
    isProduction && QuantumPlugin({
      replaceProcessEnv: true,
      treeshake: true,
      uglify: true,
      bakeApiIntoBundle: true,
    }),
  ],
  sourceMaps: !isProduction,
}

task('clean_all', () => src('dist').clean('dist').exec())
task('default', ['clean_all'], () => {
  const fuse = FuseBox.init(config)
  const bundle = fuse.bundle('app')
  if (!isProduction) {
    fuse.dev({
      port: 3000,
      https: {
        key: fs.readFileSync("./cert/app.key", "utf8"),
        cert: fs.readFileSync("./cert/app.crt", "utf8"),
      }
    })
    bundle
        .watch('(component|service|static|style)/**.(ts|tsx|scss|jpg|png)')
        .hmr()
  }
  bundle.instructions('> index.tsx')
  return fuse.run()
})
```
Also the tsconfig.json..
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "ESNext",
    "jsx": "react",
    "importHelpers": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "rootDir": ".",
    "baseUrl": ".",
  }
 }

```

it would be awesome if somebody can tell me whats happening. btw the project im working on is below, kind of blockchain thing, and the branch is `spa-login`

https://github.com/tomochain/relayerms/tree/spa-login

Thanks in advance!

**Comment by nchanged** [comment] 2019-03-27 07:03
@vutran1710 Hi
I can't reproduce your error
All I got is:

<img width="1055" alt="Screenshot 2019-03-27 08 02 21" src="https://user-images.githubusercontent.com/1629088/55056562-b4b29700-5066-11e9-9cca-7264a0fb7988.png">

Make sure to clear the cache (`.fusebox`) folder. Also, if you managed to narrow it down to a simpler example that would help too.

**Comment by vutran1710** [comment] 2019-03-27 07:11
> @vutran1710 Hi
> I can't reproduce your error
> All I got is:
> 
> <img alt="Screenshot 2019-03-27 08 02 21" width="1055" src="https://user-images.githubusercontent.com/1629088/55056562-b4b29700-5066-11e9-9cca-7264a0fb7988.png">
> 
> Make sure to clear the cache (`.fusebox`) folder. Also, if you managed to narrow it down to a simpler example that would help too.

Tks alot for noticing this so fast.
That error comes from the invalid url (APP_HOST), you can temporarily hard-code the API in `frontend/service/constant', changing it to localhost:8888 with tornado backend already running (using pipenv)

Btw, i tried to remove .fusebox more than a bunch of time and it never worked, so i think its not helpful

**Comment by nchanged** [comment] 2019-03-27 08:08
@vutran1710 what you can do is:
Open the compiled bundle, find find
`FuseBox.pkg("crypto`
and find out why it's not a function. And what is it in the first place.

**Comment by patrickmichalina** [comment] 2019-09-28 20:48
I am using this in node/electron builds just fine via fusebox v4.

**Comment by nchanged** [comment] 2019-09-29 06:06
Nice, so we can close this one ?

**Comment by patrickmichalina** [comment] 2019-09-30 01:37
Closing as dev work has moved along to v4 and crypto is working fine bundled in both Node and Electron environments. If this was a bug in v3 I doubt anyone has the bandwidth to backport a fix at this time. Recommend migrating to v4 and posting again if the issue persists.

**Closed by patrickmichalina** 2019-09-30 01:37 UTC
