### ISSUE TITLE
Import module issue with HMR

### ISSUE THREAD

**Issue by whitecolor** [fuse-box/fuse-box#541] opened 2017-05-17 12:14 UTC
fuse-box 2.0.0
The issue can be reproduced with the repo https://github.com/whitecolor/fuse-box-xstream
```
TypeError: Cannot read property 'default' of undefined
```

**Comment by devmondo** [comment] 2017-05-17 14:21
@whitecolor 
just cloned your repo and everything works fine, just make sure you do the following
* install xtream and loadash deps from npm
* install the latest fuse beta `npm install fuse-box@^2.1.0-beta.2` ( not required, just to make sure)
* clear `.fusebox` cache folder
* `node fuse.js` (after you compile `fuse.ts` it as you did it with typescript)

here is a picture to show you how it is running fine 
![image](https://cloud.githubusercontent.com/assets/1266367/26158686/946f58ac-3b2d-11e7-8f8c-a205ab47f6a6.png)

**Comment by devmondo** [comment] 2017-05-17 15:12
will close this for now, let us know otherwise :)

**Comment by whitecolor** [comment] 2017-05-17 17:42
See this is my flow with this repo:
![fuse-box-xstream-issue](https://cloud.githubusercontent.com/assets/736697/26168009/17d4e65c-3b52-11e7-8406-9c567a1fbebb.gif)

**Comment by devmondo** [comment] 2017-05-17 17:49
something is weird, it is really working, I tried npm install and not yarn, maybe yarn is the issue?

**Comment by whitecolor** [comment] 2017-05-17 17:54
Not sure how it can even be related. But I removed `node_modules` and made `npm install` - **the same result**.

> something is weird, it is really working,

Did you follow the flow described: Load page, first uncomment first two lines (debounce), reload should occur, and then uncomment the rest two lines (throttle)?

**Comment by devmondo** [comment] 2017-05-17 17:58
please, nuke your node_modules folder, fuse cache folder and build folder, start fresh. 

I assure you that i followed something is really off! try to nuke everything, including your build folder!

**Comment by whitecolor** [comment] 2017-05-17 18:12
Well I do this, the same result, maybe someone else will try? I'm doing this on Windows, though not sure why it should really matter for this case.

**Comment by devmondo** [comment] 2017-05-17 18:14
@whitecolor, i am on windows too!

**Comment by Ebuall** [comment] 2017-05-17 18:42
Having exactly the same on linux 
![screenshot_20170517_214023](https://cloud.githubusercontent.com/assets/10381141/26170323/b7d9f52e-3b49-11e7-80f3-c7b444ecfdea.png)

**Comment by nchanged** [comment] 2017-05-17 19:11
Ok, when you first load the page, your bundle doesn't contain the target library. On an HMR you are getting an error, and fusebox is trying to reload the page cuz the module wasn't loaded at all. My assumption is that something wrong happens in between.

Does it work for you if you bundle with uncommented section of your code, and keep working?

**Comment by whitecolor** [comment] 2017-05-17 20:43
> Does it work for you if you bundle with uncommented section of your code, and keep working?

Yes of course it works, check the repo yourself.

**Comment by nchanged** [comment] 2017-05-17 21:53
Well I don't have any problem there, whatsoever ;-) like @devmondo 
NodeJs version?

**Comment by whitecolor** [comment] 2017-05-17 22:19
v6.10.2

**Comment by devmondo** [comment] 2017-05-17 22:29
could you update to latest node please and see

**Comment by aretecode** [comment] 2017-05-18 00:30
I tried

## setup
- used yarn install
- ran watch with yarn 
- followed these steps https://github.com/fuse-box/fuse-box/issues/541#issuecomment-302170461
- on mac with node 7.10

## result
- worked for hmr
- had no errors

**Comment by whitecolor** [comment] 2017-05-18 16:59
I'm installed latest stable 6.10.3, the same result.

**Comment by whitecolor** [comment] 2017-05-18 17:46
I've added watch via docker and latest node image, it should use more immutable environment, please try it, see changed instructions in readme.

**Comment by devmondo** [comment] 2017-05-18 18:21
@whitecolor, I really think this is some OS related or hardware issue on your side. This is crazy as per above you can see that 3 different people on 3 different OSes and machines cloned and tried your repo, and there was no issue.

@nchanged  is there anything else possible we are missing, you might think of here?

**Comment by whitecolor** [comment] 2017-05-18 18:24
@devmondo did you tried docker version?

**Comment by nchanged** [comment] 2017-05-18 18:35
I just tried it.
![tesss](https://cloud.githubusercontent.com/assets/1629088/26217907/6c31c8fc-3c09-11e7-98d3-3061feb53231.gif)

No success;-( i mean failure.

**Comment by whitecolor** [comment] 2017-05-18 18:41
@nchanged 
try just to uncomment last two lines, **first two should not be commented** when running first time, follow steps in updated readme.

**Comment by nchanged** [comment] 2017-05-18 18:47
No matter how I tried, I cannot reproduce the issue

![sss222](https://cloud.githubusercontent.com/assets/1629088/26218374/0baa2446-3c0b-11e7-972e-0f8f4fe46ec2.gif)

**Comment by whitecolor** [comment] 2017-05-18 19:20
This his still a `heisenbug` I too sometimes have no error.
![fuse-box-xstream-issue-docker](https://cloud.githubusercontent.com/assets/736697/26219574/efdb9d44-3c28-11e7-949e-3e05867bd762.gif)

**Comment by nchanged** [comment] 2017-05-18 19:22
Could it be related to how fast you click save?

**Comment by whitecolor** [comment] 2017-05-18 19:33
I just save one time when I uncomment. It probably can relate to that change event is firing multiple times or something and fuse-box doesn't handle it well. Need to debug.

**Comment by devmondo** [comment] 2017-05-18 20:00
i think i know the issue, it is race condition, it happened to me with webstorm, try to open your project in notepad and not in VS code and see if this helps

**Comment by whitecolor** [comment] 2017-05-18 20:56
I tried with nodepad++ (notepad doesn't hanldle well LF line endings). Error is still here. And see nothing wrong with handling events https://github.com/fuse-box/fuse-box/blob/master/src/core/BundleProducer.ts#L98 there is no any racing events.

**Comment by devmondo** [comment] 2017-05-18 21:29
man! your case is crazy, can you try it on another machine( real not VM)

**Comment by whitecolor** [comment] 2017-05-18 21:32
We tried (two different people) and get the error on two different machines windows and linux. I'm not sure why don't get the error. In some case it is still should occur. I will try to provide better example or debug myself.

**Comment by nchanged** [comment] 2017-05-18 22:26
@whitecolor I believe that can happen. We have been struggling for a very long to get it to the state where it is now, but it's not perfect. Let me know if can help debugging it.

**Comment by xdave** [comment] 2017-05-20 09:44
Happens to me, too

**Comment by arabsight** [comment] 2017-05-20 11:13
I'm getting the error too (linux, node 7.10)

**Comment by aretecode** [comment] 2017-05-21 05:13
so windows & mac work, linux seems to have an issue...

**Comment by whitecolor** [comment] 2017-05-21 06:25
I'm getting this on Windows too, [you may see on my comment](https://github.com/fuse-box/fuse-box/issues/541#issuecomment-302170461)

**Comment by nchanged** [comment] 2017-05-21 06:38
You guys ... is it a blocker? :)

**Comment by xdave** [comment] 2017-05-21 06:50
Nope.  Tree-shaking is more important. :)

**Comment by nchanged** [comment] 2017-05-21 07:04
Good cuz I rather focus on a feature I am working ATM, it's quite an important one, and yes tree shaking is coming soon

**Comment by devmondo** [comment] 2017-05-21 12:26
out of interest, those of you who are facing this issue, do you have SSD drives or normal drives?

**Comment by whitecolor** [comment] 2017-05-21 13:22
> You guys ... is it a blocker? :)

Just an annoying bug.

> out of interest, those of you who are facing this issue, do you have SSD drives or normal drives?

SSD drives, Docker on windows uses SMB protocol

There is seem to be something wrong with a logic of injecting new dependencies, not platform specifics.

**Comment by nchanged** [comment] 2017-05-21 14:26
@whitecolor Does fuse refresh the page automatically? (Cuz it should if a package is not found)

**Comment by devmondo** [comment] 2017-05-21 14:52
@nchanged  could it be polling issue? should we test it with `chokidar` polling option?

**Comment by xdave** [comment] 2017-05-21 18:58
Normal drive here.  Haven't tested on my laptop SSD.

**Comment by devmondo** [comment] 2017-05-21 20:35
guys could you upgrade to latest beta we enabled passing options to `chokidar`  http://fuse-box.org/page/development#chokidar-options

let us know please :)

**Comment by devmondo** [comment] 2017-06-20 21:05
this should be working now with the latest version.

we will close this for now but let us know otherwise :)

**Closed by devmondo** 2017-06-20 21:05 UTC
Labels: discussion
