### ISSUE TITLE
3.6.0 => 3.7.0 breaks source maps

### ISSUE THREAD

**Issue by jpike88** [fuse-box/fuse-box#1493] opened 2019-02-09 08:39 UTC
Breakpoints are failing builds via 3.7.0... any idea why?

**Comment by nchanged** [comment] 2019-02-09 09:07
Can u try @next ?

**Comment by nchanged** [comment] 2019-02-09 09:09
They shouldn't be breaking tho

**Comment by jpike88** [comment] 2019-02-12 05:30
Breaks on 4.0.0-next.6

**Comment by jpike88** [comment] 2019-02-12 05:32
Breaks on 3.7.0-patch.1

**Comment by nchanged** [comment] 2019-02-12 05:41
Please reproduce it ... I have spent so much tweaking these source maps . I don't believe you )) all my projects are working flawlessly especially on 4.0

**Comment by jpike88** [comment] 2019-02-12 06:12
Downgraded to 3.6.0... works. Maybe my tsconfig will give you some indication?

**Comment by jpike88** [comment] 2019-02-12 06:13
```
{
  "compileOnSave": true,
  "compilerOptions": {
    "moduleResolution": "node",
    "target": "ESNext",
    "lib": [
      "esnext",
      "dom"
    ],
    "emitDecoratorMetadata": true,
    "outDir": "../dist",
    "sourceMap": true,
    "allowSyntheticDefaultImports": true,
    "noEmitHelpers": false,
    "noUnusedLocals": true,
    "resolveJsonModule": true,
    "noUnusedParameters": true,
    "noImplicitThis": true,
    "skipLibCheck": true,
    "experimentalDecorators": true,
    "baseUrl": "./",
    "paths": {
      "@client/*": ["./components/*"],
      "@shared/*": [
        "./../../shared/*"
      ],
      "@templates/*": [
        "./components/globalTemplates/*"
      ]
    }
  }
```

**Comment by nchanged** [comment] 2019-02-12 06:15
And your fuse.js ?

**Comment by jpike88** [comment] 2019-02-12 06:16
```
// bundle code and other assets
    const fuse = FuseBox.init({
        log: {
            enabled: false,
        },
        modulesFolder: "client/node_modules",
        target: (isProduction ? 'browser@es5' : 'browser@ESNext'),
        output: stagingDir + (isProduction ? "/$name.min.js" : "/$name.js"),
        allowSyntheticDefaultImports: true,
        hash: isProduction,
        alias: aliasPaths,
        tsConfig: (isProduction ? clientSrcDir + '/tsconfig-production.json' : clientSrcDir + '/tsconfig.json'),
        useTypescriptCompiler: true,
        package: {
            name: "default"
        },
        globals:{
            'reflect-metadata': 'reflectmetadata', // compensating for ng1
            'zone.js/dist/zone': 'zone', // compensating for ng1
            angular: 'angular',
            'chart.js': 'ChartJS',
            'whatwg-fetch': 'fetch',
            'pouchdb-browser': 'PouchDB',
            tinymce: 'tinymce',
            'lodash': '_'
        },
        plugins: [
            JSONPlugin(),
            isProduction && [
                "*.ts",
                ReplacePlugin({
                    "REPLACE_WITH_GIT_SHORT_HASH": gitHashShort,
                    "REPLACE_WITH_GIT_LONG_HASH": gitHashLong
                })
            ],
            isServerless && ["*.ts", ReplacePlugin({
                "http://localhost": (isServerlessProduction ? 'https://api.plantguard.tech' : 'https://staging.api.plantguard.tech'),
                "8081": "443"
            })],
            [CSSResourcePlugin({
                inline: true
            }), CSSPlugin()],
            WebIndexPlugin({
                template: clientSrcDir + "/index.html",
                path: '.'
            }),
            NgTemplatePlugin(),
            isProduction && QuantumPlugin({
                api: (core) => {
                    core.solveComputed("moment/moment.js");
                },
                polyfills: ["Promise"],
                bakeApiIntoBundle: false,
                processPolyfill: true,
                uglify: {
                    mangle: {
                        reserved: ['$scope']
                    }
                }
            })
        ]
    })

    const vendor = fuse.bundle("vendor");

    vendor.instructions(`> ${clientSrcDir}/components/polyfills.ts`);

    const app = fuse.bundle("app").sourceMaps(true);

    app.instructions(`> ${clientSrcDir}/components/app.ts - ${clientSrcDir}/components/**/*.d.ts`);

    if ((!skipServe && !isProduction) || (isProduction && useDevServer)) {
        var typeHelperConfig = {
            name: "Type Checker",
            tsConfig: 'tsconfig-production.json',
            basePath: './client/src/'
        };
        const typechecker = require('fuse-box-typechecker').TypeHelper(typeHelperConfig);
        typechecker.createThread();
        app.hmr().watch(path => {
                return path.match('shared/') || path.match('client/src/components/')
            })
            .completed(proc => {
                // run the type checker
                typechecker.inspectCodeWithWorker(Object.assign(typechecker.options, {
                    quit: false,
                    type: 'watch'
                }));
                typechecker.printResultWithWorker();
            });
        fuse.dev()
    }

    return fuse.run({
        chokidarPaths: ['shared/**/*', 'client/src/components/**/*']
    });
```

**Comment by nchanged** [comment] 2019-02-12 06:23
And how is it broken? Could you show an example ? One component

**Comment by jpike88** [comment] 2019-02-12 06:24
vscode breakpoints basically fail to kick in. Best I can do is provide the log from the debugger, I'll sort that today

**Comment by nchanged** [comment] 2019-02-12 06:50
@jpike88 
Add this `"inlineSources": true` to your `tsconfig.json` and clear the cache. It should fix it

@eddyw it seems that one is broken too with your new TypescriptScript, Please make sure it's tested

**Comment by nchanged** [comment] 2019-02-12 06:58
@jpike88 there might be another case, please check your vscode configuration and source map override field. Also, please inspect a few source maps, and check the paths. Does it work in browser?

**Comment by eddyw** [comment] 2019-02-12 08:55
@jpike88 hey, could you also share the typescript version installed that you're using?

**Comment by jpike88** [comment] 2019-02-12 08:56
3.3.1, ill try out the other suggestions you got shortly

**Comment by nchanged** [comment] 2019-02-12 10:47
@jpike88 also please try `publish 3.7.0-next.13` and `15` let's see 15th broke it

**Comment by eddyw** [comment] 2019-02-12 18:22
> @jpike88
> Add this `"inlineSources": true` to your `tsconfig.json` and clear the cache. It should fix it
> 
> @eddyw it seems that one is broken too with your new TypescriptScript, Please make sure it's tested

@nchanged 
https://github.com/fuse-box/fuse-box/blob/b476d491491d31e1ac5391fc2d2794eeef861a6b/src/core/TypescriptConfig.ts#L245-L246

The tests for `TypescriptConfig` include checking if `sourceMaps` and `inlineSources` are set to `true` when `useSourceMaps` is true

Btw, in v4. `await this.resolve(newFile, shouldIgnoreDeps);` should be `return` instead of `await`. Otherwise it maps each to array of `undefined` (if you `console.log` there you can see the difference :P)
https://github.com/fuse-box/fuse-box/blob/a9439990bf7c9efba4032712ad6ee59d0a084580/src/core/ModuleCollection.ts#L375-L384

**Comment by nchanged** [comment] 2019-02-13 19:45
@jpike88 any updates?

**Comment by eddyw** [comment] 2019-02-13 21:20
@jpike88  tested v4 with `launch.json`:
```javascript
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Debug Playground",
      "cwd": "${workspaceRoot}",
      "program": "${workspaceRoot}/dist/app.js",
      "sourceMapPathOverrides": {
        "/*": "${workspaceRoot}/*"
      },
      "sourceMaps": true
    }
  ]
}
```
And breakpoints and sourceMaps work well :P
If you're have a mono-repo and you have, for instance:
```
.vscode
-- launch.json
myapp
-- node_modules
-- src
-- fuse.js
```
The application root is set to `myapp` because it contains `node_modules`, so you'd need to override the path:
```
      "sourceMapPathOverrides": {
        "/*": "${workspaceRoot}/myapp/*"
      },
```

**Comment by jpike88** [comment] 2019-02-14 04:00
I had this 
```
"sourceMapPathOverrides": {
					"*": "${workspaceRoot}/*"
				}
```

**Comment by jpike88** [comment] 2019-02-14 04:01
Changing it to your suggestion didn't work

**Comment by jpike88** [comment] 2019-02-14 04:08
adding inlineSources didn't help either.. going to keep thinking about it

**Comment by jpike88** [comment] 2019-02-14 04:10
ill keep my vscode/tsconfig settings the same while messing around

**Comment by jpike88** [comment] 2019-02-14 05:09
Ok based on a diff between 3.6.0 and 4.0.0-next.6

https://github.com/fuse-box/fuse-box/compare/21c1ea...619b6c#diff-cb5978b5d218f988ba81132ae01eb62fR717

result.sourceMapText is undefined for an app file... continuing to investigate

**Comment by jpike88** [comment] 2019-02-14 05:25
OK so it looks like the tsConfig.getConfig() calls produce different results. 

Old result
```
{
    "compileOnSave": true,
    "compilerOptions": {
        "moduleResolution": "node",
        "target": "ES5",
        "importHelpers": true,
        "lib": ["es2015", "dom"],
        "sourceMap": true,
        "noEmitHelpers": true,
        "emitDecoratorMetadata": true,
        "allowSyntheticDefaultImports": true,
        "downlevelIteration": true,
        "resolveJsonModule": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "experimentalDecorators": true,
        "noImplicitThis": true,
        "skipLibCheck": true,
        "outDir": "../../dist/",
        "baseUrl": "./",
        "paths": {
            "@client/*": ["./components/*"],
            "@shared/*": ["./../../shared/*"],
            "@templates/*": ["./components/globalTemplates/*"]
        },
        "module": "commonjs"
    }
}
```


new result:

```
{
    "compilerOptions": {
        "moduleResolution": 2,
        "target": 1,
        "importHelpers": true,
        "lib": ["lib.es2015.d.ts", "lib.dom.d.ts"],
        "noEmitHelpers": true,
        "emitDecoratorMetadata": true,
        "allowSyntheticDefaultImports": true,
        "downlevelIteration": true,
        "resolveJsonModule": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "experimentalDecorators": true,
        "noImplicitThis": true,
        "skipLibCheck": true,
        "outDir": "/Users/joshua/Projects/aquipa/dist/",
        "baseUrl": "/Users/joshua/Projects/aquipa/client/src/",
        "paths": {
            "@client/*": ["./components/*"],
            "@shared/*": ["./../../shared/*"],
            "@templates/*": ["./components/globalTemplates/*"]
        },
        "module": 1
    },
    "errors": [],
    "compileOnSave": true,
    "raw": {
        "compileOnSave": true,
        "compilerOptions": {
            "moduleResolution": "node",
            "target": "es5",
            "importHelpers": true,
            "lib": ["es2015", "dom"],
            "sourceMap": true,
            "noEmitHelpers": true,
            "emitDecoratorMetadata": true,
            "allowSyntheticDefaultImports": true,
            "downlevelIteration": true,
            "resolveJsonModule": true,
            "noUnusedLocals": true,
            "noUnusedParameters": true,
            "experimentalDecorators": true,
            "noImplicitThis": true,
            "skipLibCheck": true,
            "outDir": "../../dist/",
            "baseUrl": "./",
            "paths": {
                "@client/*": ["./components/*"],
                "@shared/*": ["./../../shared/*"],
                "@templates/*": ["./components/globalTemplates/*"]
            }
        }
    },
    "typeAcquisition": {
        "enable": false,
        "include": [],
        "exclude": []
    },
    "wildcardDirectories": {
        "/users/joshua/projects/aquipa/client/src": 1
    }
}
```

**Comment by jpike88** [comment] 2019-02-14 05:26
I note that the `wildcardDirectories` property appears to have 'users' as lowercase instead of uppercase? I thought unix paths were case sensitive? Is that possibly a factor

**Comment by eddyw** [comment] 2019-02-14 05:42
@jpike `sourceMap` is missing in your new result. Was it tested with the same FuseBox config that you have shared?

Could you try adding instead `sourceMaps: true` in FuseBox options instead of `bundle(..).sourceMaps(true)`

**Comment by jpike88** [comment] 2019-02-14 06:03
OK, but I don't want to generate source maps for my other bundle.

It doesn't work, but I noticed a difference in how the source maps were generated.

old output starts with 
`"{"version":3,"file":"app.js","sourceRoot":"","sources":["file:///Users/joshua/Projects/aquipa/client/src/components/app.ts"]`

new output starts with 
`"{"version":3,"file":"app.js","sourceRoot":"","sources":["../client/src/components/app.ts"]`

Obviously, relative paths are now the method of choice versus absolute paths. Why was this changed

**Comment by nchanged** [comment] 2019-02-14 06:32
Are u trying to v4? Since there it should start with a slash

**Comment by nchanged** [comment] 2019-02-14 06:33
Remote outDir that might affect it too

**Comment by jpike88** [comment] 2019-02-14 06:37
Am using fuse-box@next for my testing, it should be up to date. I'll play with outDir shortly

**Comment by nchanged** [comment] 2019-02-14 06:49
@jpike88 `sourceMaps(true/false)` sets a global config (I know it's wrong and needs fixing). Please set it into FuseBox.init

**Comment by jpike88** [comment] 2019-02-14 09:32
I've set it to true, and I'm getting source maps, just with the different path. I'll try to tweak things to suit it

**Comment by nchanged** [comment] 2019-02-21 09:21
closing this for now chainable `sourceMaps()` is removed. Re-open if needed.

**Closed by nchanged** 2019-02-21 09:21 UTC

**Comment by athrunsun** [comment] 2019-02-21 09:56
@jpike88 @nchanged Will generating vendor sourcemaps for the first time very slow?

**Comment by nchanged** [comment] 2019-02-21 10:22
@athrunsun use `fuse-box@next` for this. It will cache it, and then it will be much faster.
