### ISSUE TITLE
HMR not updating CSS upon imported module change

### ISSUE THREAD

**Issue by graforlock** [fuse-box/fuse-box#757] opened 2017-08-28 19:55 UTC
As requested in `#730`, here is the repository that reproduces the issue:

https://github.com/graforlock/sass-compile-reproduce

In `index.js` :

```
require('./styles/styles.scss');
```

the `./styles/styles.scss` is:

```
@import "../lib/base";
@import "base/base";
```

Only updating the CSS of `./styles/styles.scss` triggers the HMR change.

**Comment by nchanged** [comment] 2017-08-28 20:05
Please read my response in the prev. issue.
This is not going to work by design

**Comment by graforlock** [comment] 2017-08-28 20:15
Yes, I have seen the response, only after I decided to delete the post.

So, by that I understand that atm, both in the newest betas (as it was suggested to use latest betas) and in `2.2.2` it isn't quite possible to achieve a sass workflow with importing scss configuration ? It does only kind of work when I keep updating and saving the root of scss which is `styles.scss`.

**Comment by nchanged** [comment] 2017-08-28 20:18
no, that was related to a one sass file that has internal dependencies like
`@import variables`

**Comment by graforlock** [comment] 2017-08-28 20:24
I like how it works by default, but right now cannot really use it to the full extend because of this missing piece. If that problem is solved I guess everyone will be extremely happy about the outcome as its already much faster than webpack.

**Comment by nchanged** [comment] 2017-08-28 20:27
@graforlock we are talking now about merging 2 separate processes. Like you may have 100 files and every file will require some css, you will lose flexibility and speed, and you can forget about caching in that case. Imagin gathering all sass files in your project and making one file. That's just not gonna happen.

You can solve your problem by using sass `@import` syntax, and fusebox understands it and make it super fast

**Comment by graforlock** [comment] 2017-08-28 20:46
Well I can, but as described before, it does not hot reload my styles.

**Comment by nchanged** [comment] 2017-08-28 21:55
It does, please reproduce the issue

**Comment by graforlock** [comment] 2017-08-28 22:26
I have just updated the repository along with the description to reproduce.

**Comment by rs3d** [comment] 2017-08-30 15:42
I've also the issue that changes to imported .scss files don't trigger a css rebuild. Only removing and adding the import line results in an updated css file. Even with `SassPlugin({ cache: false })`

**Comment by nchanged** [comment] 2017-08-30 15:55
@rs3d is it related to `_` before the filename? If it is, then it's a known issue and will be fixed soon

**Comment by rs3d** [comment] 2017-08-30 16:07
@nchanged nope, was using it without `_`.

**Comment by nchanged** [comment] 2017-08-30 16:16
@rs3d how about this repo https://github.com/fuse-box/fuse-box-examples/tree/master/examples/responsive_hmr_sass

**Comment by graforlock** [comment] 2017-08-30 17:41
But that repo assumes there's no directories inside and no external dependencies, as all `.scss` files are laid out in root, which is rarely the case.

**Comment by nchanged** [comment] 2017-08-30 18:51
@graforlock what do you mean? you can nest as much as you like. And it supports sass `importer` where you can define your own aliases

**Comment by graforlock** [comment] 2017-08-30 19:10
I can then confirm that whatever happens its the same scenario & outcome than that of what @rs3d is experiencing. Behaviour the same both my personal OSX machine and Windows 10 at work.

**Comment by nchanged** [comment] 2017-08-30 19:16
@graforlock @rs3d please create a repo to reproduce

```
require('./lib/_base.scss');
require('./styles/base/_base.scss');
require('./styles/styles.scss');
```

This creates 3 Sass Instances, and cannot be resolved as one file.

**Comment by graforlock** [comment] 2017-08-30 19:19
The current above repository  doesn't use this style of imports, after the update. It has `index.js` with:

`require('./styles/styles.scss');`

and `styles.scss` is:

```
@import "../lib/base";
@import "base/base";
```

But the end result is the same, it only hot module replaces  upon modifying styles.scss and none of the imported dependencies.

**Comment by nchanged** [comment] 2017-08-30 19:25
@graforlock then I would need a repository from you. Can you demonstrate it with `fuse-box@2.2.3-beta.16` ?

**Comment by graforlock** [comment] 2017-08-30 19:30
Its in the first post in the topic, it was updated along with instructions. Does it have to be specifically version `fuse-box@2.2.3-beta.16` ?

**Comment by nchanged** [comment] 2017-08-30 19:36
@graforlock oh yes, i just tried it, and it works, and you told me that you didn't have `_` in file names

```
→ CSS Dependency: styles/base/_base.scss depends on styles/styles.scss
```

I couldn't run the webapp for some reason, but the CSS is updated.
And yes, it has to be `fuse-box@2.2.3-beta.16`

**Comment by graforlock** [comment] 2017-08-30 20:13
I have recorded a video of what's happening with the persistent issue on `fuse-box@2.2.3-beta.16`:

https://youtu.be/EgD4MdDIhPY

**Comment by nchanged** [comment] 2017-08-30 20:26
@graforlock right... removing PostCSSPlugin helped me

**Comment by graforlock** [comment] 2017-08-30 20:35
That looks like its causing the issue. Unfortunately, I cannot develop anything without heavy company reliance on one postcss plugin which is a bit of a problem even in dev.

**Comment by nchanged** [comment] 2017-08-30 20:41
i have found a way to fix it, bare with me

**Comment by nchanged** [comment] 2017-08-30 20:45
@graforlock `fuse-box@2.2.3-beta.18` this fixes it

**Comment by graforlock** [comment] 2017-08-30 21:00
Looks like its working - good stuff :)) Waiting for the 2.2.3 release then, and will be using this beta for the time being.

**Comment by nchanged** [comment] 2017-08-30 21:01
Great, the release should be coming soon. Let's give it time for others to report.

**Closed by nchanged** 2017-08-30 21:01 UTC
Labels: discussion

**Comment by rs3d** [comment] 2017-08-31 09:21
@nchanged Sry, but fuse-box@2.2.3-beta.18 isn't resolving my issue. Changing an imported scss is still not updating the generated css file.
I've updated @graforlock's repo with the current version: https://github.com/rs3d/sass-compile-reproduce 
(i also removed postCSS to remove one possivble error source)
It would be great if you could have another look. Maybe I'm missing something essential?

**Comment by nchanged** [comment] 2017-08-31 10:33
@rs3d are you running on windows?

**Comment by rs3d** [comment] 2017-08-31 10:34
@nchanged yes

**Comment by rs3d** [comment] 2017-08-31 11:51
I've tried now https://github.com/fuse-box/fuse-box-examples/tree/master/examples/responsive_hmr_sass When i change foo.scss changes are directly visible. When I change shared.scss nothing happens until i change foo.scss again.

**Comment by rs3d** [comment] 2017-08-31 11:58
https://github.com/rs3d/fuse-box-examples/tree/master/examples/hmr-hosted-css-files/src
i extended my example with nested scss files:  https://github.com/rs3d/fuse-box-examples/tree/master/examples/hmr-hosted-css-files/src

It seems like it's conntected to the folder structure somehow. If I move `\hmr-hosted-css-files\src\styles\_imported.scss` and  `\hmr-hosted-css-files\src\styles\_variables.scss` one level up it seems to work...

**Comment by nchanged** [comment] 2017-08-31 12:01
@rs3d i think it's related to windows only....

**Comment by graforlock** [comment] 2017-08-31 14:48
I have just experienced this at work :( Indeed, Windows issue

**Comment by rs3d** [comment] 2017-08-31 14:56
@graforlock is this happening with the example repos or your real dev code?

**Comment by graforlock** [comment] 2017-08-31 15:19
both atm

**Comment by rs3d** [comment] 2017-08-31 16:10
@nchanged do u like to reopen this issue or do we need a new one?

**Comment by nchanged** [comment] 2017-08-31 16:17
@rs3d can you please create a new one? @graforlock guys, I would need you to help me debug this thing
