### ISSUE TITLE
Hot-reload with redux-provider

### ISSUE THREAD

**Issue by gerhardsletten** [fuse-box/fuse-box#148] opened 2017-02-12 23:33 UTC
Should this work? I have tried to extend the react-example with a typical setup with redux and react-router, but get and error `<Provider> does not support changing `store` on the fly...` when fuse-box tries to do a hot reload.

It also looks like the setting `cache: false` disables the hot-reload.

**Comment by skellock** [comment] 2017-02-13 01:58
Redux with hot reloading is working for me.  Mostly.  Something is off, and I can't quite put my finger on it.  

Usually you can get around that `<Provider>` warning by making changes to a component deeper down.  But for some reason it's causing the whole display tree to re-render.

If you want to not reload your store everytime, one option is to stick the instance on `global`,  `window`, or someplace equally as horrifying. 

```js
window.storeAndAlsoImGoingToHell = window.storeAndAlsoImGoingToHell || createStore()

// then later in your file
ReactDOM.render(
    <Provider store={window.storeAndAlsoImGoingToHell}>
        <Hello />
    </Provider>
    ,
    document.querySelector(element)
);
```

Also, can confirm, `cache: false` indeed seems to break hot-reload.

**Comment by nchanged** [comment] 2017-02-13 07:22
Hey guys!
Hot reload works only with cache on. Indeed, that's by design. At least for now. At the very moment, Hot reload flushes everything and reloads the entry point. Yes, there is a room for improvement. 

Let's discuss how can we do it more efficiently.

**Comment by gerhardsletten** [comment] 2017-02-13 09:21
@skellock Thanks got it working now. Actually I did not need to make the store global to have in preserved through a hot-reload. 

@nchanged Is the rule that the creation of the Provider, Routes show not be in the entry-file? There are probably more then me that are a little unsure of the success criteria's for hot-reload to work.

My test project can be found here, its still some work in progress.. 

[fuse-box-react-ssr](https://github.com/gerhardsletten/fuse-box-react-ssr)

**Comment by gerhardsletten** [comment] 2017-02-13 22:40
I have also discover that with EnvPlugin, the global var process is not available after a hot-reload, you need to do a import for it to be:

```js
import process from 'process'
console.log(process.env.someVar)
```

**Comment by nchanged** [comment] 2017-02-13 23:30
@gerhardsletten thanks! that's a real bug. Could you create a separate issue?

**Comment by nchanged** [comment] 2017-02-14 08:44
Guys, we are cooking HMR plugin support. You will have a full control on which module to reload.

**Comment by basarat** [comment] 2017-02-15 06:36
> <Provider> does not support changingstoreon the fly...

Basically you want to prevent flushing the cache for certain files. Working on it in https://github.com/fuse-box/fuse-box/pull/158#issuecomment-279927235 :rose:

**Comment by nchanged** [comment] 2017-02-17 15:41
Guys, what's the status?
This should help -> http://fuse-box.org/#loader-plugins

**Comment by skellock** [comment] 2017-02-17 19:33
I saw 117 just came out this morning, i'll give 'er another run tonight.

**Comment by skellock** [comment] 2017-02-17 19:33
Also, related... Holy balls.  You guys are killing it on this project.  😻

**Comment by nchanged** [comment] 2017-02-17 20:51
We should get more docs/examples on this subj, so stay tuned =)

**Comment by xdave** [comment] 2017-02-23 11:20
So yeah.  `react-redux` and `react-router` both complain when hot-reloading.

You have to go to hell three times if you use `react-router-redux`, as syncing the `browserHistory` singleton, creating the routes with the `Router` component, and using `Provider` all require a global variable when hot reloading.

**Comment by screendriver** [comment] 2017-07-09 15:12
So how can I solve this in my project? I have the same error logs with `<Provider />`

> Guys, what's the status?
> This should help -> http://fuse-box.org/#loader-plugins

The link doesn't work 😕  At the website I can't find anything related to `redux` or `react-redux`. The [HMR docs](http://fuse-box.org/page/development#custom-hmr) are not so clear for me that I can solve this issue.

**Comment by nchanged** [comment] 2017-07-10 05:49
Ok, maybe you tell us what's not clear :)

**Comment by screendriver** [comment] 2017-07-10 05:52
How can I enable HMR for my project that uses `redux` and `react-redux`. I still get the error message `<Provider> does not support changing`store`on the fly...` with the latest fuse-box version.

The workaround `window.storeAndAlsoImGoingToHell = window.storeAndAlsoImGoingToHell || createStore()` seems a little bit ugly to me.

And here at http://fuse-box.org/#loader-plugins I can't find anything related to this issue.

**Comment by nchanged** [comment] 2017-07-10 06:41
@screendriver you don't need to store it to the window, you can make a custom HMR
http://fuse-box.org/page/development#custom-hmr

**Comment by screendriver** [comment] 2017-07-11 14:00
Ok. Thank you. It would be great if there were a recipe or something for react / redux on the website 😉  I believe most of the developers out there that are switching or using fuse-box will run in this sooner or later.

**Comment by Shepless** [comment] 2017-11-05 11:18
@screendriver I'm doing some house keeping on older issues, is it ok to close this issue?

**Comment by screendriver** [comment] 2017-11-06 07:20
Theoretically it could be closed but I'm still missing some real examples / recipes in the docs regarding React / Redux and HMR 😉

**Comment by Shepless** [comment] 2017-11-06 07:23
We welcome any PRs from the community so if you can help us out in that regard that would be great!

**Closed by Shepless** 2017-11-06 07:23 UTC
Labels: enhancement

**Comment by atfzl** [comment] 2018-05-20 12:54
Hi All,

I've implemented redux hot-reload with fuse-box successfully, you can check it out at: https://github.com/atfzl/fuse-box-redux-starter.

The interesting stuff lies at https://github.com/atfzl/fuse-box-redux-starter/blob/master/src/ui/hmr/index.ts.

Please let me know if this works or if something can be added.
