### ISSUE TITLE
Scoped packages doesn't work without importing index

### ISSUE THREAD

**Issue by jperezdavinchi** [fuse-box/fuse-box#584] opened 2017-06-01 12:00 UTC
Hi!
with the new update of fuse-box the npm scoped packages created as bundles with fuse-box are out of action giving the "not found on request" error.

I tried with [fuse-box-npm-package-seed](https://github.com/fuse-box/fuse-box-npm-package-seed) with a npm local install (not link)  and it works, but when I add the scope `@f/use-box-npm-package-seed` the console shows the error.

You can find the modified npm seed [here](https://github.com/jperezdavinchi/fuse-box-npm-package-seed) and the example code [here](https://github.com/jperezdavinchi/fusebox-scoped-package.git)

### package.json & fuse.js
![image](https://cloud.githubusercontent.com/assets/28526655/26678181/9f5dc0a2-46cf-11e7-808b-6abd0f143470.png)

### index.ts
![image](https://cloud.githubusercontent.com/assets/28526655/26678004/ae739de2-46ce-11e7-92e0-d5a0b1894b88.png)

### Output:
![image](https://cloud.githubusercontent.com/assets/28526655/26677877/05a071e0-46ce-11e7-99d8-e566b7de4d13.png)

### Browser:
![image](https://cloud.githubusercontent.com/assets/28526655/26677902/2872a936-46ce-11e7-9e91-b4e686a015a1.png)

## About the "index":
Debugging and looking into the bundle I found:
![image](https://cloud.githubusercontent.com/assets/28526655/26677949/57694eac-46ce-11e7-9446-15546bb5540b.png)

I tried adding the `index` to the import, and it works!

![image](https://cloud.githubusercontent.com/assets/28526655/26678043/dd8de65a-46ce-11e7-8ad3-43ee609466fd.png)

![image](https://cloud.githubusercontent.com/assets/28526655/26678057/f1347c64-46ce-11e7-9cb7-49c23f5fa2c3.png)

But, I'd prefer to avoid refactoring all the projects adding the "index" to the imports.\
Am I doing something wrong with the config?\
The `@scope` couldn't be removed, the npm package is scoped and the imports should have the scope (like `@angular/core` for example).

In the previous version of fuse-box it works well without the "index".

**Comment by nchanged** [comment] 2017-06-01 12:18
@jperezdavinchi i don't think you can have a package name with `@`
`@` is a scoped repository. So you need to create a subfolders and use aliases instead for development.

Could you try it?

**Comment by jperezdavinchi** [comment] 2017-06-01 12:25
@nchanged this is for production not for development.

If I create a npm package and publish it to npm, `@haztivity/core` in my case,  it should be imported with `import {} from "@haztivity/core"`, right? (in production, doing `npm i @haztivity/core`)

In the package.json the name is `@haztivity/core` and in the docs sais that the package in fuse-box must be the same that in the package.json

node_modules for the previous example:
![image](https://cloud.githubusercontent.com/assets/28526655/26679542/d97ee7ec-46d5-11e7-9a5b-3eee07d3fe35.png)

**Comment by nchanged** [comment] 2017-06-01 12:32
that's right! You know what, can you omit @ in your package name, it will work as long as it's a unique name. My guess that `@` in the package name messing up with scope package resolving.

**Comment by jperezdavinchi** [comment] 2017-06-01 12:41
@nchanged remove the `@` from the fuse.js?
![image](https://cloud.githubusercontent.com/assets/28526655/26680121/5f71692c-46d8-11e7-8ef4-33a989a53333.png)

**Comment by nchanged** [comment] 2017-06-01 12:50
without slashes ;-) remove `/`

**Comment by jperezdavinchi** [comment] 2017-06-01 12:57
the same happens :(
![image](https://cloud.githubusercontent.com/assets/28526655/26680614/6cb5f84e-46da-11e7-8561-249d28c2a5a6.png)
![image](https://cloud.githubusercontent.com/assets/28526655/26680635/7e10bf20-46da-11e7-9417-8e4edc8e8559.png)

Now with the /index doesn't work neither.

**Comment by nchanged** [comment] 2017-06-01 12:57
that's what i am saying, you need alias it, and leave in the real @f/blba folder in production

**Comment by jperezdavinchi** [comment] 2017-06-01 12:59
so, anyone that want to use this package and do the `npm i @f/fuse-box-npm-package-seed` has to config an alias in fuse?

**Comment by nchanged** [comment] 2017-06-01 12:59
no it's only for development

**Comment by jperezdavinchi** [comment] 2017-06-01 13:00
I had the package installed in npm like in production
![image](https://cloud.githubusercontent.com/assets/28526655/26680799/06eb858c-46db-11e7-8d97-7104f937c9a0.png)

**Comment by nchanged** [comment] 2017-06-01 13:11
and that is correct. Now what you need to change is your project name. Don't add `@` there.  And when you are developing alias the real path in to a fake one.

**Comment by jperezruiz** [comment] 2017-06-01 13:19
Sorry I don't understand, could you share a screenshot please?

**Comment by nchanged** [comment] 2017-06-01 13:34
I don't have a screeтshot
```
alias : {
   "@foo/bar" : "foo-bar"
}
```

whereas foo-bar is a folder in your `customModules`

**Comment by jperezdavinchi** [comment] 2017-06-02 06:56
I'm sorry but I still don't understand.
Why I have to add the alias if the package is installed with npm and it's in the node_modules folder?
Please see https://github.com/jperezdavinchi/fusebox-scoped-package

**Comment by nchanged** [comment] 2017-06-02 07:09
Yes i have seen it. All i am saying that for development you trick it. And for production you will use the real scoped repository

**Comment by jperezdavinchi** [comment] 2017-06-21 12:24
With the version 2.1.0 this still failing.
I put the alias as you said but still failing
![image](https://user-images.githubusercontent.com/28526655/27383842-038b8632-568d-11e7-8b03-b85b4e56ba83.png)

I check it with FuseBox.exists
![image](https://user-images.githubusercontent.com/28526655/27383913-40406bf6-568d-11e7-8090-e268180b2ad4.png)

Any idea? :'(

**Comment by nchanged** [comment] 2017-06-21 12:40
@jperezdavinchi check your bundle source
for `FuseBox.pkg("@haztivity"` and copy paste the header please, also just __scope__.file("core/index)

**Comment by jperezdavinchi** [comment] 2017-06-23 07:35
Here is:
```typescript
(function(FuseBox){FuseBox.$fuse$=FuseBox;
FuseBox.pkg("@haztivity/core", {}, function(___scope___){
___scope___.file("index.js", function(exports, require, module, __filename, __dirname){
```

**Comment by nchanged** [comment] 2017-06-23 09:14
So does it work without aliases?

**Comment by nchanged** [comment] 2017-06-23 09:14
`import "@haztivity/core"`

**Comment by jperezdavinchi** [comment] 2017-06-23 10:24
nop :'(
![image](https://user-images.githubusercontent.com/28526655/27478156-f303b086-580e-11e7-9e62-5e45a9b9038b.png)

**Comment by nchanged** [comment] 2017-06-23 14:44
Well it's either not bundled or you request is wrong. Could you provide a test repository? Just a sample of your setup

**Comment by jperezdavinchi** [comment] 2017-06-26 08:13
I created two repo where you could reproduce the process:
The package to create the bundle: https://github.com/jperezdavinchi/fuse-box-npm-package-seed
The setup:
```typescript
const {FuseBox, Sparky} = require("fuse-box");

const fuse = FuseBox.init({
    homeDir: "./src",
    package: {
        name: '@f/fuse-box-npm-package-seed',
        main: 'index.ts'
    },
    globals: {'@f/fuse-box-npm-package-seed': '*'},
    output: "dist/$name.js",
});


fuse.bundle("index.js")
    .instructions("> index.ts");

fuse.run();
```

the package that installs the bundle of the previous package: https://github.com/jperezdavinchi/fusebox-scoped-package



The real case: 
https://github.com/haztivity/core
```typescript
const {FuseBox, UglifyJSPlugin} = require("fuse-box");
        let plugins = [];
        const fuseCore = FuseBox.init(
            {
                homeDir: "src",
                output: "dist/$name.js",
                globals: {
                    "@haztivity/core": {
                        "haztivity": "haztivity"
                    }
                },
                sourceMaps: true,
                package: {
                    name: "@haztivity/core",
                    main: "index.ts"
                },
                cache: false,
                shim: {
                    jquery: {
                        source: "node_modules/jquery/dist/jquery.js",
                        exports: "$"
                    }
                }
            }
        );
        fuseCore.bundle("haztivity-core")
                .instructions(`!> [index.ts]`);
        fuseCore.bundle("haztivity-core-standalone")
                .instructions(`> index.ts`);
        fuseCore.run();
        const fuseCoreMin = FuseBox.init(
            {
                homeDir: "src",
                output: "dist/$name.min.js",
                globals: {
                    "@haztivity/core": {
                        "haztivity": "haztivity"
                    }
                },
                package: {
                    name: "@haztivity/core",
                    main: "index.ts"
                },
                cache: false,
                plugins: plugins,
                shim: {
                    jquery: {
                        source: "node_modules/jquery/dist/jquery.js",
                        exports: "$"
                    }
                }
            }
        );
        fuseCoreMin.bundle("haztivity-core")
                   .instructions(`!> [index.ts]`);
        fuseCoreMin.bundle("haztivity-core-standalone")
                   .instructions(`> index.ts`);
        fuseCoreMin.run();
```

**Comment by jperezdavinchi** [comment] 2017-06-26 11:04
I tried using rollup with fusebox and it works.
```typescript
const {FuseBox, Sparky} = require("fuse-box");

const fuse = FuseBox.init({
    homeDir: "./src",
    package: {
        name: '@f/fuse-box-npm-package-seed',
        main: 'index.ts'
    },
    globals: {
        '@f/fuse-box-npm-package-seed': '@f/fuse-box-npm-package-seed'
    },
    rollup: {
        bundle: {
            moduleName: "@f/fuse-box-npm-package-seed",
        },
        entry: "index.js",
        treeshake: true
    },
    output: "dist/$name.js"
});


fuse.bundle("index.js")
    .instructions("> index.js");

fuse.run();

```

**Comment by Shepless** [comment] 2017-11-05 11:13
@jperezdavinchi @nchanged does this issue still need to be actioned?

**Comment by jperezdavinchi** [comment] 2017-12-18 10:31
Sorry @Shepless! I just read the comment. I removed fusebox from the dist flow and I didn't try again.
FuseBox has been changed a lot since then so I will check again and update/close the issue.
Thank you!

**Comment by RobinBuschmann** [comment] 2018-01-02 14:44
I've faced a similar issue. Fusebox bundles a package (which is bundled with fusebox as well) like so:

```js
FuseBox.pkg("@f/fuse-box-npm-package-seed", {}, function(___scope___){
return ___scope___.entry = "fuse-box-npm-package-seed/index.js";
});
```
The entry path is wrong. It should be ` ___scope___.entry = "index.js";` The problem is caused by this function: https://github.com/fuse-box/fuse-box/blob/master/src/analysis/plugins/OwnBundle.ts#L8
Scoped packages doesn't seem to be considered here, so that `@f/fuse-box-npm-package-seed/index.js` becomes `fuse-box-npm-package-seed/index.js` instead of `index.js`.

@nchanged I would like to create a pull request for that, but the tests seem to be failing on master  (without any change) :(

**Comment by nchanged** [comment] 2018-01-02 15:00
@RobinBuschmann you should make a Quantum build, with containedAPI : true option, then it will work

Here is something to read:
https://github.com/fuse-box/fuse-box/blob/doc-ver-3/docs/guides/publishing-to-npm.md

**Comment by RobinBuschmann** [comment] 2018-01-02 15:48
@nchanged Thanks, I will give it a try :)

**Comment by jcaron23** [comment] 2018-07-26 23:31
Hi all,

Had the same issue with scoped packages, but only when running [`nexe`](https://github.com/nexe/nexe) which uses fuse-box for packing.

It turns out to be linked to two issues:

1. In `core/PathMaster.ts` at the end of `getNodeModuleInformation`, it attempts to go just one level up searching for a `node_modules` folder with the requested module. This doesn't work for scoped packages where you need to go **two** levels up. There are probably issues as well with complex dependency graphs with several levels of node_modules (though I believe in many cases it will appear to work, but will probably use the wrong module version, see below).

    The solution is to run a loop going up one level at a time until the module is found, or you get to the root of the project.

2. When running `nexe`, the app root is that of `nexe` rather than that of the project. This results in pretty weird values for `NODE_MODULES_DIR` and `TEMP_FOLDER`. My impression is that those variables should be based on `homeDir` rather than the app root, but I'm not quite sure about all the implications of changing that.

    When running fuse-box directly, the correct app root means that PathMaster will in some cases fall back to a version of the requested module in the "root" `node_modules`, even if it's not the right version. That does not seem appropriate, but I don't know if there's a scenario where that makes sense.

    When using `nexe`, the incorrect `NODE_MODULES_DIR` means it does not find the module at all and silently ignores it.

I can provide a PR that addresses point 1, but I think point 2 is strongly related and should be addressed as well, though I'm wary of the consequences it might have.

**Comment by nchanged** [comment] 2018-07-27 07:21
@jcaron23 Hi! Please suggest a PR! That's a weak spot, and there is some room for improvements!

**Comment by nchanged** [comment] 2019-08-27 13:11
### FuseBox v4 Major Upgrade

As of today, the latest major version of FuseBox `v4` is available in `fuse-box@next`. FuseBox has undergone a full re-write from scratch, learning from its mistakes in the previous versions.

There are a lot of improvements, speed and config wise.

Get started [here](https://github.com/fuse-box/fuse-box/blob/master/docs/getting-started/get-started.md)

We are still working on the documentation and polishing before the major release. We are getting very close. And we need help testing.

```bash
npm install fuse-box@next
```

Most of the issues that I am closing have been resolved, however, if you find that your issue is still relevant in `v4` don't hesitate to re-open or (better) create a new one with `v4` configuration.

**Closed by nchanged** 2019-08-27 13:11 UTC
Labels: discussion
