### ISSUE TITLE
Watch does not stop after changing homeDir from ./ to ../

### ISSUE THREAD

**Issue by jrubstein** [fuse-box/fuse-box#1421] opened 2018-10-31 22:35 UTC
Hello,

I am trying to build a project using fuse-box (great tool, btw) that includes several sub-project in a monorepo. The `watch` was working perfectly until I changed the homeDir to the root path, that way I can use the `alias` to get the other projects into my bundle.
Once I changed the homeDir, the bundle works perfectly, however the watch does not stop. It kept re-building the same bundle.
Any idea what can cause this issue and how to fix it?
Thank you

**Comment by nchanged** [comment] 2018-11-01 08:35
Hi @jrubstein 
That's a known issue. Try to fit it all in your src folder. The problem is that `dist/` isn't ignored. I will fix it in this release

**Comment by jrubstein** [comment] 2018-11-01 18:20
Hello @nchanged ,

Thank you for your answer. Looking forward to the new release.
Regards,

**Comment by nchanged** [comment] 2018-11-01 19:02
#1425

**Comment by nchanged** [comment] 2018-11-01 19:09
FIxed in `3.7.0-next.1`

**Closed by nchanged** 2018-11-01 19:09 UTC
