### ISSUE TITLE
Not including files when calling TS from JS

### ISSUE THREAD

**Issue by wasd171** [fuse-box/fuse-box#641] opened 2017-06-28 12:28 UTC
Hello,

I have created a [repo](https://github.com/wasd171/fuse-error-example) to illustrate the bug. When `src/A.js` tries to import `~/shared` it gets transformed as `~/shared.js`. TypeScript version `src/B.ts` correctly resolves `~/shared` to `~/shared/index.ts` -> `~/shared/index.js`

**Comment by devmondo** [comment] 2017-06-28 12:40
it is because u r using typescript, and with typescript you have to define the extension if it is not `.ts`
so this should work `import { FOO } from "~/shared.js";

**Comment by wasd171** [comment] 2017-06-28 12:42
This is not a problem. Check the repo, it's already `shared/index.ts`. The problem is that JS does not get it (because there is no `shared/index.js`)

**Comment by devmondo** [comment] 2017-06-28 12:43
yep, that is conversion by Fuse. if you omitindex.ts we assume it is there.

**Comment by wasd171** [comment] 2017-06-28 12:43
But the problem is that you only assume it for TS files. In my case it is JS file trying to import TS file

**Comment by devmondo** [comment] 2017-06-28 12:44
what if you chamged you `src/A.js` to `src/A.ts`?

**Comment by wasd171** [comment] 2017-06-28 12:45
It would obviously work, `src/A.js` the same as `src/B.ts`, the difference is only in filenames and extensions

**Comment by devmondo** [comment] 2017-06-28 12:46
yep, u r right.

@nchanged  is this a bug or intended behavior?

**Comment by nchanged** [comment] 2017-06-28 13:04
It's not a bug but expected behaviour, you are mixing two different things. If you require a file from a javascript file one would expect to get a javascript file in return. Not a Typescript file, not CoffeeScript file, not a PYTHON file. 

And the same vice versa. If you import a js file from typescript, if you need to specify an extension.

**Comment by wasd171** [comment] 2017-06-28 13:07
@nchanged but you would get javascript anyway, actually. It is transpiled, so even a TS requiring TS would in fact require JS.

**Comment by wasd171** [comment] 2017-06-28 13:07
If I remember correctly, webpack handles this type of index.ext

**Comment by wasd171** [comment] 2017-06-28 13:09
And you have the ability to require CSS, JSON, etc, so it's already mixed

**Comment by wasd171** [comment] 2017-06-28 13:17
I have updated the repo because there is still one problem. Even if you specify the import extension the build is not performed correctly if you reexport something from `~/shared/index.ts`. Please check the repo to see what I mean, it is clear if you run `node dist/A-bundle.js` and `node dist/B-bundle.js`

**Comment by wasd171** [comment] 2017-06-28 13:20
To be clear:
```
JS -- import (with .ts) -> TS -- import (without ext) -> TS
```
causes errors

**Comment by nchanged** [comment] 2017-06-28 13:30
yes, because you cannot import a ts from javascript. That's a completely different environment. Typescript (high level) can reference a javascript file. But a low level (javascript) can't import a high one (typescript

**Comment by wasd171** [comment] 2017-06-28 13:31
I thought that under the hood every file was in fact JS file importing other JS files. Am I wrong?

**Comment by nchanged** [comment] 2017-06-28 14:29
js can import other js file yes

**Comment by wasd171** [comment] 2017-06-28 14:30
@nchanged right, so what happens inside the bundle when one TS file imports another TS file? Is it a piece of JS code referencing another piece of JS code?

**Comment by devmondo** [comment] 2017-06-28 14:45
@wasd171 it is still `A.js`?

**Comment by wasd171** [comment] 2017-06-28 14:56
@devmondo sorry, I am not getting it

**Comment by wasd171** [comment] 2017-06-28 15:44
My point is: internally everything we import and require transpiles to JS anyway. It is already possible to use non-JS formats like JSON and CSS. Why would you want to create unnecessary fragmentation? I don't see a reason here.

**Comment by nchanged** [comment] 2017-08-26 19:17
Closing this for now. If you have a proposal, please create a separate issue describing the problem and your solution. There must but a good reasoning behind it.

**Closed by nchanged** 2017-08-26 19:17 UTC
Labels: discussion

**Comment by xdave** [comment] 2018-05-01 07:28
@nchanged I did try that, and it resolves; but, the resulting module is `undefined`.

**Comment by nchanged** [comment] 2018-05-01 07:34
How about you do the way around, Make you entry point a typescript file, then import js files?

**Comment by xdave** [comment] 2018-05-01 07:37
OK that works.  In this case, the require()s for the .ts files must not have an extension.

**Comment by nchanged** [comment] 2018-05-01 07:38
that's right ;-)
